### ISSUE TITLE
Tab close icon not vertically aligned

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#100]
Cf screenshot:

<img width="333" alt="screen shot 2016-06-16 at 13 34 14" src="https://cloud.githubusercontent.com/assets/335567/16132250/31b61bc4-33c7-11e6-8b49-f11c4300c961.png">

At least it **seem** unaligned to me.

**Comment by sccolbert** [comment]
Looks like you are picking up a different font face than we test on. We need better fallbacks. Can list browser/os combination for this?

**Comment by Carreau** [comment]
OS X 10.10.3  – Chrome  52.0.2743.41 beta (64-bit)

I tried to force refresh/ rebuild , does not work. 

--- 

And FYI the layout is 80% broken on Safari (screenshot with **2** tabs open), but I dont' think we support Safari. 

<img width="1314" alt="screen shot 2016-06-16 at 13 47 01" src="https://cloud.githubusercontent.com/assets/335567/16132669/058e3804-33c9-11e6-9145-45a6512d041c.png">

**Comment by sccolbert** [comment]
Wow. That's amazingly bad. I thought newer versions of safari were supposed to be reasonably standards compliant.

**Comment by bliker** [comment]
@Carreau I think part of your css is not loading - apart from the sidebar bug everything seems to work fine for me.
