### ISSUE TITLE
Search placeholder text too strong

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyterlab#1003]
The placeholder text for the search box is now strong enough that it is very confused with any text you type in. Typically placeholder text will be lower contrast than the normal font, to give a hint that it is not actually text in the box.

<img width="376" alt="screen shot 2016-09-28 at 1 18 25 pm" src="https://cloud.githubusercontent.com/assets/192614/18930777/4f52ba62-857e-11e6-8a44-e7766f7b2aff.png">

**Comment by jasongrout** [comment]
I think the bright blue is also too heavy, and calls too much visual attention to it. But that's a separate issue from the placeholder looking like normal input.

**Comment by ellisonbg** [comment]
The reason we change to the bright blue background is that user tests were showing the users didn't realize it was a search driven interface. They would see the long list of actions and start to scroll through them. We can soften the blue a bit but it *should* be styled strongly to draw visual attention...
