### ISSUE TITLE
Allow custom MIME bundles of form `application/something+json`

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#1013]
In nbformat, we recently added the ability to have custom JSON based MIME types in bundles of the form: `application/something+json`. Examples are GeoJSON, Vega/VegaLite, etc.

I am working on a Vega/VegaLite rendering extension and it is all working for notebook output, but having trouble calling `RenderMime.render` as the argument is `IRenderOptions<string>` rather than `<string | JSONValue>`. Also, we will need to make the `MimeBundle` type more flexible:

https://github.com/jupyter/jupyterlab/blob/master/src/notebook/notebook/nbformat.ts#L89-L93

When we do this, we need to add tests to make sure that MIME bundles with the `+json` suffix are propagating through everything without ever being converted to strings and back.

@blink1073 @minrk @rgbkrk

**Comment by ellisonbg** [comment]
Let's also release 0.4.2 after this is fixed...

**Comment by rgbkrk** [comment]
Ah, whoop. Yeah that needs to generally match `application/(\w\.)+\+json` (though it's probably a bigger character set than that).
