### ISSUE TITLE
Provide FocusTracker for console

### ISSUE THREAD

**Issue by AlexTugarev** [jupyter/jupyterlab#1014]
We could make good use of a `FocusTracker<ConsolePanel>` from console plugin if it would be provides as a service in the same manner as it was done with the `FocusTracker<NotebookPanel>` from notebook plugin. 

Our custom `Widget` should be "linked" to the focused console to match users' expectations. 

Are there any objections to expose a `FocusTracker<ConsolePanel>`? Would you like to receive a PR with an implementation similar to the notebook plugin?

**Comment by blink1073** [comment]
That sounds good to me, a PR would be most welcome!

**Comment by AlexTugarev** [comment]
@blink1073, please have a look at PR https://github.com/jupyter/jupyterlab/pull/1025.

**Comment by blink1073** [comment]
Fixed by #1025, thanks!
