### ISSUE TITLE
Renaming files in the file browser tab moves them to $HOME directory.

### ISSUE THREAD

**Issue by frodera** [jupyter/jupyterlab#1015]
Steps to reproduce the issue:

1. In Jupypter lab web interface create a new directory from the _Files_ tab or the OS shell.
2. Double click in the newly created folder.
3. Create a new file.
4. Add some content to the file and save it.
5. Rename it via the _Files_ tab (single clicking on it).
6. Open the renamed file in a new tab.
7. The content in the file has disappeared (file is 0 bytes in size now).
8. The original file and its content has been moved to `$HOME` directory.

Software versions used:
* OS X 10.11.6
* Python 2.7.12 
* JupyterLab 0.4.1 (installed through Anaconda)
* Jupyter 1.0.0 (installed through Anaconda)
* Jupyter core 4.2.0 (installed through Anaconda)

**Comment by blink1073** [comment]
Nice catch, thanks @frodera!
