### ISSUE TITLE
MIME bundle injection triggers infinite loop

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#1031]
I tried the new MIME bundle injection API late last week and found that it works (yeah!) but triggers an infinite loop. I think this is what is happening:

* Original MIME bundle gets set on the model.
* The output view gets updated, which triggers the renderer for that original MIME bundle through rendermime
* That renderer calls  the injector, which adds a new MIME key/value to that output.
* But that is a model change, which triggers an entirely new pass of rendering that output.
* That blasts the view, which starts the renderer all over again, which changes the model yet again.
* Repeat forever...

@blink1073

**Comment by blink1073** [comment]
Fixed in #1024 by setting a guard flag around mime data injection on the widget.
