### ISSUE TITLE
URGENT: file saved in wrong directory (possible data loss)

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#1032]
I am observing data loss in some situations where JupyterLab is saving files:

* Open a new text file in JLab in a directory other than the top-level notebook directory.
* You will see that file in the file browser.
* However, when you edit the file, it is actually saving the file at the top-level notebook directory.

I think this is related to the new file opening dialogs and may also be a problem with notebooks.

@blink1073

**Comment by afshin** [comment]
Same as https://github.com/jupyter/jupyterlab/issues/1015

**Comment by sccolbert** [comment]
Can we update the title? This isn't really data loss. It's "files saving to the wrong directory".

**Comment by ellisonbg** [comment]
The problem is that the user often won't realize where the real file is saved. They will keep editing the version in their CWD, but each time they load from disk, those changes will be gone. I didn't realize the file had been saved elsewhere until much later...

**Comment by ellisonbg** [comment]
@afshin I have confirmed this affects notebooks as well...
