### ISSUE TITLE
New File created after selecting cancel in dialog

### ISSUE THREAD

**Issue by charnpreetsingh185** [jupyter/jupyterlab#1034]
![nbbug2](https://cloud.githubusercontent.com/assets/16314651/19130151/ea2fb8d4-8afe-11e6-8fd7-4c26e38387c4.gif)

**Comment by sccolbert** [comment]
May be related to #1015

**Comment by blink1073** [comment]
This is the same root cause as #1033, closing in favor of a single issue.
