### ISSUE TITLE
Fix Steve being sick

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#1046]
@blink1073 is feeling sick today. Can someone look into fixing that.

**Comment by jasongrout** [comment]
We actually only need one or two of the Steves - the rest can take turns being sick...

**Comment by jasongrout** [comment]
Definitely a 0.9-level bug!

**Comment by jasongrout** [comment]
Can't decide if it is feature parity, enhancement, or maintenance....

**Comment by blink1073** [comment]
Status: Nap + Steam-hood + Tea = progress

**Comment by ellisonbg** [comment]
closing as fixed in master
