### ISSUE TITLE
Stylized function outputs not displayed correctly

### ISSUE THREAD

**Issue by eskirk** [jupyter/jupyterlab#107]
<img width="1228" alt="screen shot 2016-06-17 at 3 29 42 pm" src="https://cloud.githubusercontent.com/assets/7052378/16167062/d7f3c4da-34a5-11e6-93f0-0fbc0e804d9a.png">

The lab (shown on the left) is not properly processing cell output that would result in a stylized function. Possibly has something to do with our sanitization as discussed in #49

**Comment by blink1073** [comment]
It looks like the mime type in the `execute_result` bundle might either be plain text or something we don't support.  Is that `sympy` code?  Do you mind posting the source code?

**Comment by eskirk** [comment]
[Typography.ipynb.zip](https://github.com/jupyter/jupyterlab/files/321432/Typography.ipynb.zip)

I was just looking at examples in this Typography.ipynb notebook that Brian gave me.

**Comment by blink1073** [comment]
Great, thanks, I'll take a look at this over the weekend.
