### ISSUE TITLE
Audit CSS selectors

### ISSUE THREAD

**Issue by sccolbert** [jupyter/jupyterlab#128]
I'm seeing some selectors which are arbitrarily increasing specificity e.g. `.jp-MarkdownCell-content.p-Widget` (seen quite a bit in #127).

Is this specificity increase needed?

CC @blink1073 @jasongrout

**Comment by blink1073** [comment]
This will go away once we explicitly load the CSS in order.

**Comment by ellisonbg** [comment]
Done in master!

#628 
#680
