### ISSUE TITLE
Link to API docs in README is a 404

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyterlab#13]
Team, If the API docs are built and rendered somewhere. I would like to use this as an issue on Monday for a Cal Poly intern sprint.

**Comment by willingc** [comment]
@jasongrout Any ideas where the API docs live or if the link in the README was just a placeholder?

**Comment by blink1073** [comment]
They will reside in `docs/api`, similar to https://github.com/phosphorjs/phosphor/pull/75.

**Comment by willingc** [comment]
Thanks @blink1073. Now I'm seeing at the bottom of the README that one needs to build the docs locally. Is there an easy way to autobuild and host the docs somewhere so that everyone can see them without building? Especially prior to sprints.

**Comment by willingc** [comment]
Ahh..So phosphor uses gh-pages to host the docs.

**Comment by blink1073** [comment]
Yes, which we do have working on the `jupyter-js-*` repos, just not here yet.

**Comment by blink1073** [comment]
Fixed by #44.
