### ISSUE TITLE
Markdown/HTML rendering difference/feature parity.

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#131]
Was open on jupyter/notebook, so cross linking here: 

https://github.com/jupyter/notebook/issues/1556

Seem that: 

- Code in rendered markdown is not highlighted. 
- HTML Table renders differently.

**Comment by afshin** [comment]
We might have to consider that if we want consistent behavior across JupyterLab and the notebook, it might be best to have server-side markdown rendering because it's often the case that different libraries like `marked` vs. `gfm` will diverge in the way they render the same source input.

**Comment by Carreau** [comment]
In the beginning of the notebook, we considered it. At the time it was not practical.

**Comment by ellisonbg** [comment]
No way on the server side rendering - too slow on bad networks

On Tue, Jun 21, 2016 at 10:00 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> In the beginning of the notebook, we considered it. At the time it was not
> practical.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyterlab/issues/131#issuecomment-227554188>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0AU6JO8QUFsvD5J0ZgmlD5JldSljks5qOELkgaJpZM4I7DFU>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jasongrout** [comment]
+1 on client-side rendering.

**Comment by fperez** [comment]
I think this should be 0.99 material, but I could imagine bumping it to 1.0 if we are drowning.

**Comment by jasongrout** [comment]
See also https://github.com/jupyter/jupyterlab/issues/272 about evaluating markdown-it as a commonmark-compliant renderer.

**Comment by blink1073** [comment]
Notes: #538 adds code highlighting to markdown, but we still need to style the tables and use the default ipython theme here: https://github.com/jupyter/notebook/blob/41d6da235cbf3bcf6d7f818e11a066e0fd12ff8b/notebook/static/notebook/less/highlight.less
