### ISSUE TITLE
Console icon

### ISSUE THREAD

**Issue by afshin** [jupyter/jupyterlab#132]
In order to add the web console (which is the web port of the Jupyter Qt Console application) to the landing page of JupyterLab, we need a logo for this screen:

<img width="430" alt="screen shot 2016-06-21 at 8 42 10 pm" src="https://cloud.githubusercontent.com/assets/159529/16243755/b26aba22-37f0-11e6-912c-83aba5f708ea.png">

Something like the current IPython logo...

![230453](https://cloud.githubusercontent.com/assets/159529/16243781/cdcc4042-37f0-11e6-82d6-c2f08509cc6d.png)

... which emphasizes a terminal that has some additional capabilities is a good place to start. The web console can display graphical widgets but also behaves like a terminal session and a graphic that reflects that would be helpful to aid the process of discovery of a different way JupyterLab offers to talk to a kernel outside of using a notebook.

cc: @willingc @ellisonbg

**Comment by afshin** [comment]
@Carreau pointed out another good icon, the icon for: https://github.com/unconed/TermKit

**Comment by Carreau** [comment]
Sidenote, the SVG of the QtConsole Icon is there : https://github.com/jupyter/qtconsole/blob/master/qtconsole/resources/icon/JupyterConsole.svg

Also it would happily get a refresh to not say IPython if we end up having multiple availables isons.

**Comment by willingc** [comment]
@ellisonbg Which intern would be best suited to this task?

**Comment by eskirk** [comment]
@willingc @matt-bowers

**Comment by ellisonbg** [comment]
Team Calisto has been assigned the landing page, so it would be @matt-bowers

On Tue, Jun 21, 2016 at 12:10 PM, Elliot Kirk <notifications@github.com>
wrote:

> @willingc <https://github.com/willingc> @matt-bowers
> <https://github.com/matt-bowers>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyterlab/issues/132#issuecomment-227587852>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0BGkiwR40UTYNXyl7mEK8BQ9wOI2ks5qOGFegaJpZM4I7Gis>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by SylvainCorlay** [comment]
My 2 cents:

- Change the prompt for the terminal to  `$ _`
- A console prompt for the interactive console `> _` with the Jupyter logo around it without the "document" paper sheet behind it.

**Comment by JamiesHQ** [comment]
Hi @ellisonbg & @willingc, 
@afshin was hoping this could get done before SciPy so folks who learn about JupyterLab during the SciPy talks can download JupyterLab and see the icon in the console. Is this possible? Does Team Calisto have the bandwidth to finish this work by SciPy? Thanks!

**Comment by matt-bowers** [comment]
Hi @JamiesHQ (and everyone)!
I've been working on the icons still briefly! I redesigned the page icons, as well as the terminal and the console icon. I designed them so they would still look consistent with the current "look" of JupyterLab, but I can always make any design changes if necessary. Here's a few preview pictures of what I have so far:

**Jupyter Notebook:**
![jupyter lab launcher icons-01](https://cloud.githubusercontent.com/assets/9501647/16597241/ba9b25c6-42ac-11e6-8bab-adab02a3009a.png)

**Text Editor:**
![jupyter lab launcher icons-02](https://cloud.githubusercontent.com/assets/9501647/16597243/ba9e8e6e-42ac-11e6-95b9-91169631e197.png)

**Terminal:**
![jupyter lab launcher icons-03](https://cloud.githubusercontent.com/assets/9501647/16597239/ba9a6b9a-42ac-11e6-8743-c70d2ff5931b.png)

**Console** (Iteration 1):
![jupyter lab launcher icons-04](https://cloud.githubusercontent.com/assets/9501647/16597240/ba9af75e-42ac-11e6-92aa-6b07747d4be9.png)

**Console** (Iteration 2):
![jupyter lab launcher icons-05](https://cloud.githubusercontent.com/assets/9501647/16597242/ba9b3dcc-42ac-11e6-9de8-38719e278c31.png)

**Comment by willingc** [comment]
@afshin Will these icons done by @matt-bowers work for the SciPy demo? They can always be redone at a later date.

**Comment by matt-bowers** [comment]
@afshin @willingc @JamiesHQ These can also be redone or re-styled anytime before SciPy (within reason). They only took about an hour to redesign, and most of it was incorporating a grid to keep the icons consistent.

Examples of grid:

![jupyter-lab-launcher-icons-01-grid](https://cloud.githubusercontent.com/assets/9501647/16598227/b5379fe2-42b1-11e6-9cac-8ed359911f66.png)

![jupyter-lab-launcher-icons-03-grid](https://cloud.githubusercontent.com/assets/9501647/16598228/b53b727a-42b1-11e6-86c6-d7593d9c826c.png)

**Comment by afshin** [comment]
I like this one:

https://cloud.githubusercontent.com/assets/9501647/16597242/ba9b3dcc-42ac-11e6-9de8-38719e278c31.png

Unless somebody has an objection, how about I use that so that we have it in place for SciPy? It's still alpha software, so I think the logo of one of its components changing if we decide to iterate won't be disruptive.

**Comment by willingc** [comment]
@afshin Sounds good to me. Thanks!

**Comment by matt-bowers** [comment]
Thanks for the feedback @afshin! I'm linking the SVG files to all of the icons below so you can use them for the launcher. Let me know if you need any changes or anything else!

[Jupyter Lab Launcher Icon SVGs.zip](https://github.com/jupyter/jupyterlab/files/348767/Jupyter.Lab.Launcher.Icon.SVGs.zip)

**Comment by matt-bowers** [comment]
Thanks for the feedback @afshin! I'm attaching all of the SVGs for the icons below so you can implement them how you'd like in Jupyter Lab. @JamiesHQ @willingc 

[Jupyter Lab Launcher Icons.zip](https://github.com/jupyter/jupyterlab/files/348776/Jupyter.Lab.Launcher.Icons.zip)

**Comment by afshin** [comment]
@matt-bowers @willingc

Sweet, thanks!

**Comment by willingc** [comment]
Thanks @matt-bowers @afshin. Closing :door:

**Comment by SylvainCorlay** [comment]
@afshin if would probably make sense to also use the new terminal icon since it is styled similarly.

**Comment by SylvainCorlay** [comment]
Quick remark on the new icons:

I think that they are too complicated - too many details... Double border line, circle with reduced version of the jupyter logo, and prompt in the middle. I would reduce the whole thing to the prompt for both terminal and console.

**Comment by afshin** [comment]
@SylvainCorlay good call on using the new terminal icon as well 👍 

As far as the new console icon goes, though, I think that end users won't know the difference between a "terminal" and a "console" right away, because both are used interchangeably in common parlance. So my inclination is to have a visual icon that makes it very clear that one of these is a "Jupyter" thing while the other is more generically a command prompt.

Anyone else have thoughts on this?

**Comment by ellisonbg** [comment]
I will to a design iteraction with Matt tomorrow - the icons for the
terminal and console need to be different enough to tell the difference -
and it is a bit subtle - even the names "console" and "terminal" probably
are not clear enough...

Cheers,

Brian

On Wed, Jul 6, 2016 at 11:32 PM, A. Darian <notifications@github.com> wrote:

> @SylvainCorlay <https://github.com/SylvainCorlay> good call on using the
> new terminal icon as well 👍
>
> As far as the new console icon goes, though, I think that end users won't
> know the difference between a "terminal" and a "console" right away,
> because both are used interchangeably in common parlance. So my inclination
> is to have a visual icon that makes it very clear that one of these is a
> "Jupyter" thing while the other is more generically a command prompt.
>
> Anyone else have thoughts on this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyterlab/issues/132#issuecomment-230992704>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0GUk33aEpdStcV5nQ6HOQ0BlD_epks5qTJ2RgaJpZM4I7Gis>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by SylvainCorlay** [comment]
I was thinking of both having a prompt in the middle and
- add a stylized computer around the prompt for the terminal.
- add a jupyter logo around the prompt for the console.

**Comment by ellisonbg** [comment]
Also thinking that the console icon should use our console prompts of `In
[1]:` and `Out[1]:`

On Wed, Jul 6, 2016 at 11:42 PM, Sylvain Corlay <notifications@github.com>
wrote:

> I was thinking of both having a prompt in the middle and
> - add a stylized computer around the prompt for the terminal.
> - add a jupyter logo around the prompt for the console.
> On Jul 7, 2016 8:35 AM, "Brian E. Granger" <notifications@github.com>
> wrote:
>
> > I will to a design iteraction with Matt tomorrow - the icons for the
> > terminal and console need to be different enough to tell the difference -
> > and it is a bit subtle - even the names "console" and "terminal" probably
> > are not clear enough...
> >
> > Cheers,
> >
> > Brian
> >
> > On Wed, Jul 6, 2016 at 11:32 PM, A. Darian <notifications@github.com>
> > wrote:
> >
> > > @SylvainCorlay <https://github.com/SylvainCorlay> good call on using
> the
> > > new terminal icon as well 👍
> > >
> > > As far as the new console icon goes, though, I think that end users
> won't
> > > know the difference between a "terminal" and a "console" right away,
> > > because both are used interchangeably in common parlance. So my
> > inclination
> > > is to have a visual icon that makes it very clear that one of these is
> a
> > > "Jupyter" thing while the other is more generically a command prompt.
> > >
> > > Anyone else have thoughts on this?
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > <
> https://github.com/jupyter/jupyterlab/issues/132#issuecomment-230992704
> > >,
> > > or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AABr0GUk33aEpdStcV5nQ6HOQ0BlD_epks5qTJ2RgaJpZM4I7Gis
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Brian E. Granger
> > Associate Professor of Physics and Data Science
> > Cal Poly State University, San Luis Obispo
> > @ellisonbg on Twitter and GitHub
> > bgranger@calpoly.edu and ellisonbg@gmail.com
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/jupyter/jupyterlab/issues/132#issuecomment-230993288
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ACSXFnAbUsi_QcwqYpPh6sj1uV92q_Jnks5qTJ4lgaJpZM4I7Gis
> >
> > .
>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyterlab/issues/132#issuecomment-230994934>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0DywkWKoHkXDI5dHDN2dRJ1FmYl0ks5qTJ_BgaJpZM4I7Gis>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
