### ISSUE TITLE
Odd completion issue in console: executed code doesn't see full completion

### ISSUE THREAD

**Issue by fperez** [jupyter/jupyterlab#148]
Consider the following in the console: I type `from ipywidgets import IntS<TAB>`. I get the completion pop-up, and it only shows a single completion, `IntSlider`. I hit `Enter` and it completes, then I hit `Shift-Enter` and it executes. But it seems that the internal buffer never got updated with the extra text from the completion, because it gives this error:

![image](https://cloud.githubusercontent.com/assets/57394/16314703/079f8f60-3934-11e6-937d-502b58f09c00.png)

This is obviously a bug. More generally, the completion behavior in the console and notebook should match what IPython does at the console as much as possible (e.g., when there's only one unambigous completion, the text buffer should fully complete without showing a pop-up, etc).  Completion is one of the most automatic, muscle-memory tasks we have, so we need to work extra hard in reducing variance between our clients in its behavior, or we'll drive users (me included :) crazy.

**Comment by afshin** [comment]
@fperez, are you using a recent pull of `master`? This sounds like an issue I fixed a little while ago, so can you confirm your version, please?

**Comment by fperez** [comment]
Yes, this is on current master of `jupyterlab` right now, specifically I'm on fdb564f. Can you replicate it?

**Comment by afshin** [comment]
I can't replicate it, no. The version I'm running appears to work correctly when following your exact steps. Could you try clearing your browser cache?

**Comment by afshin** [comment]
This is what I see:

![completion](https://cloud.githubusercontent.com/assets/159529/16315916/0e43b970-397c-11e6-8a3b-09bbbdc90d65.gif)

**Comment by fperez** [comment]
testing now and making sure I do a full rebuild of the JS assets. I'm getting weird errors there, so I nuked everything out and I'm doing a full rebuild from scratch. Hang tight.

**Comment by fperez** [comment]
OK, this is odd... I did a full git clean, full rebuild and source install, and I definitely see changes, but not what we wanted :(  Now I have no tab completion at all! Does this make sense to you?

**Comment by fperez** [comment]
This was after a full `git clean -fdx .`, then `npm install` at the top, as per the README instructions...

**Comment by afshin** [comment]
Are there errors in your JS console?

**Comment by fperez** [comment]
nope, fully clean

**Comment by afshin** [comment]
That is perplexing. Do you have a few minutes to do a screenshare?

**Comment by fperez** [comment]
Now, I just opened a *notebook* and that did give an error:

![image](https://cloud.githubusercontent.com/assets/57394/16316225/5e1213c6-393a-11e6-8b8c-9c5271588afe.png)

**Comment by fperez** [comment]
Sure!

**Comment by fperez** [comment]
Bluejeans?

**Comment by fperez** [comment]
Or appear.in?

**Comment by afshin** [comment]
https://appear.in/jupyter please

**Comment by fperez** [comment]
Wow, this is really odd! While I was in a different window, the pop-up completions for the notebook appeared all of a sudden! With a good minute of lag...

**Comment by afshin** [comment]
Thanks! This was an issue related to the build instructions being incomplete. It will be addressed in a later PR that will reference this issue.
