### ISSUE TITLE
trying with some existing notebook, jupyterlab seems to hang at opening of the notebook

### ISSUE THREAD

**Issue by stonebig** [jupyter/jupyterlab#15]
(with jupyterlab-0.0.5.tar.gz)

this notebook hangs at opening, before even trying to execute the mere first cell:
https://github.com/winpython/winpython_afterdoc/blob/master/docs/Winpython_checker.ipynb

maybe it's an incompatibility with bokeh/bqplot/ipywidgets ? Still, to hang at opening is a bit strange to me, as I open a notebook with cleared output cells.

Windows/python3.5.1:

Name | Version | Description
-----|---------|------------
[Python](http://www.python.org/) | 3.5.1 | Python programming language with standard library
[adodbapi](http://pypi.python.org/pypi/adodbapi) | 2.6.0.7 | A pure Python package implementing PEP 249 DB-API using Microsoft ADO.
[alabaster](http://pypi.python.org/pypi/alabaster) | 0.7.8 | A configurable sidebar-enabled Sphinx theme
[astroid](http://pypi.python.org/pypi/astroid) | 1.4.5 | Rebuild a new abstract syntax tree from Python's ast (required for pylint)
[astroml](http://pypi.python.org/pypi/astroml) | 0.3 | tools for machine learning and data mining in Astronomy
[babel](http://pypi.python.org/pypi/babel) | 2.3.2 | Internationalization utilities
[backports-abc](http://pypi.python.org/pypi/backports-abc) | 0.4 | A backport of recent additions to the 'collections.abc' module.
[backports.shutil-get-terminal-size](http://pypi.python.org/pypi/backports.shutil-get-terminal-size) | 1.0.0 | A backport of the get_terminal_size function from Python 3.3's shutil.
[baresql](http://pypi.python.org/pypi/baresql) | 0.7.3 | playing SQL directly on Python datas
[bcolz](http://pypi.python.org/pypi/bcolz) | 1.0.0 | columnar and compressed data containers.
[beautifulsoup4](http://pypi.python.org/pypi/beautifulsoup4) | 4.4.1 | Screen-scraping library
[blaze](http://pypi.python.org/pypi/blaze) | 0.10.1 | Blaze
[blosc](http://pypi.python.org/pypi/blosc) | 1.3.2 | Blosc data compressor
[bloscpack](http://pypi.python.org/pypi/bloscpack) | 0.9.0 | Command line interface to and serialization format for Blosc
[bokeh](http://pypi.python.org/pypi/bokeh) | 0.11.1 | Statistical and novel interactive HTML plots for Python
[boto3](http://pypi.python.org/pypi/boto3) | 1.3.1 | The AWS SDK for Python
[botocore](http://pypi.python.org/pypi/botocore) | 1.4.24 | Low-level, data-driven core of boto 3.
[bottleneck](http://pypi.python.org/pypi/bottleneck) | 1.0.0 | Fast NumPy array functions written in Cython
[bqplot](http://pypi.python.org/pypi/bqplot) | 0.6.1 | Interactive plotting for the Jupyter notebook, using d3.js and ipywidgets.
[brewer2mpl](http://pypi.python.org/pypi/brewer2mpl) | 1.4.1 | Connect colorbrewer2.org color maps to Python and matplotlib
[certifi](http://pypi.python.org/pypi/certifi) | 2016.2.28 | Python package for providing Mozilla's CA Bundle.
[cffi](http://pypi.python.org/pypi/cffi) | 1.6.0 | Foreign Function Interface for Python calling C code.
[click](http://pypi.python.org/pypi/click) | 6.6 | A simple wrapper around optparse for powerful command line utilities.
[cloudpickle](http://pypi.python.org/pypi/cloudpickle) | 0.2.1 | Extended pickling support for Python objects
[colorama](http://pypi.python.org/pypi/colorama) | 0.3.7 | Cross-platform colored terminal text
[commonmark](http://pypi.python.org/pypi/commonmark) | 0.5.4 | Python parser for the CommonMark Markdown spec
[cvxopt](http://abel.ee.ucla.edu/cvxopt) | 1.1.7 | Convex optimization library
[cx-freeze](http://cx-freeze.sourceforge.net) | 4.3.4 | Deployment tool which converts Python scripts into stand-alone Windows executables (i.e. target machine does not require Python or any other library to be installed)
[cycler](http://pypi.python.org/pypi/cycler) | 0.10.0 | Composable style cycles
[cyordereddict](http://pypi.python.org/pypi/cyordereddict) | 1.0.0 | Cython implementation of Python's collections.OrderedDict
[cython](http://www.cython.org) | 0.24 | Cython is a language that makes writing C extensions for the Python language as easy as Python
[cytoolz](http://pypi.python.org/pypi/cytoolz) | 0.8.0 | Cython implementation of Toolz: High performance functional utilities
[dask](http://pypi.python.org/pypi/dask) | 0.9.0 | Minimal task scheduling abstraction
[datashape](http://pypi.python.org/pypi/datashape) | 0.5.2 | A data description language
[db.py](http://pypi.python.org/pypi/db.py) | 0.4.4 | a db package that doesn't suck
[decorator](http://pypi.python.org/pypi/decorator) | 4.0.10 | Better living through Python with decorators
[dill](http://pypi.python.org/pypi/dill) | 0.2.5 | serialize all of python (almost)
[distributed](http://pypi.python.org/pypi/distributed) | 1.10.2 | Distributed computing
[docopt](http://pypi.python.org/pypi/docopt) | 0.6.2 | Pythonic argument parser, that will make you smile
[docrepr](http://pypi.python.org/pypi/docrepr) | 0.1.0 | docrepr renders Python docstrings in HTML.
[docutils](http://docutils.sourceforge.net) | 0.12 | Text processing system for processing plaintext documentation into useful formats, such as HTML or LaTeX (includes reStructuredText)
[emcee](http://pypi.python.org/pypi/emcee) | 2.1.0 | Kick ass affine-invariant ensemble MCMC sampling
[entrypoints](http://pypi.python.org/pypi/entrypoints) | 0.2.2 | Discover and load entry points from installed packages
[fasteners](http://pypi.python.org/pypi/fasteners) | 0.14.1 | A python package that provides useful locks.
[flask](http://pypi.python.org/pypi/flask) | 0.11.1 | A microframework based on Werkzeug, Jinja2 and good intentions
[flask-cors](http://pypi.python.org/pypi/flask-cors) | 2.1.2 | A Flask extension adding a decorator for CORS support
[formlayout](http://formlayout.googlecode.com) | 1.1.0 | Module for creating form dialogs/widgets to edit various type of parameters without having to write any GUI code
[geopy](http://pypi.python.org/pypi/geopy) | 1.11.0 | Python Geocoding Toolbox
[greenlet](http://pypi.python.org/pypi/greenlet) | 0.4.9 | Lightweight in-process concurrent programming
[guidata](http://packages.python.org/guidata) | 1.7.5 | Automatically generated graphical user interfaces for easy data set edition and display
[guiqwt](http://packages.python.org/guiqwt) | 3.0.2 | Efficient curve/image plotting and other GUI tools for scientific data processing software development
[h5py](http://pypi.python.org/pypi/h5py) | 2.6.0 | General-purpose Python interface to HDF5 files (unlike PyTables, h5py provides direct access to the full HDF5 C library)
[holoviews](http://pypi.python.org/pypi/holoviews) | 1.5.0 | Composable, declarative data structures for building complex visualizations easily.
[html5lib](http://pypi.python.org/pypi/html5lib) | 0.9999999 | HTML parser based on the WHATWG HTML specification
[husl](http://pypi.python.org/pypi/husl) | 4.0.3 | Human-friendly HSL (Hue-Saturation-Lightness)
[idlex](http://pypi.python.org/pypi/idlex) | 1.13 | IDLE Extensions for Python
[imagesize](http://pypi.python.org/pypi/imagesize) | 0.7.1 | Getting image size from png/jpeg/jpeg2000/gif file
[ipykernel](http://pypi.python.org/pypi/ipykernel) | 4.3.1 | IPython Kernel for Jupyter
[ipyleaflet](http://pypi.python.org/pypi/ipyleaflet) | 0.2.0 | A Jupyter widget for dynamic Leaflet maps
[ipyparallel](http://pypi.python.org/pypi/ipyparallel) | 5.0.1 | Interactive Parallel Computing with IPython
[ipython](http://pypi.python.org/pypi/ipython) | 4.2.0 | Enhanced Python shell
[ipython-genutils](http://pypi.python.org/pypi/ipython-genutils) | 0.1.0 | Vestigial utilities from IPython
[ipython-sql](http://pypi.python.org/pypi/ipython-sql) | 0.3.7.1 | RDBMS access via IPython
[ipywidgets](http://pypi.python.org/pypi/ipywidgets) | 5.1.5 | IPython HTML widgets for Jupyter
[itsdangerous](http://pypi.python.org/pypi/itsdangerous) | 0.24 | Various helpers to pass trusted data to untrusted environments and back.
[jedi](http://pypi.python.org/pypi/jedi) | 0.9.0 | An autocompletion tool for Python that can be used for text editors
[jinja2](http://pypi.python.org/pypi/jinja2) | 2.8 | Sandboxed template engine (provides a Django-like non-XML syntax and compiles templates into executable python code)
[jmespath](http://pypi.python.org/pypi/jmespath) | 0.9.0 | JSON Matching Expressions
[joblib](http://pypi.python.org/pypi/joblib) | 0.9.4 | Lightweight pipelining: using Python functions as pipeline jobs.
[jsonschema](http://pypi.python.org/pypi/jsonschema) | 2.5.1 | An implementation of JSON Schema validation for Python
[julia](http://pypi.python.org/pypi/julia) | 0.1.1.8 | Python interface to the Julia language
[jupyter](http://pypi.python.org/pypi/jupyter) | 1.0.0 | Jupyter metapackage. Install all the Jupyter components in one go.
[jupyter-client](http://pypi.python.org/pypi/jupyter-client) | 4.3.0 | Jupyter metapackage. Install all the Jupyter components in one go.
[jupyter-console](http://pypi.python.org/pypi/jupyter-console) | 4.1.1 | Jupyter metapackage. Install all the Jupyter components in one go.
[jupyter-core](http://pypi.python.org/pypi/jupyter-core) | 4.1.0 | Jupyter metapackage. Install all the Jupyter components in one go.
[keras](http://pypi.python.org/pypi/keras) | 1.0.4 | Theano-based Deep Learning library
[lasagne](http://pypi.python.org/pypi/lasagne) | 0.2.dev1 | neural network tools for Theano
[lazy-object-proxy](http://pypi.python.org/pypi/lazy-object-proxy) | 1.2.2 | A fast and thorough lazy object proxy.
[llvmlite](http://pypi.python.org/pypi/llvmlite) | 0.11.0 | lightweight wrapper around basic LLVM functionality
[lmfit](http://pypi.python.org/pypi/lmfit) | 0.9.3 | Least-Squares Minimization with Bounds and Constraints
[locket](http://pypi.python.org/pypi/locket) | 0.2.0 | File-based locks for Python for Linux and Windows
[lxml](http://pypi.python.org/pypi/lxml) | 3.6.0 | Powerful and Pythonic XML processing library combining libxml2/libxslt with the ElementTree API.
[markdown](http://pypi.python.org/pypi/markdown) | 2.6.6 | Python implementation of Markdown.
[markupsafe](http://pypi.python.org/pypi/markupsafe) | 0.23 | Implements a XML/HTML/XHTML Markup safe string for Python
[matplotlib](http://pypi.python.org/pypi/matplotlib) | 1.5.2rc2 | 2D plotting library (embeddable in GUIs created with PyQt)
[mistune](http://pypi.python.org/pypi/mistune) | 0.7.2 | The fastest markdown parser in pure Python, inspired by marked.
[mkl-service](https://github.com/ContinuumIO/mkl-service) | 1.1.2 | Python bindings to some MKL service functions
[monotonic](http://pypi.python.org/pypi/monotonic) | 1.1 | An implementation of time.monotonic() for Python 2 & < 3.3
[mpld3](http://pypi.python.org/pypi/mpld3) | 0.2 | D3 Viewer for Matplotlib
[mpmath](http://pypi.python.org/pypi/mpmath) | 0.19 | Python library for arbitrary-precision floating-point arithmetic
[msgpack-python](http://pypi.python.org/pypi/msgpack-python) | 0.4.7 | MessagePack (de)serializer.
[multipledispatch](http://pypi.python.org/pypi/multipledispatch) | 0.4.8 | A relatively sane approach to multiple dispatch in Python
[mysql-connector-python](http://pypi.python.org/pypi/mysql-connector-python) | 2.0.4 | MySQL driver written in Python
[nbconvert](http://pypi.python.org/pypi/nbconvert) | 4.2.0 | Converting Jupyter Notebooks
[nbformat](http://pypi.python.org/pypi/nbformat) | 4.0.1 | The Jupyter Notebook format
[nbsphinx](http://pypi.python.org/pypi/nbsphinx) | 0.2.8 | Jupyter Notebook Tools for Sphinx
[netcdf4](http://pypi.python.org/pypi/netcdf4) | 1.2.4 | python/numpy interface to netCDF library (versions 3 and 4)
[networkx](http://pypi.python.org/pypi/networkx) | 1.11 | Python package for creating and manipulating graphs and networks
[nltk](http://pypi.python.org/pypi/nltk) | 3.2.1 | The Natural Language Toolkit (NLTK) is a Python package for natural language processing.
[nose](http://somethingaboutorange.com/mrl/projects/nose) | 1.3.7 | nose is a discovery-based unittest extension (e.g. NumPy test module is using nose)
[notebook](http://pypi.python.org/pypi/notebook) | 4.2.1 | # Jupyter Notebook
[numba](http://pypi.python.org/pypi/numba) | 0.26.0 | compiling Python code using LLVM
[numexpr](http://pypi.python.org/pypi/numexpr) | 2.6.0 | Fast evaluation of array expressions elementwise by using a vector-based virtual machine
[numpy](http://numpy.scipy.org/) | 1.10.4 | NumPy: multidimensional array processing for numbers, strings, records and objects (SciPy''s core module)
[numpydoc](http://pypi.python.org/pypi/numpydoc) | 0.6.0 | Sphinx extension to support docstrings in Numpy format
[oct2py](http://pypi.python.org/pypi/oct2py) | 3.5.7 | Python to GNU Octave bridge --> run m-files from python.
[odo](http://pypi.python.org/pypi/odo) | 0.5.0 | Data migration in Python
[pandas](http://pypi.python.org/pypi/pandas) | 0.18.1 | Powerful data structures for data analysis, time series and statistics
[pandas-datareader](http://pypi.python.org/pypi/pandas-datareader) | 0.2.0 | Data readers extracted from the pandas codebase,should be compatible with recent pandas versions
[param](http://pypi.python.org/pypi/param) | 1.3.2 | Declarative Python programming using Parameters.
[partd](http://pypi.python.org/pypi/partd) | 0.3.3 | Appendable key-value storage
[patsy](http://pypi.python.org/pypi/patsy) | 0.4.1 | Describing statistical models using symbolic formulas
[pep8](http://pypi.python.org/pypi/pep8) | 1.7.0 | Python style guide checker
[pg8000](http://pypi.python.org/pypi/pg8000) | 1.10.5 | PostgreSQL interface library
[pickleshare](http://pypi.python.org/pypi/pickleshare) | 0.7.2 | Tiny 'shelve'-like database with concurrency support
[pillow](http://pypi.python.org/pypi/pillow) | 3.2.0 | Python Imaging Library (fork)
[pip](http://pypi.python.org/pypi/pip) | 8.1.2 | A tool for installing and managing Python packages
[pkginfo](http://pypi.python.org/pypi/pkginfo) | 1.3.2 | Query metadatdata from sdists / bdists / installed packages.
[prettytable](http://pypi.python.org/pypi/prettytable) | 0.7.2 | A simple Python library for easily displaying tabular data in a visually appealing ASCII table format.
[prompt-toolkit](http://pypi.python.org/pypi/prompt-toolkit) | 1.0.0 | Library for building powerful interactive command lines in Python
[psutil](http://code.google.com/p/psutil) | 4.2.0 | Provides an interface for retrieving information on all running processes and system utilization (CPU, disk, memory, network) in a portable way
[ptpython](http://pypi.python.org/pypi/ptpython) | 0.34 | Python REPL build on top of prompt_toolkit
[pulp](http://pypi.python.org/pypi/pulp) | 1.6.1 | PuLP is an LP modeler written in python. PuLP can generate MPS or LP files and call GLPK, COIN CLP/CBC, CPLEX, and GUROBI to solve linear problems
[py](http://pypi.python.org/pypi/py) | 1.4.31 | library with cross-python path, ini-parsing, io, code, log facilities
[pyaudio](http://pypi.python.org/pypi/pyaudio) | 0.2.9 | Bindings for PortAudio v19, the cross-platform audio input/output stream library.
[pybars3](http://pypi.python.org/pypi/pybars3) | 0.9.1 | Handlebars.js templating for Python 3 and 2
[pycparser](http://pypi.python.org/pypi/pycparser) | 2.14 | C parser in Python
[pyflakes](http://pypi.python.org/pypi/pyflakes) | 1.2.3 | passive checker of Python programs
[pygments](http://pygments.org) | 2.1.3 | Generic syntax highlighter for general use in all kinds of software
[pylint](http://www.logilab.org/project/pylint) | 1.5.5 | Logilab code analysis module: analyzes Python source code looking for bugs and signs of poor quality
[pymc](http://pypi.python.org/pypi/pymc) | 2.3.6 | Markov Chain Monte Carlo sampling toolkit.
[pymc3](http://pypi.python.org/pypi/pymc3) | 3.0 | Markov Chain Monte Carlo sampling toolkit.
[pymeta3](http://pypi.python.org/pypi/pymeta3) | 0.5.1 | Pattern-matching language based on Meta for Python 3 and 2
[pymongo](http://pypi.python.org/pypi/pymongo) | 3.2.2 | Python driver for MongoDB <http://www.mongodb.org>
[pyodbc](http://pypi.python.org/pypi/pyodbc) | 3.0.10 | DB API Module for ODBC
[pyopengl](http://pyopengl.sourceforge.net) | 3.1.1 | Cross platform Python binding to OpenGL and related APIs
[pyparsing](http://pyparsing.wikispaces.com/) | 2.1.4 | A Python Parsing Module
[pyqt5](http://www.riverbankcomputing.co.uk/software/pyqt/intro) | 5.6 | Python bindings for the Qt cross platform GUI toolkit
[pyqtgraph](http://pypi.python.org/pypi/pyqtgraph) | 0.9.10 | Scientific Graphics and GUI Library for Python
[pyreadline](http://pypi.python.org/pypi/pyreadline) | 2.1 | IPython needs this module to display color text in Windows command window
[pyserial](http://pypi.python.org/pypi/pyserial) | 3.1 | Library encapsulating the access for the serial port
[pystache](http://pypi.python.org/pypi/pystache) | 0.5.4 | Mustache for Python
[pytest](http://pypi.python.org/pypi/pytest) | 2.9.1 | pytest: simple powerful testing with Python
[python-dateutil](http://labix.org/python-dateutil) | 2.5.3 | Powerful extensions to the standard datetime module
[python-hdf4](http://pypi.python.org/pypi/python-hdf4) | 0.9 | Python-HDF4: Python interface to the NCSA HDF4 library
[pythonnet](http://pypi.python.org/pypi/pythonnet) | 2.1.0 | .Net and Mono integration for Python
[pythonqwt](http://pypi.python.org/pypi/pythonqwt) | 0.5.5 | Qt plotting widgets for Python
[pytz](http://pypi.python.org/pypi/pytz) | 2016.4 | World Timezone Definitions for Python
[pywin32](http://pypi.python.org/pypi/pywin32) | 220.1 | Python library for Windows
[pyyaml](http://pypi.python.org/pypi/pyyaml) | 3.11 | YAML parser and emitter for Python
[pyzmq](http://pypi.python.org/pypi/pyzmq) | 15.2.0 | Lightweight and super-fast messaging based on ZeroMQ library (required for IPython Qt console)
[qtawesome](http://pypi.python.org/pypi/qtawesome) | 0.3.3 | FontAwesome icons in PyQt and PySide applications
[qtconsole](http://pypi.python.org/pypi/qtconsole) | 4.2.1 | Jupyter Qt console
[qtpy](http://pypi.python.org/pypi/qtpy) | 1.0.2 | Provides an abstraction layer on top of the various Qt bindings (PyQt5, PyQt4 and PySide) and additional custom QWidgets.
[recommonmark](http://pypi.python.org/pypi/recommonmark) | 0.4.0 | A markdown parser for docutils
[redis](http://pypi.python.org/pypi/redis) | 2.10.5 | Python client for Redis key-value store
[reportlab](http://www.reportlab.org) | 3.3.0 | The PDF generation library
[requests](http://pypi.python.org/pypi/requests) | 2.10.0 | Requests is an Apache2 Licensed HTTP library, written in Python, for human beings.
[requests-toolbelt](http://pypi.python.org/pypi/requests-toolbelt) | 0.6.2 | Requests is an Apache2 Licensed HTTP library, written in Python, for human beings.
[rope-py3k](http://pypi.python.org/pypi/rope-py3k) | 0.9.4.post1 | a python refactoring library...
[rpy2](http://pypi.python.org/pypi/rpy2) | 2.7.8 | Python interface to the R language (embedded R)
[rx](http://pypi.python.org/pypi/rx) | 1.5.2 | Reactive Extensions (Rx) for Python
[s3fs](http://pypi.python.org/pypi/s3fs) | 0.0.5 | Convenient Filesystem interface over S3
[scikit-image](http://pypi.python.org/pypi/scikit-image) | 0.12.3 | Image processing toolbox for SciPy
[scikit-learn](http://pypi.python.org/pypi/scikit-learn) | 0.17.1 | A set of Python modules for machine learning and data mining
[scikit-neuralnetwork](http://pypi.python.org/pypi/scikit-neuralnetwork) | 0.7 | Deep neural networks without the learning cliff! A wrapper library compatible with scikit-learn.
[scilab2py](http://pypi.python.org/pypi/scilab2py) | 0.6 | Python to Scilab bridge
[scipy](http://www.scipy.org) | 0.17.1 | SciPy: Scientific Library for Python (advanced math, signal processing, optimization, statistics, ...)
[seaborn](http://pypi.python.org/pypi/seaborn) | 0.7.1 | statistical data visualization
[setuptools](http://pypi.python.org/pypi/setuptools) | 21.2.2 | Download, build, install, upgrade, and uninstall Python packages - easily
[simplegeneric](http://pypi.python.org/pypi/simplegeneric) | 0.8.1 | Simple generic functions (similar to Python's own len(), pickle.dump(), etc.)
[simplejson](http://pypi.python.org/pypi/simplejson) | 3.8.2 | Simple, fast, extensible JSON (JavaScript Object Notation) encoder/decoder
[sip](http://pypi.python.org/pypi/sip) | 4.18 | 
[six](http://pypi.python.org/pypi/six) | 1.10.0 | Python 2 and 3 compatibility utilities
[snowballstemmer](http://pypi.python.org/pypi/snowballstemmer) | 1.2.1 | This package provides 16 stemmer algorithms (15 + Poerter English stemmer) generated from Snowball algorithms.
[sphinx](http://pypi.python.org/pypi/sphinx) | 1.4.3 | Tool for generating documentation which uses reStructuredText as its markup language
[sphinx-rtd-theme](http://pypi.python.org/pypi/sphinx-rtd-theme) | 0.1.9 | Tool for generating documentation which uses reStructuredText as its markup language
[spyder](http://pypi.python.org/pypi/spyder) | 3.0.0.dev0 | Scientific PYthon Development EnviRonment: designed for interactive computing and data visualisation with a simple and intuitive user interface
[sqlalchemy](http://www.sqlalchemy.org) | 1.0.13 | SQL Toolkit and Object Relational Mapper
[sqlite-bro](http://pypi.python.org/pypi/sqlite-bro) | 0.8.11 | a graphic SQLite Client in 1 Python file
[sqlparse](http://pypi.python.org/pypi/sqlparse) | 0.1.19 | Non-validating SQL parser
[statsmodels](http://pypi.python.org/pypi/statsmodels) | 0.6.1 | Statistical computations and models for use with SciPy
[sympy](http://pypi.python.org/pypi/sympy) | 1.0 | Symbolic Mathematics Library
[tables](http://www.pytables.org) | 3.2.2 | Package based on HDF5 library for managing hierarchical datasets (extremely large amounts of data)
[tblib](http://pypi.python.org/pypi/tblib) | 1.3.0 | Traceback serialization library.
[theano](http://pypi.python.org/pypi/theano) | 0.8.2 | Optimizing compiler for evaluating mathematical expressions on CPUs and GPUs.
[toolz](http://pypi.python.org/pypi/toolz) | 0.8.0 | List processing tools and functional utilities
[tornado](http://pypi.python.org/pypi/tornado) | 4.3 | Scalable, non-blocking web server and tools (required for IPython notebook)
[traitlets](http://pypi.python.org/pypi/traitlets) | 4.2.1 | Traitlets Python config system
[twine](http://pypi.python.org/pypi/twine) | 1.6.5 | Collection of utilities for interacting with PyPI
[twitter](http://pypi.python.org/pypi/twitter) | 1.17.1 | An API and command-line toolset for Twitter (twitter.com)
[wcwidth](http://pypi.python.org/pypi/wcwidth) | 0.1.6 | Measures number of Terminal column cells of wide-character codes
[werkzeug](http://pypi.python.org/pypi/werkzeug) | 0.11.10 | The Swiss Army knife of Python web development
[wheel](http://pypi.python.org/pypi/wheel) | 0.29.0 | A built-package format for Python.
[widgetsnbextension](http://pypi.python.org/pypi/widgetsnbextension) | 1.2.3 | IPython HTML widgets for Jupyter
[winpython](http://winpython.github.io/) | 1.6.20160531 | WinPython distribution tools, including WPPM (package manager)
[wordcloud](http://pypi.python.org/pypi/wordcloud) | 1.2.1 | A little word cloud generator
[wrapt](http://pypi.python.org/pypi/wrapt) | 1.10.8 | A Python module for decorators, wrappers and monkey patching.
[xarray](http://pypi.python.org/pypi/xarray) | 0.7.2 | N-D labeled arrays and datasets in Python
[xlrd](http://pypi.python.org/pypi/xlrd) | 1.0.0 | Extract data from Microsoft Excel spreadsheet files
[xlsxwriter](http://pypi.python.org/pypi/xlsxwriter) | 0.9.0 | A Python module for creating Excel XLSX files.
[zarr](http://pypi.python.org/pypi/zarr) | 1.0.0 | A minimal implementation of chunked, compressed, N-dimensional arrays for Python.

**Comment by stonebig** [comment]
to the opposite, this one is working perfect:

https://github.com/winpython/winpython_afterdoc/blob/master/docs/seaborn_demo_from_jakevdp.ipynb

**Comment by jasongrout** [comment]
Does the winpython notebook render for you? It does for me: 
<img width="1330" alt="screen shot 2016-06-07 at 5 11 34 pm" src="https://cloud.githubusercontent.com/assets/192614/15874787/f78eea66-2cd2-11e6-9a6f-844496f40b2e.png">

**Comment by stonebig** [comment]
it does render, but an initial jupyterlab scripts never finishes to run:
![jupyterlab01](https://cloud.githubusercontent.com/assets/4312421/15883342/a904ce4a-2d47-11e6-9e30-a67ffe5d54f7.PNG)

![jupyterlab02](https://cloud.githubusercontent.com/assets/4312421/15883345/adfaee2a-2d47-11e6-8eb2-b8d3b859ed25.PNG)

**Comment by stonebig** [comment]
apparently, the problem is on firefox, but not on chrome. chrome is ok (or its javascript cache is ok, don't know)

**Comment by jasongrout** [comment]
When I try on FF 47 on OS X 10.10, it is depressingly slow to open that notebook and execute any cells: maybe 10 seconds to render, and then several seconds to, for example focus on a cell after clicking on it: 
![ff](https://cloud.githubusercontent.com/assets/192614/15934545/fb0fd442-2e31-11e6-8d03-28672980bf7e.gif)

**Comment by jasongrout** [comment]
Using the profiler, I see that this line is being executed once for every cell in the notebook every time, for example, the selected cell changes. It causes massive slowdowns in Chrome too, but maybe Chrome is faster overall.

https://github.com/jupyter/jupyterlab/blob/master/src/codemirror/widget.ts#L91

(technical info for fixing the bug) Basically, when something like the selected cell changes, an update event is propagated by phosphor, which causes the layout to send a resize event with an unknown size. Each codemirror widget gets this event and asks Codemirror to refresh, which takes a long time (roughly 10-20ms). We can mitigate this by: (1) using a smarter phosphor layout, which tells us exactly what size the codemirror should be, (2) having at most one codemirror - the currently edited cell, and replace all other codemirrors with rendered code, (3) being smarter about calling codemirror's refresh method.

CC @sccolbert, FYI.

**Comment by jasongrout** [comment]
Thinking more about it, telling us exactly what size codemirror should be would still involve a call to codemirror.refresh(), and I don't think we can be too much smarter about callling codemirror's refresh method, since it may be that a splitter was dragged, so we would need to call refresh anyway. We could maybe set a definite size for codemirror and manage that, but then we lose some of the dynamic sizing.

It seems that the biggest bang for the buck is to switch the notebook widget to having one codemirror active at a time, and all others being read-only views generated by codemirror.

**Comment by blink1073** [comment]
Agreed, cf https://github.com/jupyter/jupyter-js-notebook/issues/200

**Comment by sccolbert** [comment]
(2) is the best solution. Only have one code mirror at a time - the cell which is being edited.

**Comment by sccolbert** [comment]
Also, would be interesting to know why you are getting an `update-request` message when a cell is selected. Something in the notebook must be triggering that, which it sounds like it shouldnt be at this point.

**Comment by jasongrout** [comment]
I *think* this `.update()` call is the thing triggering the messages whenever the active cell gets updated: https://github.com/jupyter/jupyterlab/blob/master/src/notebook/notebook/widget.ts#L395. Steve, is that needed?

**Comment by blink1073** [comment]
I don't believe that is the source, but I'll have to dig deeper.

**Comment by jasongrout** [comment]
I think I was seeing first an update request, and then from that a resize request was being propagated.

**Comment by jasongrout** [comment]
This makes a *world* of difference:

```diff
diff --git a/src/notebook/notebook/widget.ts b/src/notebook/notebook/widget.ts
index 3734458..c44ce83 100644
--- a/src/notebook/notebook/widget.ts
+++ b/src/notebook/notebook/widget.ts
@@ -368,7 +368,8 @@ class ActiveNotebook extends NotebookRenderer {
       }
     }
     this.stateChanged.emit({ name: 'mode', oldValue, newValue });
-    this.update();
+    this.onUpdateRequest(new Message('update-request'));
+    //this.update();
   }
 
   /**
@@ -392,7 +393,8 @@ class ActiveNotebook extends NotebookRenderer {
       }
     }
     this.stateChanged.emit({ name: 'activeCellIndex', oldValue, newValue });
-    this.update();
+    //this.update();
+    this.onUpdateRequest(new Message('update-request'));
   }
 
   /**
@@ -400,7 +402,8 @@ class ActiveNotebook extends NotebookRenderer {
    */
   select(widget: BaseCellWidget): void {
     Private.selectedProperty.set(widget, true);
-    this.update();
+    this.onUpdateRequest(new Message('update-request'));
+    //this.update();
   }
 
   /**
@@ -411,7 +414,8 @@ class ActiveNotebook extends NotebookRenderer {
    */
   deselect(widget: BaseCellWidget): void {
     Private.selectedProperty.set(widget, false);
-    this.update();
+    this.onUpdateRequest(new Message('update-request'));
+    //this.update();
   }
 
   /**
```

**Comment by blink1073** [comment]
Ah, right, an update on a panel triggers and update of all visible child widgets.

**Comment by fperez** [comment]
I just tested with master, and the notebook referenced above now opens just fine for me (about the same time as opening it in the old notebook UI).

Should we close this?

**Comment by stonebig** [comment]
closing. will re-open a new one if I encouter the issue with latest versions. thanks.
