### ISSUE TITLE
Consider reducing menu clutter with "New console" when a user has many language kernels

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyterlab#152]
I noticed that since I have multiple kernels installed that the Console menu has all of the kernels listed. It struck me as a bit odd especially if I had a few more kernels installed R, ruby... This may just be a personal preference to have less items but just giving a heads up.

![screen shot 2016-06-23 at 12 17 39 pm](https://cloud.githubusercontent.com/assets/2680980/16316809/f716e996-393c-11e6-9835-76449a35a3ce.png)

**Comment by sccolbert** [comment]
This is the command palette. It's not exactly a "menu". The palette will always have "lots of stuff" in it, because it represents all commands installed in the system. The idea is that fuzzy completion makes it quick to narrow down that list.

When the MenuBar is added, it will have a more "curated" set of items shown.

**Comment by willingc** [comment]
@sccolbert Just for clarification the "command palette" contains the commands that are currently available based on which panel(s) are on the right hand side.

Forgot about the fuzzy completion feature. Perhaps the entry box should be a bit more prominent. Feel free to close or leave open since this was more a heads up issue than anything else. 🏄

**Comment by ellisonbg** [comment]
Also, I thought that eventually we were going to have a streamlines "New"
dialog and a single command for that - that put the kernel choice under the
dialog. That is part of the problem we have right now - we haven't
implemented that dialog so we have to have (N kernels)*(M document types)
new commands. We might want a command for each document type:

* New Notebook
* New Console
* New Text Editor

And then put the kernel selection under those dialogs?

But also, yes, the command palette will always show everything and be
optimized for the fuzzy searching, with the menu having a carefully curated
set of actions.

On Thu, Jun 23, 2016 at 11:25 AM, Carol Willing <notifications@github.com>
wrote:

> @sccolbert <https://github.com/sccolbert> Just for clarification the
> "command palette" contains the commands that are currently available based
> on which panel(s) are on the right hand side.
>
> Forgot about the fuzzy completion feature. Perhaps the entry box should be
> a bit more prominent. Feel free to close or leave open since this was more
> a heads up issue than anything else. 🏄
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyterlab/issues/152#issuecomment-228188920>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0DAPqZFel4_XdSSOZ62A1fVCKrKZks5qOvnigaJpZM4I9JrG>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by willingc** [comment]
cc/ @jupyter/students

**Comment by spoorthyv** [comment]
I felt like it would make much more sense to eventually implement a system where you get a set  of commands based on what panels are open on the right side. This could either be added alongside the existing command palette or replace it. I made a mockup for this idea. 

![jupyterlab-command](https://cloud.githubusercontent.com/assets/12418068/16350686/201fda68-3a15-11e6-9f4d-b481bd342051.png)

**Comment by ellisonbg** [comment]
Closing in favor of new issues to track the broader design considerations of the launcher and friends.
