### ISSUE TITLE
Less chrome

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyterlab#153]
Assuming that #147 gets merged, the dockarea will look like. It is already de-cluttered compared to the current version.

<img width="881" alt="chrome" src="https://cloud.githubusercontent.com/assets/2397974/16317300/66f1917e-3958-11e6-8a95-76abfaee9fde.png">

Still, the top-right square in every tab area is not very useful. We could remove it and get something visually less cluttered like this:

<img width="881" alt="less-chrome" src="https://cloud.githubusercontent.com/assets/2397974/16317319/860a6a86-3958-11e6-87b9-6757be75484f.png">

**Comment by sccolbert** [comment]
There will eventually be extra controls in that area. To maximize, restore, and undock a panel. Plus the potential for a settings button or other user-defined things.

**Comment by SylvainCorlay** [comment]
So the `+` button can totally be with the tabs themselves.

There are other options for positioning buttons:

<img width="280" alt="screen shot 2016-06-23 at 4 15 42 pm" src="https://cloud.githubusercontent.com/assets/2397974/16318574/c35db92e-395d-11e6-8bde-aea7bc599230.png">

(depending on whether you want it to be applicable to a tab area or a single tab, we may have different preferences)

**Comment by SylvainCorlay** [comment]
In the current state of things, this area is not used, and could be styled differently if we decide to put something there...

**Comment by sccolbert** [comment]
The `X` button is already part of tab, so I'm not exactly sure what you are tying to show with the screenshot of the Chrome browser tab. There will be at least 2 additional buttons: "maximize/restore" and "undock". That would make 3 total buttons in each tab at minimum, which I think would be excessive.

ping @cameronoelsen @ellisonbg

**Comment by SylvainCorlay** [comment]
ok, that was not clear: what I meant is that if the maximize button applies to the entire tab area, it can be at the top left corner, but if you have actions that apply to individual tabs, it is different.

**Comment by sccolbert** [comment]
Ah, I see. Extra buttons in top-left instead of top-right. Got it. 

Still needs discussion with the design team :)

**Comment by SylvainCorlay** [comment]
Yeah, although it is probably good to remove any line or visual clutter that is not actively used until we use it...

**Comment by bliker** [comment]
I would also take a pixel or two off the padding.

**Comment by ellisonbg** [comment]
We will soon need to start using the area to the right of the tab. The
biggest initial target is to have a "+" button that opens a new document in
that panel. Also, "not using" is different than "not seeing". By that, I
mean that sometimes, appropriately styled whitespace is an important part
of design - omitting the styling of that rectangle is a bit too sparse for
my tastes. Do we have examples of other tabbed designs that have that type
of styling?

On Thu, Jun 23, 2016 at 12:01 PM, Samuel Vasko <notifications@github.com>
wrote:

> I would also take a pixel or two off the padding.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyterlab/issues/153#issuecomment-228198407>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0Gwu7u67nZ4wvu00awmQtisYZZ5Aks5qOwJJgaJpZM4I9KkZ>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by SylvainCorlay** [comment]
> Do we have examples of other tabbed designs that have that type of styling?

Most of the ones I found in MS products are like this (with less or no margin between tab areas though), there is no extra line for delimiting tabs.


Ex: ms blend:
![tbs](https://cloud.githubusercontent.com/assets/2397974/16323940/12fd3d8c-397d-11e6-9621-bea322644712.png)

No need for additional lines even if you want to have buttons there.

**Comment by SylvainCorlay** [comment]
> We will soon need to start using the area to the right of the tab. The
biggest initial target is to have a "+" button that opens a new document in
that panel.

As showed above, no need to draw lines to use this area.

>  omitting the styling of that rectangle is a bit too sparse for my tastes.

It means that we have available space and increase work space for the notebook, the editor etc..

**Comment by SylvainCorlay** [comment]
Screenshot from PR on ubuntu + chrome
![screenshot](https://cloud.githubusercontent.com/assets/2397974/16398847/a229a38a-3c9b-11e6-8bf9-fa1888c6ced4.png)

**Comment by cameronoelsen** [comment]
I definitely feel that we should keep the rectangle on the right just for styling purposes. Without it there, the interface feels like it is missing something in my opinion.

**Comment by SylvainCorlay** [comment]
It shows something that was not apparent before, which is that we have a lot of available space which we were filling with lines that don't have practical meaning.

**Comment by sccolbert** [comment]
This is an early mockup of the UI, which shows potential buttons placed in that area:

![Mockup](https://cloud.githubusercontent.com/assets/6437976/9770666/47bed546-56e6-11e5-86ca-2383abe99760.png)

**Comment by jasongrout** [comment]
I really like how Sylvain's proposal declutters the interface (less lines and visual noise). One negative is that it isn't clear then the difference between the splitter and the tab header area, except for a cursor change. But I think it's worth trying Sylvain's proposal out.

And this is something that could tried out easier if/when we have a loadable theme system. But for now, +1 on getting rid of the box in the tab header to declutter the interface.

**Comment by SylvainCorlay** [comment]
Here is a version of Chris' mock up without the lines.

![test](https://cloud.githubusercontent.com/assets/2397974/16423252/4f4476de-3d29-11e6-9602-d9830d792c5f.png)

**Comment by sccolbert** [comment]
Sorry, i should have been more specific. That was Cameron's original mock up from here:
https://github.com/jupyter/design/issues/18

**Comment by SylvainCorlay** [comment]
ok updated the comment :)

**Comment by SylvainCorlay** [comment]
IMO, it looks especially nicer on the mockup when there are icons there.

**Comment by jasongrout** [comment]
(from appear.in conversation with Brian) - the consensus now at Cal Poly is that Sylvain's proposal is a good one.
