### ISSUE TITLE
Document How to Add Content

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyterlab#163]
As an example: add `fullpage.js`, a `jQuery` plugin, to the `About` plugin.

- Go to npm: search for [fullpage.js](https://www.npmjs.com/package/fullpage.js) (success!).
- Go to `jupyterlab` top level source directory: `npm install --save fullpage.js`.  This adds the file to the `dependencies` in `package.json`.
- Go to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) to get the third party declaration file: search for [fullpage.js](https://github.com/DefinitelyTyped/DefinitelyTyped/search?utf8=%E2%9C%93&q=fullpage.js) (more success!).
- If there are no typings, we must create our own.  An example typings file that exports functions is [ansi_up](https://github.com/jupyter/jupyterlab/blob/master/typings/ansi_up/ansi_up.d.ts).  An example with a class is [xterm](https://github.com/jupyter/jupyterlab/blob/master/typings/xterm/xterm.d.ts).
- Copy the contents of [fullpage.js.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1bd46872a2cd1c1ed7a0af24de2b657bd074ac7a/fullpage.js/fullpage.js.d.ts) to `typings/fullpage.js/fullpage.js.d.ts`.
- Add a reference to the new library in `src/typings.d.ts`.
- We already have `jQuery` available in the application, in our `package.json` and in `typings/jquery`.
- Add the following to `jupyterlab/src/about/plugin.ts`:

 ````typescript
import 'fullpage.js';   // load the plugin.
import 'fullpage.js/jquery.fullPage.css';  // load the style (the file location in `node_modules/fullpage.js`).

let options = {...};  // define options here.
${'#myCoolId'}.fullpage(options);  // jQuery is available in Jupyterlab as a global variable `$` per the webpack config.
```

- Install the dependency in `jupyterlab/jupyterlab` as well:  `npm install --save fullpage.js`
- Run `npm run build` from `jupyterlab/jupyterlab`
- Run `jupyter lab` and verify changes.

**Comment by blink1073** [comment]
Another example:  how to add a menu to a side bar item.

Use a phosphor panel.
Add a menu to the panel.
Add the content to the panel.

**Comment by willingc** [comment]
Nice!

**Comment by eskirk** [comment]
We are trying to do this right now but `options` in `jQuery.fullpage(options)` is undefined and the `import jQuery;` line is also yelling at us :/

**Comment by blink1073** [comment]
Can you paste the `import` error?  Right, you need to provide those options to `fullpage()`.

**Comment by eskirk** [comment]
`src/about/plugin.ts(4,14): error TS1005: '=' expected.`

Both of our teams trying to import jQuery are running into that error.

**Comment by blink1073** [comment]
Ah, sorry, try it with quotes (updated above).

**Comment by eskirk** [comment]
That fixed that problem, but now it is telling us fullpage does not exist on type 'jQueryStatic'. 

Also, we run `npm install --save fullpage.js` twice, once in `Jupyterlab/jupyterlab` and once in `Jupyterlab/jupyterlab/src`, correct?

**Comment by blink1073** [comment]
Can you post your code as is in a WIP PR?  Yes, you install it in both places.
