### ISSUE TITLE
Desktop App

### ISSUE THREAD

**Issue by bliker** [jupyter/jupyterlab#166]
I have contemplating about the endgame of this project. I love the idea and the execution, so far seems surprisingly polished and I hope it will bring more people to jupyter. But there are two things that I find most annoying and daunting when using and explaining it.

- How to install it
- How to start it 

Personally I also hate the waste of vertical space.
What I propose is embracing the great work that has been put into frameworks for javascript desktop apps recently and create something for this. What I imagine is following.

1. Implement a wrapper around jupyterlab that is able to offload some of the functionality onto OS (menu, floating windows) in [electron](http://electron.atom.io) of similar.
2. Add desktop specific features to that app (starting and stopping server, opening notebook files form file browser) and possibility to connect to remote server.
3. Possibly package the app so no other installation is necessary 

I do not want a codebase split, only a different way to access the same server using a UI with some extra features added. I am happy to work on this project myself, if there is an interest.

**Comment by SylvainCorlay** [comment]
@bliker would an "app" that simply launches chrome in "app" mode do the job?

To see the result:
 - launch jupyter lab: `jupyter lab --no-browser`
 - launch chrome in app mode: `google-chrome --app=http://localhost:8888`

**Comment by bliker** [comment]
It would work, but :)
- There would still be a useless menu on top on Mac. 
- No filesystem access (file association)
- No extra features like [frameless windows](http://electron.atom.io/docs/api/frameless-window/) - [this has no controls but you know what I mean](https://i.imgur.com/fdPFRUx.png)

I will try to make a demo next

**Comment by blink1073** [comment]
Hi @bliker, the pieces of JupyterLab are intended to be used as standalone components where possible, see for example `examples/console`.  They can be combined using a `phosphor` application as we do here, or by manually putting the instances together.  We target the browser because there are a whole class of users that require a browser environment, but an electron app based on these components is certainly feasible.  We welcome any feedback where the architecture or an individual component could be made more amenable to other use cases.

**Comment by jasongrout** [comment]
> I am happy to work on this project myself, if there is an interest.

I think there probably would be interest (the Jupyter mailing list would be a great place to ask!). As @blink1073 said, we hope people can easily use the components in apps other than the browser-based JupyterLab app, so we're happy to work with you on things you need to make this work.

FYI, several people are also working on an electron-based app called nteract, though I don't think it reuses much or any of the JupyterLab work.

I'm going to close this issue in favor of opening specific issues about things we can do to help you in your efforts. Thanks for looking into this! I'm excited to see where it goes!
