### ISSUE TITLE
Moving from cell to cell is sluggish when using >10 cells 

### ISSUE THREAD

**Issue by ebeisaac** [jupyter/jupyterlab#168]
General small Notebooks are fine but when using notebooks than spans multiple cells, the movement between cells delay from half a second to 1.5 seconds. This especially happens when the number of pages exceed 10 on A4 print. This problem does not exist in Jupyter Notebook when executed on the same machine.

Machine: Ubuntu 14.04;  Intel Core i7-4790 CPU; Intel Haswell GPU

**Comment by blink1073** [comment]
Hi @ebeisaac, thank you for the report.  This is a known problem because right now we are calling `refresh()` on all of the CodeMirror instances (every cell) when the index changes.  We are looking at a workaround in https://github.com/jupyter/jupyterlab/issues/25.

**Comment by ebeisaac** [comment]
Thank you for the clarification, @blink1073.
