### ISSUE TITLE
When shoudl I use Jupyterlab?

### ISSUE THREAD

**Issue by cqcn1991** [jupyter/jupyterlab#17]
Jupyterlab looks very cool (and I'm thinking about something very similiar to it), but I'm wondering when should I use it? Is there anyone using it for your project? and can I see an example?

If I run it in local machine, I dont' understand why I need a tab in browser for console?

**Comment by jasongrout** [comment]
It's a *very* pre-alpha level project right now, not at all suitable for general usage right now. This is just a *very* early preview that still has lots of development left to do.

**Comment by jasongrout** [comment]
There will be a big announcement when it is ready for general usage. That likely won't be for at least a few months, and likely longer.
