### ISSUE TITLE
Command palette: once a command was run, empty the content of the TextArea

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyterlab#175]
Once a command has been selected and run, we should probably empty the text area of the command palette.

**Comment by afshin** [comment]
We've had some conversations about this behavior and which way it should go. As an example, Sublime Text's command palette leaves the text area populated in between invocations of commands. I prefer that behavior, personally, but others may have arguments one way or the other.

**Comment by sccolbert** [comment]
To be clear, once a command is run, the text in the text area is selected, so if focus is not lost on execution of the command, continuing to type will clear the input and insert the new characters.

**Comment by SylvainCorlay** [comment]
> To be clear, once a command is run, the text in the text area is selected, so if focus is not lost on execution of the command, continuing to type will clear the input and insert the new characters.

That is right.

**Comment by SylvainCorlay** [comment]
Feel free to close.

**Comment by afshin** [comment]
Cheers.
