### ISSUE TITLE
Dockarea + Notebook

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyterlab#176]
When closing a notebook tab that is not the current tab, the `close without saving` popup is invisible because the tab content is invisible - and the tab is not closed right away.

The triggering of this popup should probably change the selected tab temporarily.

**Comment by sccolbert** [comment]
Phosphor specifically does not select the tab when clicking the close icon, which I think is the correct default behavior. It shouldn't be too difficult to ensure a widget is the selected tab from its `onCloseRequest` handler.

**Comment by SylvainCorlay** [comment]
I am not *sure* that I was clear, it is only in the case of a popup such " Close without saving" that we need to select the tab.

**Comment by ellisonbg** [comment]
This is fixed in master now that all dialog are on the body...
