### ISSUE TITLE
compatibility problem with ipywidgets 5.1.5 ?

### ISSUE THREAD

**Issue by stonebig** [jupyter/jupyterlab#18]
this works under classic ipython4.2:
````
%matplotlib inline
# Pandas interactive
import pandas as pd
import numpy as np
import seaborn as sns

# create a df with random datas
np.random.seed(24)
df = pd.DataFrame({'A': np.linspace(1, 10, 10)})
df = pd.concat([df, pd.DataFrame(np.random.randn(10, 4), columns=list('BCDE'))],
               axis=1)
df.iloc[0, 2] = np.nan

# interactive
from ipywidgets import widgets
@widgets.interact
def f(h_neg=(0, 359, 1), h_pos=(0, 359), s=(0., 99.9), l=(0., 99.9)):
    return (df
             .style
             .background_gradient(
                cmap=sns.palettes.diverging_palette(
                     h_neg=h_neg, h_pos=h_pos, s=s, l=l, as_cmap=True)
             ).highlight_null()
````

under jupyterlab (and chrome) I get a :
![jupyterlab03](https://cloud.githubusercontent.com/assets/4312421/15883524/1877a0b2-2d49-11e6-92ba-1d008f304840.PNG)

**Comment by jasongrout** [comment]
Yes, @interact doesn't work right now - we're actively working on a fix. Also, you'll need the master dev branch of widgets installed to have widgets working (what will be widgets 6.x) -- we should note that in the readme and the initial startup page.

- [ ] Release pre-release version of ipywidgets 6.x
- [ ] Make this pre-release a requirement of jupyterlab (maybe an optional prereq? That way people can still experiment with jupyterlab without messing up their ipywidgets installation if they just don't use ipywidgets)
- [ ] Note in the readme and initial about page that ipywidgets 6.x+ is needed for widgets to work.

**Comment by SylvainCorlay** [comment]
@stonebig we are actively working on the 6.x branch which should work with both jupyterlab and the current notebook eventually.

**Comment by jasongrout** [comment]
Subsumed in the working items in #23. Thanks for the report!
