### ISSUE TITLE
Licensing of files

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyterlab#19]
@sccolbert, @blink1073, @afshin - would it be all right with you to relicense the two files that have a PhosphorJS copyright/license with the standard Jupyter license statement (same BSD license, but copyright Jupyter dev team)? The two files in question are:

https://github.com/jupyter/jupyterlab/blob/ba0a1b7e14509afaf59afb1a9afa0ba1aa9a01b3/src/codemirror/widget.ts

https://github.com/jupyter/jupyterlab/blob/f2a4b8d99218aef83f110e67e348ed21d9196cee/src/notebook/common/json.ts

Having a single common license for all the files in JupyterLab will make adoption and messaging simpler, and follows the project policy more closely (https://github.com/jupyter/governance/blob/master/projectlicense.md#our-copyright-policy).

**Comment by jasongrout** [comment]
On the other hand, especially for json.ts, can we just import that from phosphor and use it?

**Comment by sccolbert** [comment]
I can do a `0.x` release of phosphor now on npm if you want to use `json.ts` immediately. For the code mirror file, yeah you can have it/relicense/whatever.

**Comment by blink1073** [comment]
I'd say let's relicense both in place and I'll remove `json.ts` when we switch the codebase over.
