### ISSUE TITLE
Remove Sliver at the Top of the Tab

### ISSUE THREAD

**Issue by charnpreetsingh185** [jupyter/jupyterlab#190]
There is a line under each tab in Jupyter Lab. It's somewhat hard to see...
<img width="928" alt="screen shot 2016-06-29 at 3 13 31 pm" src="https://cloud.githubusercontent.com/assets/16314651/16470631/3df54870-3e0c-11e6-8e65-a28e3f4d9f81.png">

**Comment by ellisonbg** [comment]
Talked with the designers here at Cal Poly and all think we should remove the sliver of whitespace above the actual widget in each tab.

* Individual widgets can add that space or more if needed.
* More difficult to remove on individual basis.
* Simplifies the design and works well with @SylvainCorlay proposed changes

**Comment by sccolbert** [comment]
That little line looks like it *might* be due to a drop shadow on the tab.

@ellisonbg which whitespace are you talking about?

**Comment by eskirk** [comment]
I'm all for this change, except for the fact that it will make some of the designs look a little bit too cluttered up towards the top. 
![screen shot 2016-06-30 at 9 23 53 am](https://cloud.githubusercontent.com/assets/7052378/16495870/1928509e-3ea4-11e6-8526-15ad803d25be.png)
![screen shot 2016-06-30 at 9 24 01 am](https://cloud.githubusercontent.com/assets/7052378/16495871/19299602-3ea4-11e6-8946-a559d4bdfe38.png)
In the Notebook, the `Code` dropdown would be flush up against the tab bar and that would look 💀 

Maybe there needs to be some sort of padding up towards the top, but completely removing the sliver might be a little excessive.

**Comment by ellisonbg** [comment]
This was done in master...
