### ISSUE TITLE
Updated JupyterLab about page

### ISSUE THREAD

**Issue by eskirk** [jupyter/jupyterlab#191]
We (@rnetro @roshancvp @matt-bowers ) updated the about page to using `fullPage.js` and want some feedback. This is currently just done using an iFrame pointing to a website hosted using gh-pages, but once I get around to installing the required js and providing the HTML it will be fully embedded within JupyterLab. Let us know what you think!

![screen shot 2016-06-29 at 4 06 16 pm](https://cloud.githubusercontent.com/assets/7052378/16471705/4ded5ac2-3e13-11e6-9669-f2170177f1f3.png)
![screen shot 2016-06-29 at 4 06 26 pm](https://cloud.githubusercontent.com/assets/7052378/16471708/522a0dd8-3e13-11e6-8bec-52f695f712a9.png)
![screen shot 2016-06-29 at 4 06 37 pm](https://cloud.githubusercontent.com/assets/7052378/16471717/55233dfc-3e13-11e6-8341-74a41126c117.png)
![screen shot 2016-06-29 at 4 07 04 pm](https://cloud.githubusercontent.com/assets/7052378/16471718/58fda5e8-3e13-11e6-9a58-ef02e3be63ac.png)
![screen shot 2016-06-29 at 4 07 12 pm](https://cloud.githubusercontent.com/assets/7052378/16471719/5c2f983e-3e13-11e6-8203-c1081c55148a.png)

**Comment by matt-bowers** [comment]
In addition, these screenshots are currently acting as placeholders to show where the actual animated images showing each command will be located.

**Comment by blink1073** [comment]
Great work so far folks!

**Comment by jasongrout** [comment]
This is done now, right?

**Comment by eskirk** [comment]
@jasongrout yessir
