### ISSUE TITLE
Drag and Drop Functionality Broken in FileBrowser

### ISSUE THREAD

**Issue by charnpreetsingh185** [jupyter/jupyterlab#192]
Also, selected files are staying orange even after hovering away from them.
![screen shot 2016-06-29 at 4 40 15 pm](https://cloud.githubusercontent.com/assets/16314651/16472360/515c90d8-3e18-11e6-8f8b-96c2bd085fcd.png)

**Comment by blink1073** [comment]
This was broken by #181.
