### ISSUE TITLE
tsc dev dependency missing

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyterlab#20]
You guys probably have it globally installed.

**Comment by jasongrout** [comment]
typescript is a dev dependency, and that provides tsc. Can you post your error?

**Comment by SylvainCorlay** [comment]
Could not reproduce.

**Comment by SylvainCorlay** [comment]
Reopening. This just occurred on my mac:

```
    > jupyterlab@0.0.7 prepublish /Users/scorlay/jupyter/jupyter/jupyterlab
    > npm run build
    
    
    > jupyterlab@0.0.7 build /Users/scorlay/jupyter/jupyter/jupyterlab
    > npm run build:src
    
    
    > jupyterlab@0.0.7 build:src /Users/scorlay/jupyter/jupyter/jupyterlab
    > tsc --project src && node scripts/copyfiles.js
    
    sh: tsc: command not found
```

**Comment by blink1073** [comment]
@SylvainCorlay, can you check for `node_modules/.bin/tsc`?

**Comment by SylvainCorlay** [comment]
A regular npm install succeeds, and `node_modules/.bin/tsc` is created as expected. What does not work is the pip installation, which is supposed to trigger npm.

**Comment by blink1073** [comment]
Ah, so `tsc` was just the first node command it tried, a red herring.

**Comment by jasongrout** [comment]
Is it reproducible? if you manually do `python setup.py jsdeps`, does the npm installation happen?

**Comment by jasongrout** [comment]
I reproduced this:

```
git clone git@github.com:jupyter/jupyterlab.git
conda create -n lab7 python=3 notebook
source activate lab7
pip install -e jupyterlab
```
