### ISSUE TITLE
Add Advanced File Dialogs

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyterlab#208]
Add  "create new" and "open with" dialogs.

Dialogs are implemented in https://github.com/jupyter/jupyterlab/blob/master/src/filebrowser/dialogs.ts, but need to be finished.

**Comment by ellisonbg** [comment]
I am going to be opening a new set of issues about the new file approach. Also, looks like open with is done. Closing this one...

**Comment by jasongrout** [comment]
@ellisonbg - Can you make sure to link the new issues to here? Thanks!
