### ISSUE TITLE
The launcher should be main area when nothing is open

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyterlab#210]
Migrated from https://github.com/jupyter-attic/jupyter-js-plugins/issues/167

**Comment by willingc** [comment]
This would be helpful for a new(er) user. 

For a new user, it would be nice to have the existing Launcher come up first (so I would know immediately how to create a new "whatever"). Much like a browser tab, I would leave the Launcher on the left side and use it as needed. Having the title of the tab be Launcher would also help.

cc @afshin @blink1073

**Comment by ellisonbg** [comment]
We are going to close this in favor of some new issues working on the design of the launcher and activity starting logic.

**Comment by ellisonbg** [comment]
See #848
