### ISSUE TITLE
Add ability to close all widgets in the main area

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyterlab#212]
Migrated from https://github.com/jupyter-attic/jupyter-js-plugins/issues/114

**Comment by ellisonbg** [comment]
We should probably do this by adding a new command - probably rare enough that we don't need a keyboard shortcut.

**Comment by ellisonbg** [comment]
@blink1073 I am going to have @charnpreetsingh185 create a new method of `ApplicationShell` that will use its private `Tracker` to close all widgets in the main area. Then we would add a command somewhere that simply calls that method. But which plugin should add that command. Right now we don't have a plugin that has "global" commands.

**Comment by blink1073** [comment]
The "main" plugin seems like a good spot.

**Comment by blink1073** [comment]
Which could actually be sensibly merged with the application folder.

**Comment by ellisonbg** [comment]
We saw that but I wasn't sure that that main plugin could be used. Can we add a `requires` section to grab the command palette and add it as usual?

**Comment by blink1073** [comment]
Ayup, there was nothing special about "main".

**Comment by ellisonbg** [comment]
So I am guessing that the main plugin isn't quite a real plugin - it is the root plugin that should only depend on the app?

**Comment by blink1073** [comment]
It is a real plugin on that there's nothing special about it, just like any other plugin.  It just happens to do stuff directly on the window.
