### ISSUE TITLE
Composing cdn urls and distribution patterns

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyterlab#214]
1) As we are publishing umd modules with the npm packages for jupyter-js-widgets and jupyter-js-services, we need to decide on a pattern for the main entry point of the distributed package.

I propose that we go for `dist/index.js` which would give a URL of the form 

`https://npmcdn.com/jupyter-js-services/dist/index.js`

in the case of npmcdn, which can be achieved by building the webpack package at the prepublish stage.

This URL redirects to the latest version of jupyter-js-services published on npm. More generally, one may add a SEMVER requirement to the URL such as `https://npmcdn.com/jupyter-js-services@^0.11/dist/index.js`.

The support for semver in the npmcdn requests is super neat IMO and we make use of it in jupyter-js-widget to get the latest compatible version of the inline embedder...

2) There are some ongoing discussion on supporting other cdns than npmcdn. The problem is that I don't know any other cdn that supports semver which is a killer feature. The pydata cdn URL include the version number as part of the package name. A good way to do so would be to provide a pluggable way to compute cdn URLs. At the moment, cdn url computation is done in jupyter-js-widgets, but this could moved upstream in jupyterlab.

3) Open questions. The npmcdn `jupyter-js-widgets` bundle comprises `jupyter-js-services`, which will now also be on npmcdn. I imagine that we would want to make it an external dep of the bundle and also fetch it via npmcdn...

@blink1073 @ellisonbg @jasongrout

**Comment by blink1073** [comment]
I am `+1` for 1 and 3, cf https://github.com/jupyter/jupyter-js-services/pull/162.  AFAIK we'd have to distribute a separate bundle if we wanted it to be available on the pydata cdn URL, since the public path is embedded in the bundle.

**Comment by blink1073** [comment]
We should also either start using `jupyter-js-utils` in `jupyter-js-widgets` or consider absorbing it into `jupyter-js-services`.

**Comment by blink1073** [comment]
Actually, we do use it directly in `jupyterlab`.  It should have its own release and be referenced from the `jupyter-js-services` and `jupyterlab` bundles.

**Comment by blink1073** [comment]
cf https://github.com/jupyter/jupyter-js-utils/pull/46

I'm still not sure how to make one bundle depend on the public path of another, I'll look at it this week.

**Comment by SylvainCorlay** [comment]
> I'm still not sure how to make one bundle depend on the public path of another, I'll look at it this week.

Yes, there is another issue is that the public path is cdn-dependent.

**Comment by jasongrout** [comment]
cf. #224.

**Comment by jasongrout** [comment]
What is the status of this?

**Comment by blink1073** [comment]
Closing this in favor of #728.  JupyterLab itself does not have a single "entry" point, and we are planning to use local dependencies as part of a local build.
