### ISSUE TITLE
FAQ page in Help plugin

### ISSUE THREAD

**Issue by faricacarroll** [jupyter/jupyterlab#219]
We ( @spoorthyv @charnpreetsingh185 @katiewhite360 ) made an FAQ page to be added inside the Help section. We used jquery alongside static html and css to create this page. We're still working on embedding it within JupyterLab. 

We came up with a couple of questions on our own, but were wondering if you guys had any suggestions for frequently asked questions among Jupyter users. Let us know what you think! 

![ezgif com-crop](https://cloud.githubusercontent.com/assets/19479586/16533805/34f49426-3f90-11e6-9feb-d6d871f899ee.gif)

Our current content: 
# Frequently Asked Questions

### What is Jupyter Notebook?

Central to the project is the Jupyter Notebook, a web­based platform that allows users to
combine live code, equations, narrative text, visualizations, interactive dashboards and other
media. Together these building blocks make science and data reproducible across over 40
programming languages and combine to form what we call a computational narrative. 

### What is JupyterLab?

JupyterLab allows users to arrange multiple jupyter notebooks, text editors, terminals, output areas, etc. on a single page with multiple panels and tabs into one application. The codebase and UI of JupyterLab is based on a flexible plugin system that makes it easy to extend with new components. 

### How do I add more kernels/languages to JupyterLab?

To add more languages to the JupyterLab you must install a new kernel. Installing a kernel
is usually fairly simple and can be done with a couple terminal commands. For further instructions, click this [link](https://ipython.readthedocs.io/en/latest/install/kernel_install.html).

**Comment by jasongrout** [comment]
What is the status of this?

**Comment by jasongrout** [comment]
See also #325

**Comment by spoorthyv** [comment]
This can be closed. The faq page is done for now (other than a couple very small problems).

**Comment by jasongrout** [comment]
Thanks!
