### ISSUE TITLE
Opening markdown files in preview mode

### ISSUE THREAD

**Issue by bliker** [jupyter/jupyterlab#226]
There should be a way to open markdown not only in text editor but as readable documents.

**Comment by blink1073** [comment]
Hi @bliker, yep, this should take the form of a `WidgetFactory` for markdown files, and will be available in our "Open With..." dialog/context menu (when we build it).
http://jupyterlab-tutorial.readthedocs.io/en/latest/documents.html#widget-factories

**Comment by fperez** [comment]
It's not perfect yet (I'll be opening some issues on this shortly), but it does work now in master... I'd close this for now as the basic feature is implemented, and we can focus on remaining refinements. Thoughs, @blink1073?

**Comment by blink1073** [comment]
Sounds good.
