### ISSUE TITLE
"Cancel" in console closing doesn't work

### ISSUE THREAD

**Issue by fperez** [jupyter/jupyterlab#233]
If I click on the close button for the console and then select "Cancel" in the resulting confirmation dialog, it still kills the console.

**Comment by willingc** [comment]
This also applies to notebook closing and selecting "Cancel".

**Comment by blink1073** [comment]
@willingc, the notebook is behaving like I'd expect, is it not what you expected?

![notebook_cancel](https://cloud.githubusercontent.com/assets/2096628/16659814/59932b3a-4431-11e6-88cd-b408c12afb88.gif)

**Comment by fperez** [comment]
Ah, the bug is that if the notebook *has been saved*, then Cancel is ignored:

![untitled](https://cloud.githubusercontent.com/assets/57394/16665269/cdb602d4-4437-11e6-8c1e-aff9a34d9840.gif)

Indeed if it hasn't been saved, Cancel works as expected. But Cancel should always cancel closing, even if the notebook has been saved.  It seems like what is being canceled is the kernel shutdown, but the notebook tab itself is closed unconditionally.

**Comment by blink1073** [comment]
I think we should remove the "shut down kernel" dialog once we have the "running" tab.

**Comment by fperez** [comment]
Though we still need a single-place to do "Close and Halt" like the current notebook offers. That action is common/useful enough that the process for users shouldn't be "Close the notebook first, then go find its kernel in the "running" area and shut it down manually".  That would be pretty confusing UX for most people.

I know at least I use "Close and Halt" a lot...

**Comment by blink1073** [comment]
That seems like a good candidate for a command and a menu item, but not the default action when closing the tab.

**Comment by fperez** [comment]
On Thu, Jul 7, 2016 at 11:48 AM, Steven Silvester <notifications@github.com>
wrote:

> That seems like a good candidate for a command and a menu item, but not
> the default action when closing the tab.
>

Definitely a menu item, if nothing else to ease the transition for existing
users... I think we'll need to try to provide a menu experience that at
least for key actions is very similar to the current one if we want users
to have a good transition process.

Right now their experience is: closing the browser tab simply closes the
document, for a full shutdown they can either use "Close and Halt"
(convenient, one-step) or close the document and later manually clean up
from the "Running" tab.

For simplicity, I suggest we tend to copy, within reason, our UX flow from
the existing notebook.   While I'm sure we've made decisions that could be
made better, I'm a little worried that if we try to make each and every
such decision anew right now, the process of catching up will drag too
much, and that hurts us all.

If instead we simply say, for UX decisions, "do what we did", we can move
faster and with less discussion. In the future we'll have plenty of time to
refine the UX atop our new more modular UI codebase.

At least that's my take on how we should approach this, both for our
fluidity of development and for the user's sake as we ask them to
transition.

**Comment by blink1073** [comment]
Sounds good.

**Comment by jasongrout** [comment]
I think the above discussion decided that things work as expected now, but there should be an additional "Close and Halt" menu item and command for notebooks, mimicking the current notebook menu item - see #742.

**Comment by jasongrout** [comment]
(Please reopen, @fperez, if I'm mistaken)

**Comment by fperez** [comment]
This sounds good, I'll play with it and we can revisit if the experience feels awkward. Thanks!
