### ISSUE TITLE
Provide some visual feedback on what tab/object is currently focused

### ISSUE THREAD

**Issue by fperez** [jupyter/jupyterlab#234]
There should be a way for the user to know which main element is currently focused, right now if you've moved out or even blinked away for a few minutes, you basically have to keep on clicking again to make sure your typing will go to the right place.

All OS window managers provide visual highlights for the active window (more or less prominent, more or less configurable, but they all give *something*). I think this is pretty critical, I'll tag it for 0.99 for now.

**Comment by fperez** [comment]
This is related to, though not identical to, #5.

**Comment by blink1073** [comment]
Chris and I are working on adding support for this in phosphor right now.

**Comment by blink1073** [comment]
Fixed by #636, the "current" (most recently focused) widget in the dock panel gets styled.
