### ISSUE TITLE
Mention kernel name in Console tab name

### ISSUE THREAD

**Issue by jorisvandenbossche** [jupyter/jupyterlab#237]
Currently, if you open multiple consoles, they are named 'Console-1', 'Console-2', etc. 
IMO, it would be useful if the tab names could include the kernel name, for the use case where you open multiple consoles with different kernels (eg different python versions). Similar to the kernel name as it is listed in the Commands ("New [kernel display name] Console").

**Comment by willingc** [comment]
Thanks for the suggestion 👍

**Comment by afshin** [comment]
Thanks for the suggestion! This has been implemented via https://github.com/jupyter/jupyterlab/pull/240

**Comment by afshin** [comment]
I just reopened the issue in case one of you felt like reviewing it. If you're satisfied with its being complete, feel free to close it.

**Comment by jorisvandenbossche** [comment]
Looks good, thanks a lot!

**Comment by willingc** [comment]
Thanks @afshin for the addition and @jorisvandenbossche for the helpful suggestion. 😎
