### ISSUE TITLE
Terminal Id Numbers Not Recycling

### ISSUE THREAD

**Issue by charnpreetsingh185** [jupyter/jupyterlab#257]
Closing a terminal and opening a new terminal results in a new terminal id being used. Currently the terminal ids only get reset after a jupyter lab server restart.

**Comment by blink1073** [comment]
These numbers come from the notebook server.

**Comment by ellisonbg** [comment]
But then that means that closing a terminal isn't actually closing the
terminal with the server properly

On Thu, Jul 7, 2016 at 5:57 PM, Steven Silvester <notifications@github.com>
wrote:

> These numbers come from the notebook server.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyterlab/issues/257#issuecomment-231249569>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0FWTFaG2UXGk3GrwWlvkPJQnFN6kks5qTaBrgaJpZM4JHook>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
Also, the way the current notebook works is that closing a terminal doesn't
quit the terminal - but if you open a new terminal later, you get that one
back again. This allows you leave and come back - very nice!

On Thu, Jul 7, 2016 at 7:04 PM, Brian Granger <ellisonbg@gmail.com> wrote:

> But then that means that closing a terminal isn't actually closing the
> terminal with the server properly
>
> On Thu, Jul 7, 2016 at 5:57 PM, Steven Silvester <notifications@github.com
> > wrote:
>
>> These numbers come from the notebook server.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/jupyter/jupyterlab/issues/257#issuecomment-231249569>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AABr0FWTFaG2UXGk3GrwWlvkPJQnFN6kks5qTaBrgaJpZM4JHook>
>> .
>>
>
>
>
> --
> Brian E. Granger
> Associate Professor of Physics and Data Science
> Cal Poly State University, San Luis Obispo
> @ellisonbg on Twitter and GitHub
> bgranger@calpoly.edu and ellisonbg@gmail.com
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by blink1073** [comment]
Noted, I'll update the logic tomorrow. 

Sent from phone.




On Thu, Jul 7, 2016 at 9:05 PM -0500, "Brian E. Granger" <notifications@github.com> wrote:










Also, the way the current notebook works is that closing a terminal doesn't

quit the terminal - but if you open a new terminal later, you get that one

back again. This allows you leave and come back - very nice!



On Thu, Jul 7, 2016 at 7:04 PM, Brian Granger <ellisonbg@gmail.com> wrote:



> But then that means that closing a terminal isn't actually closing the

> terminal with the server properly

>

> On Thu, Jul 7, 2016 at 5:57 PM, Steven Silvester <notifications@github.com

> > wrote:

>

>> These numbers come from the notebook server.

>>

>> —

>> You are receiving this because you are subscribed to this thread.

>> Reply to this email directly, view it on GitHub

>> <https://github.com/jupyter/jupyterlab/issues/257#issuecomment-231249569>,

>> or mute the thread

>> <https://github.com/notifications/unsubscribe/AABr0FWTFaG2UXGk3GrwWlvkPJQnFN6kks5qTaBrgaJpZM4JHook>

>> .

>>

>

>

>

> --

> Brian E. Granger

> Associate Professor of Physics and Data Science

> Cal Poly State University, San Luis Obispo

> @ellisonbg on Twitter and GitHub

> bgranger@calpoly.edu and ellisonbg@gmail.com

>







-- 

Brian E. Granger

Associate Professor of Physics and Data Science

Cal Poly State University, San Luis Obispo

@ellisonbg on Twitter and GitHub

bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
Great - basically think of "New Terminal" as meaning "Open an existing
terminal if it isn't open currently in the dock panel, or a brand new one
if all existing terminals are already open in the dock panel."

On Thu, Jul 7, 2016 at 7:33 PM, Steven Silvester <notifications@github.com>
wrote:

> Noted, I'll update the logic tomorrow.
>
> Sent from phone.
>
>
>
>
> On Thu, Jul 7, 2016 at 9:05 PM -0500, "Brian E. Granger" <
> notifications@github.com> wrote:
>
>
>
>
>
>
>
>
>
>
> Also, the way the current notebook works is that closing a terminal doesn't
>
> quit the terminal - but if you open a new terminal later, you get that one
>
> back again. This allows you leave and come back - very nice!
>
>
>
> On Thu, Jul 7, 2016 at 7:04 PM, Brian Granger <ellisonbg@gmail.com> wrote:
>
>
>
> > But then that means that closing a terminal isn't actually closing the
>
> > terminal with the server properly
>
> >
>
> > On Thu, Jul 7, 2016 at 5:57 PM, Steven Silvester <
> notifications@github.com
>
> > > wrote:
>
> >
>
> >> These numbers come from the notebook server.
>
> >>
>
> >> —
>
> >> You are receiving this because you are subscribed to this thread.
>
> >> Reply to this email directly, view it on GitHub
>
> >> <
> https://github.com/jupyter/jupyterlab/issues/257#issuecomment-231249569>,
>
> >> or mute the thread
>
> >> <
> https://github.com/notifications/unsubscribe/AABr0FWTFaG2UXGk3GrwWlvkPJQnFN6kks5qTaBrgaJpZM4JHook
> >
>
> >> .
>
> >>
>
> >
>
> >
>
> >
>
> > --
>
> > Brian E. Granger
>
> > Associate Professor of Physics and Data Science
>
> > Cal Poly State University, San Luis Obispo
>
> > @ellisonbg on Twitter and GitHub
>
> > bgranger@calpoly.edu and ellisonbg@gmail.com
>
> >
>
>
>
>
>
>
>
> --
>
> Brian E. Granger
>
> Associate Professor of Physics and Data Science
>
> Cal Poly State University, San Luis Obispo
>
> @ellisonbg on Twitter and GitHub
>
> bgranger@calpoly.edu and ellisonbg@gmail.com
>
>
>
>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
>
>
>
>
>
>
>
>
>
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyterlab/issues/257#issuecomment-231261228>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0ErXiDdQuShLLMFTAcQvwp0N_hFZks5qTbb_gaJpZM4JHook>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by sccolbert** [comment]
What if the user really wants a *new* terminal, instead of one which may be arbitrarily hosed with whatever env changes may have been made by something or another?

Would it make sense to have a UI for "running" terminals as well? Then let the user open either a new one, or a running one?

**Comment by ellisonbg** [comment]
We could distinguish those - the current "Running" page in the notebook
does list running terminals - maybe that is a cleaner way of handling it.
New gives a truly new one, and users can use the "Running" plugin to get an
existing one.

But, the terminal id number should be recycled though (reuse if there isn't
a terminal running with that number).

On Thu, Jul 7, 2016 at 7:59 PM, S. Chris Colbert <notifications@github.com>
wrote:

> What if the user really wants a *new* terminal, instead of one which may
> be arbitrarily hosed with whatever env changes may have been made by
> something or another?
>
> Would it make sense to have a UI for "running" terminals as well? Then let
> the user open either a new one, or a running one?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyterlab/issues/257#issuecomment-231264096>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0P3Xk8n9p3Pdn4ookbpHvU7gAM-9ks5qTb0PgaJpZM4JHook>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by blink1073** [comment]
Sounds reasonable. I plan to make a minimally styled running tab tomorrow
