### ISSUE TITLE
JupyterLab Console Tab title question. 

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#268]
Hey, me again. 

The Jupyter Console looks great ! I have a question though, the tab title says `Python 3 (1)`, I guess the `Python 3` part is the kernel name, but what's the `(1)`, it does not seem to reflect the execution number. 

I also found Myself, trying to hove the tab to get a tooltip explaining, I don't know if we have API to set an `alt` text on a tab, but I was just wondering if it would be a good idea.

**Comment by afshin** [comment]
The `(1)` just means it's the first console you have open. Right now, the version of phosphor we are using doesn't have tooltips, but the mono repo version will, so we can add a more helpful tooltip.

We can and should also decide, across the board, how we want to deal titles of various entities in tabs.

**Comment by Carreau** [comment]
> The (1) just means it's the first console you have open

Ah thanks, that seem unnatural to me because of the parenthesis, though I'm not sure how to make it better.

**Comment by jasongrout** [comment]
Putting the number in parens is a standard thing to do when you have conflicting filenames when downloading, at least for Chrome on OS X, and I've seen it elsewhere too.
