### ISSUE TITLE
User Test with 10yo

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#275]
# User test with Reed

About a week ago, I performed a simple user test with Reed, a computer/mobile literate 10 year old boy who plays Minecraft and has used Scratch. He has never used JupyterLab before. It wasn't recorded, but I did keep notes, which are provided here.

## Tasks and results

Task:

Open a new text file.

Result:

Quickly found the plus icon at the bottom of the file browser and was able to open a text file.

Task:

Type some text into the newly opened text file.

Result:

Was able to type text into the text file.

Task:

Save the text file.

Result:

Failed to save the text file. Knew about context menus and tried to pull up one over the text file, but it was for the browser. Hunted high and low for a button or something to save the file. Right clicked on the filename in the file browser to bring up its context menu, no save item to be found. Eventually I told him to use Command+S. When asked later about this, said "I was looking for a button that said Save."

Task:

Open a second text file, edit it and save.

Result:

Could do this, but now the Command+S shortcut seemed to not work (bug?!?).

Task:

Rename the file. Completed this action by right-clicking on the file name in the file browser and selecting the Rename item.

Task:

Open a new terminal.

Result:

Having found the plus icon at the bottom of the file browser previously, he tried to use that to open a temrinal but that wasn't an option listed. Hunted high and low, even opened up the Command Palette, but failed after scrolling through it a bit (lots to scroll through). After a long time playing, eventually found the New Terminal item at the bottom of the Command Palette. Once the terminal was opened, he typed `ifconfig` without any prompting.

Task:

Close the terminal.

Result:

Completed by clicking the cross in the Terminal's tab.

Task:

Open two terminals and put them side by side.

Result:

Could then open two terminals using the Command Palette. Knew that the tabs could probably dragged around, but couldn't figure out the right drop areas. This became easy once I told him to drag the tab down the dock area lower (he was previously moving around the tab bar only.)

Task:

Collapse the left side bar.

Result:

Quickly found that the width of the left side bar could be made larger, but was puzzled that it couldn't go smaller than some minimum. Looked for the long time and didn't discover that that clicking on the currently selected side-tab would minimize it all.

Task:

Resize the relative widths of two documents open in the dock panel.

Result:

Quickly found that the divider between the documents could be dragged for this purpose.

## Observations:

Even as a 10 year old, he knew to right click to get a context menu. Sometimes he was able to complete actions with this, but other times we either didn't have a context menu at all (browser context menu showed instead) or ours didn't have the desired action. Other times, there was a context menu with actions, but nothing to apply them to.

A number of times he tried to do action with the browser's own menu bar, but failed.

## Take homes

* Open documents should have a context menu that shows items for that document (save, rename) and kernel (start, stop, interrupt, etc.).
* The context menu of the file browser should have a save item.
* The context menu of the file browser should not show a context menu if nothing is selected.
* Visual design to make the left side-bar collapse/show action more discoverable (maybe an arrow?).
* The Terminal should appear in the dropdown brought up by clicking on the plus icon at the bottom of the file browser.
* Many of the discoverability problems would have been resolved by having a main menu bar with submenus for each plugin.

**Comment by jasongrout** [comment]
Can you make issues the items that are still relevant?

**Comment by ellisonbg** [comment]
Covered in other issues...
