### ISSUE TITLE
Multiple Cell selection improvement in edit mode.

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#276]
I guess @ellisonbg will be interested in this one. 

I'm playing around with JupyterLab again, the keyboard shortcut are really close to what the legacy notebook are, I thinks it's really great ! I have the strange feeling that some things are a bit different, but I can't pinpoint alway why exactly, so it's a good sign. 

Here is one a the few difference of behavior that I've found though. I don't know if we can classify it as "bug", as it make some sens. I just want to list it.

Shift Up/Down in edit mode move across cells while (de)selecting, here I press repetitively shift-down.

![shift-sel](https://cloud.githubusercontent.com/assets/335567/16709733/d7ba7d86-45cd-11e6-9037-d5584f518c61.gif)

See how it select/deselect in a way which is hard to undersand.
you can reproduce it by creating 6 cells:
  - click end of cell 6.
  - Shift-Up, Shift-Up
  - click start of cell 1
   - shift down, shift down 
   - Start recording
   - Shift down 6 times. 

This is because the head/tail of selection are in reverse order in cell 4 and 6. 

I suggest we don't allow to change focus cell with shift up/down if something is selected. 
The alternative is to deselect while unfocusing cell, but I'm unsure it's a good idea as some action might want to deal with a cell selection.

**Comment by ellisonbg** [comment]
Great catch! Some of these interactions are really subtle and take a bit of
digging to discover all the edge cases we need to handle. For stuff like
this, it is pretty important to match the existing notebook's interactions.

On Sat, Jul 9, 2016 at 2:16 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> I guess @ellisonbg <https://github.com/ellisonbg> will be interested in
> this one.
>
> I'm playing around with JupyterLab again, the keyboard shortcut are really
> close to what the legacy notebook are, I thinks it's really great ! I have
> the strange feeling that some things are a bit different, but I can't
> pinpoint alway why exactly, so it's a good sign.
>
> Here is one a the few difference of behavior that I've found though. I
> don't know if we can classify it as "bug", as it make some sens. I just
> want to list it.
>
> Shift Up/Down in edit mode move across cells while (de)selecting, here I
> press repetitively shift-down.
>
> [image: shift-sel]
> <https://cloud.githubusercontent.com/assets/335567/16709733/d7ba7d86-45cd-11e6-9037-d5584f518c61.gif>
>
> See how it select/deselect in a way which is hard to undersand.
> you can reproduce it by creating 6 cells:
>
>    - click end of cell 6.
>    - Shift-Up, Shift-Up
>    - click start of cell 1
>       - shift down, shift down
>       - Start recording
>       - Shift down 6 times.
>
> This is because the head/tail of selection are in reverse order in cell 4
> and 6.
>
> I suggest we don't allow to change focus cell with shift up/down if
> something is selected.
> The alternative is to deselect while unfocusing cell, but I'm unsure it's
> a good idea as some action might want to deal with a cell selection.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyterlab/issues/276>, or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0Nwifv3JAe2gLjJS6iwTMf1xetItks5qT_OigaJpZM4JIrrx>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jasongrout** [comment]
Confirmed. +1 to not allowing shift-arrow keys to go beyond the current cell when in edit mode.

**Comment by jasongrout** [comment]
The current notebook doesn't allow the cell to change in this case.
