### ISSUE TITLE
Rephrase closing tab/kernel dialog.

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#281]
The closing tab dialog that ask you whether to keep the kernel or not can be confusing or miss-interpreted.

 - Click on `x` to close tab.
 - get prompted `shut down kernel? `:
   - ok 
   - cancel

The second option reads to me as "No, don't close the tab", while it means, close the tab keep the kernel running.  I think we can greatly improve the text. 

Side question. The dialog text  has a `user-select: none`. I think it is really important for user to be able to copy-past error messages or dialog if they don't understand. Was this added on purpose ? Can we re-override at least on the dialog body text to `user-select:text`?

**Comment by Carreau** [comment]
Alternatively, if you close a tab, and click "close a tab without saving" > "yes" and "shutdown kernel" >"cancel" I would expect cancel to not close the tab. 

I would suggest changing the naming to be a more explict "close"/"leave open" for the first dialog, and "Shutdown" / "leave running" for the second one. 

I think for this specific case, we might want to redesign deeper to not have 2 dialog back to back. 
Maybe just a "close" dialog with a "shutdown kernel" checkbox ?

**Comment by jasongrout** [comment]
I think we don't ask about shutting down the kernel anymore. Is that right, @blink1073?

**Comment by blink1073** [comment]
Correct.

**Comment by jasongrout** [comment]
Why did you reopen this issue?

**Comment by blink1073** [comment]
Because I'm on my phone and wasn't sure if the whole issue had been addressed.

**Comment by jasongrout** [comment]
Yep, it doesn't apply anymore. And I can select text in the Close without saving dialog, answering his other question.
