### ISSUE TITLE
Keyboard events in widgets act as commands

### ISSUE THREAD

**Issue by fperez** [jupyter/jupyterlab#288]
This is best illustrated below. When typing into a text widget, the keyboard events are getting captured and interpreted as commands.  In the example below, I start with "hello" in the text field and try to type "world", but when I hit "r", the cell gets immediately converted to a "raw" cell instead:

![untitled](https://cloud.githubusercontent.com/assets/57394/16715893/b4a55666-46a1-11e6-936e-3075339fc40f.gif)

This can be tested with this snippet for copy-paste convenience:

```python
from ipywidgets import interactive
interactive(lambda x:x, x="hello")
```

Additional note: though the closing at "r" of the cell makes it hard to see, it's worth mentioning that the widget isn't working yet in terms of actually displaying the output text as it's typed. But I figured that issue is already known and being worked on as part of getting the widgets fully functioning.  But I wanted to highlight first this one that is specific to text input separately.

**Comment by jasongrout** [comment]
Interact doesn't work right now, but that is a focus of mine to try to get
done before scipy.

**Comment by fperez** [comment]
Great, thanks! I figured I'd put it on the milestone so we track it :)

**Comment by jasongrout** [comment]
`@interact` is working now, but this is still an issue.

**Comment by blink1073** [comment]
@jasongrout, I handled this in #517 by preventing key events from propagating beyond the input request widget.

**Comment by jasongrout** [comment]
Yep, makes sense.

**Comment by fperez** [comment]
BTW, widgets aren't working at all right now, correct? Was that a known, temporary regression or an unintentional one?

**Comment by blink1073** [comment]
It was causing breakage, so we removed it until we get third party extension working.

**Comment by fperez** [comment]
No problem, good to know. Thanks!

**Comment by jasongrout** [comment]
Closing, since compatibility with JupyterLab is now being done in the ipywidgets repo, currently at https://github.com/ipython/ipywidgets/pull/727.
