### ISSUE TITLE
Innacurate shortcuts to change cell to codecell

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#298]
While in notebook and command mode, it seem like `E` is changing cell back to code. while it seem to me that normal notebook is `Y`. Not sure if it was on purpose.

**Comment by jasongrout** [comment]
Confirmed on both accounts.

**Comment by blink1073** [comment]
We added undo/redo, and redo is classicly `Y`

**Comment by sccolbert** [comment]
We should probably have a document which keeps a running list of keyboard shortcuts we are currently providing by default, along with a big banner which says that they are user customizable. We should also make that customizer plugin :)

**Comment by jasongrout** [comment]
+1. I was sorely tempted to do the notebooks "H" in command mode to get the shortcut list, but of course that doesn't work in JupyterLab.

**Comment by jasongrout** [comment]
> We added undo/redo, and redo is classicly Y

Sounds like this needs discussion - about  whether backwards compatibility or consistency is more important...

**Comment by Carreau** [comment]
> Sounds like this needs discussion - about whether backwards compatibility or consistency is more important...

Agreed, I'm fine changing (slightly) the keyboard shortcut, but we have to be careful with user habit.
I guess that if `Y` is redo and there is nothing to redo we might try to pop-up a `"codecell" is now <whatever>` to help user to transition.

**Comment by sccolbert** [comment]
My point about being customizable, is that we have to care a lot less about making everyone happy with the default shortcuts, since they'll be easily able to change them to whatever they want.

**Comment by Carreau** [comment]
> My point about being customizable, is that we have to care a lot less about making everyone happy with the default shortcuts, since they'll be easily able to change them to whatever they want.

I understand, though I think the number of people that would actually take time to customize shortcuts is low.

I think it also nice to be able to borrow someone else computer and have usable shortcut.
The issue with customizability, is that if Y is taken by redo, then it need to be kicked-out to another shortcut, that might displace another action, which itself need a new shortcut... etc.

I also want to take into account the number of document [books, video tutorials like the one of O'reilley] that list our "to code" shortcut as being `Y`, and ponder that as well.

Devil advocate, `to code` is likely less used the `to markdown`, so will likely interfere with only a minority of users.

Maybe we can get info from the user-testing that happen as SciPy ?
Who among @rnetro, @eskirk, @faricacarroll, @spoorthyv , @roshancvp , @charnpreetsingh185 or @matt-bowers can tell us how many users used keyboard shortcuts to change cell type ?

**Comment by jasongrout** [comment]
@Carreau - My guess is that we would provide an easily-selectable option to set up shortcuts exactly like the old notebook.

**Comment by faricacarroll** [comment]
@Carreau There were only a couple users that used keyboard shortcuts to change cell type. Most of the users selected the dropdown menu on the notebook toolbar.

**Comment by Carreau** [comment]
>  My guess is that we would provide an easily-selectable option to set up shortcuts exactly like the old notebook.

I like the idea of "context manager for shortcut maps". 

> There were only a couple users that used keyboard shortcuts to change cell type. Most of the users selected the dropdown menu on the notebook toolbar.

Ok, great ! Thanks, that's useful to know !

**Comment by jasongrout** [comment]
> @Carreau There were only a couple users that used keyboard shortcuts to change cell type. Most of the users selected the dropdown menu on the notebook toolbar.

Not only do I use the dropdown, but I'm often accidentally changing the cell type from keyboard shortcuts...

**Comment by ellisonbg** [comment]
We have decided to use shift+z for redo and go back to y for code cell.

**Comment by Carreau** [comment]
Thanks Brian, that seem closer to other shortcuts I expect. 

Was (Cmd/Ctrl)-Shift-Z considered as well as it is also common ? 
As I said in a previous comment in a separate PR: 

Would it be possible to have a summary of the reasoning as of to why – if possible pro and cons ? Knowing how and when you discussed this would also be helpful for future reader , for archival reason , and understand the process of decision as well as have it look like an open participative process.

Otherwise it make the process looks like a black box. It also is hard to know what the "we" is. While I seem to agree with the decision you have taken, I was not part of this we, so would appreciate an expansion of this `we` to be clearer for future reader (that can be ourself). 

Thanks.

**Comment by blink1073** [comment]
We used (Cmd/Ctrl)-Shift-Z as inspiration (used by Chrome, for example), but we are already in command mode, so dropping the (Cmd/Ctrl) part is consistent.  

Using this enables us to keep using the existing notebook shortcuts while using a sensible shortcut for the new command (redo).

We in this case is @jasongrout @ellisonbg @afshin  and myself.

**Comment by jasongrout** [comment]
@Carreau - we had an video-conferenced triage session on the bluejeans jupyter channel for the needs-discussion issues. The meeting was announced on the jupyterlab gitter channel and in the jupyterlab dev meeting last Friday. @ellisonbg, @afshin, @blink1073, and I attended.

**Comment by Carreau** [comment]
> We used (Cmd/Ctrl)-Shift-Z as inspiration (used by Chrome, for example), but we are already in command mode, so dropping the (Cmd/Ctrl) part is consistent.
> 
> Using this enables us to keep using the existing notebook shortcuts while using a sensible shortcut for the new command (redo).

Thanks that is a really good reason.
