### ISSUE TITLE
Flip Right (or left) Dock panel test 180º ?

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#305]
The "Running" tab reads up down, While the `File/Commands` one reads bottom/up.

I think rotating one of the 2 by 180º to have the text in the same direction, might help make things more readable at a glance. 

I'm likely more affected than natives english as the words don't jump to my eyes and I have to incline my head a bit in each direction. 

Do @ellisonbg have thoughts on that ?

**Comment by ellisonbg** [comment]
We are currently working on some more significant re-design of the tab interface in #696 for the R/L panels that would also happen to resolve this issue. Closing in light of that larger effort.
