### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by jots** [jupyter/jupyterlab#307]
doing developer install, during this step: `pip install -e .` get:
```
 ModuleNotFoundError: Module not found: Error: Cannot resolve module 'jquery-ui/themes/smoothness/jquery-ui.min.css' in /home/myuser/jupyterlab/jupyterlab/node_modules/jupyterlab/lib/widgets
        at /home/myuser/jupyterlab/jupyterlab/node_modules/webpack/lib/Compilation.js:229:38
```
using latest node and npm.

**Comment by Carreau** [comment]
I got the same here https://github.com/jupyter/jupyterlab/issues/265, it shoudl be fixed on master. 

pull, clean all (`git clean -xfd`) and reinstall, and it should work.

**Comment by jots** [comment]
Ah, that was it.  I was out of sync with upstream.  Sorry about that.
Really love this UI!
