### ISSUE TITLE
Change instruction to use `jupyter notebook` ?

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#308]
**SUMMARY**

Add command or menu item to open current Jupyter Notebook

---

If you start with `jupyter lab` the fact that you start on the lab page is nice, though we should likely have a way to access to the normal dashboard. 

CC @ellisonbg, discuss in person, might need more discussion.

**Comment by eskirk** [comment]
Seems like #311 has a decent solution to this

**Comment by jasongrout** [comment]
@eskirk - does #311 let you open the current notebook?

**Comment by eskirk** [comment]
@jasongrout what do you mean by current? if you have a notebook currently open couldn't you just click it up in the tab bar?

**Comment by jasongrout** [comment]
> Seems like #311 has a decent solution to this

I read @Carreau's request as asking for a way to access the `/tree` URL from JupyterLab (in essence, a way to go back to the existing Jupyter Notebook 4.2 `/tree` page). You said #311 had a solution, so I was just double-checking to make sure we were communicating clearly.

**Comment by jasongrout** [comment]
We discussed this, and decided that we didn't want to clutter the lab interface with a link back to the current notebook.

**Comment by Carreau** [comment]
> @ellisonbg, @blink1073, @afshin, and I discussed this, and decided that we didn't want to clutter the lab interface with a link back to the current notebook.

Great, thanks. I would love to have a summary of the reasoning as of to why – if possible pro and cons – and what is the answer you give to user of lab when they want to access the normal notebook. Knowing how and when you discussed this would also be helpful for future reader t o understand the process of decision and having it look like an open participative process. 

I appreciate it.

**Comment by blink1073** [comment]
We saw these as two different actions: run `jupyter lab` to use JupyterLab if you have it installed, and run `jupyter notebook` to explicitly run the existing notebook (or switch the URL in either case if you are a power user).

**Comment by jasongrout** [comment]
@Carreau - we had an video-conferenced triage session for the needs discussion issues that was announced on the jupyterlab channel and in the dev meeting. For this issue, as @blink1073 said, we see running `jupyter lab` as a separate activity from running `jupyter notebook`.

Given that, though, I wouldn't be opposed to a menu item for now to open a new tab with the `/tree` url - would that be sufficient for your usecase? If you feel this issue needs further discussion, then let's reopen it.

**Comment by Carreau** [comment]
> Given that, though, I wouldn't be opposed to a menu item for now to open a new tab with the /tree url - would that be sufficient for your usecase?

Yes, I think that would be enough.

> hat was announced on the jupyterlab channel and in the jupyterlab dev meeting last Friday

I think it is hard to ask people to follow gitter. I can understand that some people might be able to follow, but seeing that most of the mentions I get on gitter at `@/all` and most often don't concern me I had to tell gitter to stop notifying me, which sadly also affect the JupyterLab channel . So I did not get the mention; and I was under the impression that at the dev meeting we agreed that announcement and decision can be made on gitter but should also be made on wider channel. 

I, because of some other conversation I had, figured out there was a meeting this morning, and when the decision was taken. Because I am aware of the process I can likely find the video and figure out who was in the decision process, and know how to access it. 

My request was not particularly toward me wanted to know – sorry if it was not explicit. It was more trying to convey that the process of decision looks from an external contributor point of view as black box. @jasongrout did already a good job of saying who was there, so it's easy to infer who was not. I'm mostly just requesting wether it's possible to make a general effort, for our own sake when we will review that to be slightly more verbose. 

> @ellisonbg, @blink1073, @afshin, and I discussed this [this morning (if possible add date, though it is in github comment) on a video meeting we had which is available on youtube at this link, the notes are on the hackpad as usual] , and decided that we didn't want to clutter the lab interface with a link back to the current notebook.

Agreed it is twice as long, but for anyone interested (or us in the future) we can get to this link and remember why & how things were done, as well as tell to user that we do things in public, we do have meeting, and we do not make decisions behind closed doors. 

I know I am guilty of not doing this enough, and i'm sorry I could not have made it to this morning meeting, plus apologize if the comment fall on this PR on particular; but receiving N mails that roughly read "We decided that foo. Closing."  felt like authoritative decision not wanting to include anyone that did not participate in this discussion, nor trying to get more user involved. I, being a regular in these meeting, know that it is not the case, and I'm just trying to encourage everyone to remember that not every use is working 24/7 on all the issues and a small difference in the writing on summary or decision can go a long way toward including more people. 

I saw the following recently [on twitter](https://twitter.com/kaz/status/757733261938298881)

> User-friendly copy can be a growth strategy. Both of these messages convey the same point…which would you rather use 

![coqbzdvviaadxao](https://cloud.githubusercontent.com/assets/335567/17911514/c03722b6-6942-11e6-99b8-f81e3e622c64.jpg)

**Comment by jasongrout** [comment]
> I'm mostly just requesting wether it's possible to make a general effort, for our own sake when we will review that to be slightly more verbose.

Thanks for the reminder! I really appreciate you bringing this up.

**Comment by jasongrout** [comment]
Re-opening, with a TODO item in the summary.

**Comment by Carreau** [comment]
> Re-opening, with a TODO item in the summary.

Ah ! I should have thought that issue could be reopened ! Thanks a lot for that !
Thanks Jason !

**Comment by jasongrout** [comment]
Now this one TODO item makes it a dup of #69.
