### ISSUE TITLE
Allow to open notebook through 'running' panel.

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#314]
The running panel on the side is useful to shutdown kernel you don't want anymore, 
though as it list the notebooks names, I think that clicking on the notebook name should open the notebook, or make it's tab focused if already opened. 

That's how the current notebook behave.

**Comment by blink1073** [comment]
I had meant to open an issue for this, I will add it once we consolidate to the new phosphor.

**Comment by fperez** [comment]
Agreed! 

I've added [a few additional sub-tasks](https://github.com/jupyter/jupyterlab/issues/161#issuecomment-232249081) to the main 'running' issue (#161), I'm going to close this one so we track that feature's completeness in a single location. I'm sure we'll want to fine tune quite a few things about it.
