### ISSUE TITLE
Global design tasks

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#315]
The following are global design task we aim to complete by our SciPy 2016 talk:

- [ ] Change primary color (@ellisonbg)
- [ ] Darken dock area background?
- [ ] Go back to 13px UI font
- [ ] Install MD icons to repare for switch to MD icons @ 18-20px (@ellisonbg)
- [ ] Use different icon for unsaved changes in tab
- [ ] Review layout of CSS files (@ellisonbg)
- [ ] Context menu styling
- [ ] Add "Jupyter icon" menu on L with all launcher items
- [ ] Add L/R border to L/R stacked side panel

Each plugin will have a base.css with structural CSS
The default-theme folder will have a separate file for each plugin that has the actual styling.

**Comment by neilpanchal** [comment]
@ellisonbg Thanks. I would love to collaborate, provide feedback and contribute when it can be entertained.

**Comment by jasongrout** [comment]
@ellisonbg - which did we do? What is the status here?

**Comment by blink1073** [comment]
I moved the remaining Scipy2016 takes to 0.9.

**Comment by jasongrout** [comment]
@ellisonbg - are these done or obsolete now? Can we close the issue, and migrate any undone items to their own issues?

**Comment by ellisonbg** [comment]
Closing this as we are tracking these things elsewhere.
