### ISSUE TITLE
Launcher plugin tasks

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#316]
The following are tasks related to the launcher plugin tasks we aim to complete by SciPy 2016.

- [x] Add a link to the "JupyterLab Tour" ( @roshancvp )
- Add the cwd of the file browser ( @blink1073 and @roshancvp ) -> #475.
- [x] Rename tab "Launcher" ( @roshancvp )

**Comment by eskirk** [comment]
#311

**Comment by roshancvp** [comment]
@ellisonbg Tasks 1 & 3 are done. #311

**Comment by jasongrout** [comment]
@roshancvp - progress on the cwd task?

**Comment by roshancvp** [comment]
@jasongrout I still haven't been able to figure out how I can get the cwd with javascript. What should I do here?

**Comment by blink1073** [comment]
We now provide a `PathTracker` that you can `require[]` in your plugin: https://github.com/jupyter/jupyterlab/blob/28ae2cc07dba53f64254712324514b487479a5f3/src/filebrowser/plugin.ts#L57

**Comment by jasongrout** [comment]
Tracking the last item at #475.
