### ISSUE TITLE
Command palette tasks

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#318]
The following are tasks related to the command plugin tasks we aim to complete by SciPy 2016.

- [x] Fix typography colors in command palette
- Move to global modal dialog? -> opened  #507
- [x] 13px UI font

**Comment by eskirk** [comment]
#305  
Should this be added as a task or do we want to keep the text orientation as it is?

**Comment by charnpreetsingh185** [comment]
@charnpreetsingh185
