### ISSUE TITLE
Text editor plugin tasks

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#322]
The following are tasks related to the text editor plugin tasks we aim to complete by SciPy 2016.

- [x] L/R/B border ( @eskirk)
- [x] Add text editor menu ( @eskirk )

**Comment by eskirk** [comment]
I got these, I have a branch with exactly these changes just kinda sitting around

**Comment by eskirk** [comment]
@ellisonbg do we still need the borders since you guys decided on a slightly different change? Because if then this task is donezo
