### ISSUE TITLE
FAQ plugin tasks

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#325]
The following are tasks related to the FAQ plugin tasks we aim to complete by SciPy 2016.

- [x] Content review and additions (@Carreau)

**Comment by Carreau** [comment]
Misc ideas:

  - Think about maybe not hiding the response in a collapsible area, and just make a TOC a the top. 
    This woudl allow users to search with browser Ctrl-F. 

### How stable is Jupyter Lab

> Jupyterlab is not currently in version 1.0, we are still working on bringing feature parity with the current notebook. We strongly recommend to backup your work before using JupyterLab. 

[Will edit this comment further]

**Comment by jasongrout** [comment]
We now have a good set of questions/answers (thanks @Carreau!). 

> Think about maybe not hiding the response in a collapsible area, and just make a TOC a the top.

+1. @charnpreetsingh185 - what do you think?

**Comment by blink1073** [comment]
This is also the only place we're currently using jQuery in the application.

**Comment by jasongrout** [comment]
Making it not hide things would eliminate that too? +1.

**Comment by charnpreetsingh185** [comment]
Sounds good to me! I'm currently rewriting this page with the virtual dom APIs for easier readability/maintainability. Planning on getting ride of jQuery and adding in a TOC at the top

**Comment by jasongrout** [comment]
It's not being updated dynamically, right? It may be easiest just to stick the html into a huge text string and slap it in a div. Is there a reason to use the virtual dom over a static html string?

**Comment by charnpreetsingh185** [comment]
Right, its not being updated dynamically. Originally the page was entirely in inner html and that prohibited access to the app object needed to open the tour page.

**Comment by jasongrout** [comment]
Ah. You could still make it inner html, and then find the one element that needed that javascript, and add it manually.

**Comment by charnpreetsingh185** [comment]
Ah thats a really good idea!

**Comment by jasongrout** [comment]
Great. Let's make this another issue, since @Carreau did review the faq items (which is what this issue was about).
