### ISSUE TITLE
Going to command mode "Jumps"

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#326]
Though, going to edit mode does not. 
This make me think there is likely a extra call to "focus"
![jump](https://cloud.githubusercontent.com/assets/335567/16772187/dac9aba8-4818-11e6-8766-d3ab7ed68873.gif)

**Comment by eskirk** [comment]
Most annoying bug we currently have...

**Comment by jasongrout** [comment]
@Carreau - this seems to be fixed for me now. Can you try to reproduce it with the current master?

**Comment by Carreau** [comment]
If I nitpick a lot, with an extremely rare case, yes:

![jump-iv](https://cloud.githubusercontent.com/assets/335567/16969145/c23f79a0-4dc7-11e6-9559-1a22d5a7afd7.gif)

Though the jump is:
 - much smaller, 
 - extremely hard to reproduce. 
 - with a sequence of keys that seem to be unlikely (or rare at least).

So feel free to close, or bump to enhancement, or consider the issue as minor annoyance.

**Comment by jasongrout** [comment]
I'm reliably reproducing this now. The way I'm doing it is to create a notebook with lots of cells (so there is a scrollbar), then scrolling all the way to the top, the clicking on, say, the third cell to enter edit mode, then pressing escape to go to command mode. The scroll position jumps when going to command mode.

**Comment by jasongrout** [comment]
Okay, I'm pretty sure this line is causing the scroll jump: https://github.com/jupyter/jupyterlab/blob/master/src/notebook/notebook/widget.ts#L756

**Comment by jasongrout** [comment]
It seems that Chrome may have some problems with focusing elements inside of fixed position elements. Possibly relevant bug reports:

* https://bugs.chromium.org/p/chromium/issues/detail?id=437025&q=component%3ABlink%3EScroll%20&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&start=200
* https://bugs.chromium.org/p/chromium/issues/detail?id=520033&q=component%3ABlink%3EScroll%20&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&start=100

**Comment by jasongrout** [comment]
This seems to work in Firefox - no jumps there.

**Comment by jasongrout** [comment]
The notebook DOM structure is: 
* jp-Notebook-panel
  * jp-NBToolbar
  * jp-Notebook-container
    * jp-Notebook
      * jp-Cell
      * jp-Cell, etc.

Now, when we go into command mode, we focus jp-Notebook (presumably to keep the focus on something inside the widget? Is this partly for keyboard handling, or for keeping that notebook as the active widget?). Focusing jp-Notebook causes the jump in Chrome (jp-Notebook-container has overflow auto, so there is a scrollbar). If we focus jp-Notebook-container at https://github.com/jupyter/jupyterlab/blob/e288fbfc08bfeff26498071456c671db1ba660c0/src/notebook/notebook/widget.ts#L756 instead, we don't have a jump in Chrome. We don't seem to have a jump in firefox either way.

@blink1073, @sccolbert - thoughts?

**Comment by blink1073** [comment]
That seems fair to me.

**Comment by jasongrout** [comment]
The thing is that if you embed the notebook itself in another page, and the notebook is not in a fixed position div that scrolls notebook content, the bug may not be there, so focusing the parent of the notebook may be the wrong thing. That's my hesitation.

**Comment by jasongrout** [comment]
We could make it an option, that seems to be building in a lot of kludge to work around the bug.

**Comment by jasongrout** [comment]
I've started working on this, so ping me if someone else wants to look into it.

**Comment by jasongrout** [comment]
@Carreau - recently the DOM structure changed for notebooks, and this seems to be fixed now. Can you check?

**Comment by Carreau** [comment]
That's seem to be fixed on my side. Thanks all !
