### ISSUE TITLE
Repeatedly clicking 'Switching Console Kernel' Bug

### ISSUE THREAD

**Issue by charnpreetsingh185** [jupyter/jupyterlab#336]
Repeatedly clicking switching console kernel bug results in the background surrounding the change kernel dialog to darken repeatedly. Also, after the background darkens it takes several repeated clicks on the cancel button in the switch kernel dialog to actually exit the dialog. 

![bug2](https://cloud.githubusercontent.com/assets/16314651/16775766/d7647a38-4827-11e6-8766-d84374e6d642.gif)

**Comment by blink1073** [comment]
This is fixed by #347, the dialogs are now modal to the whole application.
