### ISSUE TITLE
Markdown not rendering images

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#337]
This in Jupyterlab lead to a white `Image` rectangle:

```
![image](https://bids.github.io/colormap/images/screenshots/option_d.png)
```

The rendered html has no `src` attributes:

```
<p><img alt="image"></p>
```

**Comment by eskirk** [comment]
Probably similar to #313? Maybe?

**Comment by afshin** [comment]
@eskirk you're right, it's the same issue.

@Carreau thanks for finding it, I think we now have a better way of handing this.
