### ISSUE TITLE
Clear the CodeMirror history when creating a new cell after setting content

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#343]
- Open an existing notebook
 - enter edit mode in a pre-populated cell. 
 - press Ctrl-Z

Expected:
  - nothing should happen

Observed
  - The cell becomes empty

Probable Cause:
  - Codemirror gets instantiated with empty string, and set with the content of the cell. 
  - Ctrl-Z get back in history to the empty string 

Improvement likely call [`doc.clearHistory()`](http://codemirror.net/doc/manual.html#clearHistory) after loading a cell.

**Comment by ellisonbg** [comment]
Good catch! Fully agree we should clear the history when creating a new cell

**Comment by Carreau** [comment]
> Good catch! Fully agree we should clear the history when creating a new cell

This is inaccurate and i believe your change in title as well. We don't want to clear history on _new_ cell, we want to clear history when a cell is _loaded_ with some content.
