### ISSUE TITLE
Couple of focus inconsistency in command/edit mode

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#344]
Requirement:
  -  Have cell with long input, typically a graph higher than the page. 

Observation, going in and out of command mode(with keyboad and or mouse) lead to various "jump" in the page position:

Expected, staring in edit mode:
 - [esc],[enter],[esc],[enter],[esc],[enter]  should not make the page move. (at least not anymore after the first cycle)

Observed:
 - Esc scroll page to bottom of the cell, 
 - Enter to the top.

![jump-ii](https://cloud.githubusercontent.com/assets/335567/16780714/7b160966-483d-11e6-8c7a-946fa97f098b.gif)

Clicking in an unfocus cell editor, scroll to it's bottom.

Expected:
  - Cell don't move, or at least scroll to editor (not bottom)

![jump-iii](https://cloud.githubusercontent.com/assets/335567/16780820/f7535588-483d-11e6-9ab2-869f81eb209b.gif)

**Comment by metaperture** [comment]
Simplest way to reproduce the above:
 - if you do `print("\n" * 100)` (or whatever number gets you do the bottom of the page), go to another cell, and try to put the cursor in the cell code box, you see the scroll not work
Additionally:
 - if you do `import time; time.sleep(10)`, and Shift-Enter execute that cell, then keep typing in that cell, when the execution finishes your focus changes to a new cell (often mid-word, for me).

**Comment by jasongrout** [comment]
Thanks @metaperture. The original bug should be fixed in master (#486). Did you reproduce it in master?

I've opened #518 for your other bug.

**Comment by jasongrout** [comment]
@Carreau - can you see if your original bug is fixed in master?

**Comment by jasongrout** [comment]
ping @Carreau - do you still see this on current master?

**Comment by jasongrout** [comment]
@Carreau - both of your original issues seem to be fixed in master for me. Please reopen if you're still seeing these.
