### ISSUE TITLE
File browser & sort by "Last Modified"

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyterlab#352]
When sorting files with respect to "last modified" or by "name" in the reverse order, the old "sort by name" order is used again after a short period of time ~1sec.

@blink1073

**Comment by blink1073** [comment]
Isn't that what you expected to see?

**Comment by SylvainCorlay** [comment]
I guess not, this makes your choice very transient... And it reverts it after a non-deterministic duration... (Depending on when you clicked in the polling loop).
