### ISSUE TITLE
Use CSS variables or a preprocessor

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#37]
This seem to be able to compile css variable:

https://www.npmjs.com/package/postcss-css-variables (http://postcss.org/).

**Comment by Carreau** [comment]
Ping @sccolbert. 

And less dynamic on the browser:

http://lesscss.org/usage/#browser-support

http://lesscss.org/usage/#using-less-in-the-browser-modify-variables

**Comment by SylvainCorlay** [comment]
Having the original source (of the css with variables or less) served dynamically would allow libraries like custom widget to read things like colors and use an in-browser compiler.

**Comment by ellisonbg** [comment]
Also this: http://stylus-lang.com/

**Comment by ellisonbg** [comment]
Closing in favor of #647
