### ISSUE TITLE
File manager resets to starting directory every 10 seconds

### ISSUE THREAD

**Issue by fperez** [jupyter/jupyterlab#371]
As the title says... Change directories in the FM, wait  10 seconds, it auto-reverts to the starting dir...

**Comment by jasongrout** [comment]
The Filebrowser also resets to the root directory every time I open a file.

**Comment by ellisonbg** [comment]
Also, we are no longer triggering a refresh when the user makes explicit
changes.

On Thu, Jul 14, 2016 at 9:32 AM, Jason Grout <notifications@github.com>
wrote:

> The Filebrowser also resets to the root directory every time I open a file.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyterlab/issues/371#issuecomment-232682928>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0KNUzXB65-2RqbHc5smPJpuMWy5hks5qVkiMgaJpZM4JMPIl>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
