### ISSUE TITLE
When opening a new console, the cursor is not in the entry field

### ISSUE THREAD

**Issue by asmeurer** [jupyter/jupyterlab#388]
When I open a new console, the cursor is not put in the entry field. I have to click it to to start typing things. I am using jupyterlab master.

**Comment by fperez** [comment]
Confirming, just came here to open this very issue. Thanks @asmeurer for beating me to the punch :) Tagging for 0.90, it's a fairly up-front usability issue.

**Comment by afshin** [comment]
This is something that the new focus tracker will help resolve. We talked
about it a bit and decided to not implement it "the wrong way" in the
meantime since upgrading to the phosphor mono repo is imminent.

cc: @sccolbert

**Comment by fperez** [comment]
No worries, there's no rush. As long as we're tracking it :)

**Comment by blink1073** [comment]
Fixed by #636.

**Comment by fperez** [comment]
Confirming fix, thx!!
