### ISSUE TITLE
Create .py file on 'Start new activity'

### ISSUE THREAD

**Issue by gabrieldlm** [jupyter/jupyterlab#393]
Although this can be achieved by creating a text file and renaming to .py, as Jupiter Lab been an IDE wouldn't be interesting have an option for create a .py file on the new activity tab and a shortcut to open a new terminal and run the script?

**Comment by blink1073** [comment]
Hi @gabrieldlm, both are great ideas.  We will soon have a more advanced "create new" dialog that will allow you to set the file type/name and other options.  Additionally, plugins could be used to provide the second capability, including running in a terminal or a rich Jupyter Console.

**Comment by ellisonbg** [comment]
This type of feature is going to show up as we continue to iterate on our new activity UI/UX. Closing this issue now, but there will be a series of other issues to track this type of stuff.
