### ISSUE TITLE
invalid kernelspecs model, labs doesn't open

### ISSUE THREAD

**Issue by Gijs-Koot** [jupyter/jupyterlab#395]
Using Debian, Chrome and an Anaconda Python 3.5 installation, I have installed Jupyter Lab with `pip`, 

    $ pip install jupyterlab
    Collecting jupyterlab
     ....
    Installing collected packages: jupyterlab
    Successfully installed jupyterlab-0.0.10
    $ jupyter serverextension enable --py jupyterlab
    Enabling: jupyterlab
    - Writing config: /home/gijs/.jupyter
         - Validating...
         jupyterlab  OK

When starting the lab with `jupyter lab`, both Chrome and Firefox show nothing, except for the title of the page. Chrome reports this:

    kernel.js:138 Uncaught (in promise) Error: Invalid KernelSpecs Model(…)(anonymous function)

And Firefox, 

    Error: Invalid KernelSpecs Model1 bundle.js:19142:20

**Comment by blink1073** [comment]
Hi @Gijs-Koot, if you open the original notebook (as `jupyter notebook`), and select the `New` dropdown, does it by changes say `Python [Root]`?

**Comment by buzmakov** [comment]
I have the same issue and I have ```Python [Root]``` option in ```New``` dropdown.
The log of starting JupyterLab is:
```
[makov-G46VW]➜  ~ conda create -n jupyterlab anaconda python=3
....
[makov-G46VW]➜  ~ source activate jupyterlab 
....
(jupyterlab) [makov-G46VW]➜  ~ conda install -c conda-forge jupyterlab
....
(jupyterlab) [makov-G46VW]➜  ~ jupyter lab     
[W 21:30:11.765 LabApp] Unrecognized JSON config file version, assuming version 1
[W 21:30:11.767 LabApp] Unrecognized JSON config file version, assuming version 1
[W 21:30:11.768 LabApp] server_extensions is deprecated, use nbserver_extensions
[I 21:30:12.261 LabApp] [nb_conda_kernels] enabled, 9 kernels found
[I 21:30:12.357 LabApp] ✓ nbpresent HTML export ENABLED
[W 21:30:12.358 LabApp] ✗ nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
[I 21:30:12.358 LabApp] Pre-alpha version of JupyterLab extension loaded from /home/makov/opt/anaconda/envs/jupyterlab/lib/python3.5/site-packages/jupyterlab
[I 21:30:12.361 LabApp] [nb_conda] enabled
[I 21:30:12.401 LabApp] [nb_anacondacloud] enabled
[I 21:30:12.405 LabApp] Serving notebooks from local directory: /home/makov
[I 21:30:12.405 LabApp] 0 active kernels 
[I 21:30:12.405 LabApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 21:30:12.405 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Created new window in existing browser session.
[W 21:30:14.605 LabApp] 404 GET /favicon.ico (127.0.0.1) 30.88ms referer=http://localhost:8888/lab
```

**Comment by blink1073** [comment]
This is related to https://groups.google.com/forum/#!topic/jupyter/qE6fCyXe6fs.  We are relying on the `default` kernel name returned by the server to match one of the kernel specs, and this bug has caused a  mismatch.

**Comment by Gijs-Koot** [comment]
@blink1073 Yes, if I open a notebook, the option is `Python [Root]`.

**Comment by damianavila** [comment]
This is not directly impacting jupyterlab now, but just to let you know, we've released versions of nb_conda, nb_conda_kernels and nb_anacondacloud through the official Anaconda conda repos that should resolve the issues you saw with Python[root].

**Comment by Gijs-Koot** [comment]
Thanks! Updating the packages you mentioned resolved the issue for me.
