### ISSUE TITLE
Menu Bug

### ISSUE THREAD

**Issue by amirmasoudabdol** [jupyter/jupyterlab#396]
Hi,

I found that the main menu is not showing correctly in Safari 9. File and Commands are overlapping.

![](http://i.imgur.com/PUniLI7.png)

A.

**Comment by blink1073** [comment]
Hi @amirmasoudabdol, this is a known bug in Safari where the browser is not respecting the CSS spec for flex box.

**Comment by jasongrout** [comment]
Sorry - it's unfortunate that Safari is buggy in this way. Can you use Chrome or Firefox?

**Comment by uetchy** [comment]
Same behaviour here.
We should do some work-around for this.
