### ISSUE TITLE
Allowing tmux shortcuts to be sent to terminal

### ISSUE THREAD

**Issue by kehey** [jupyter/jupyterlab#397]
The terminal in the lab is incredibly awesome. At this point I mostly work with a notebook and a putty session for things like htop and installations. I do this within tmux, and the question is related to this.

I'm not sure this would ever be possible, or even lies at the side of the lab to fix, but at this point, my tmux shortcuts are calling the firefox, instead of going to the terminal and tmux.

Would there be a way to let the browser know that when the focus is on the terminal? Or would there be a possible shortcut (=lead key) definition possible that you know of that would make this work?

**Comment by afshin** [comment]
JupyterLab has a configurable keyboard shortcut system, so it is possible to write an extension that supports any set of keyboard shortcuts a user might want. We are also still discussing how to save user settings, but one of the goals on the roadmap is to allow user settings to include configurable shortcuts. Any keyboard shortcut that is currently "owned" by the browser can, in theory, be caught before it bubbles up to the browser and instead by used as an event in JupyterLab.

So yes, it is possible ... sometime soon 😄

**Comment by bilderbuchi** [comment]
> JupyterLab has a configurable keyboard shortcut system

Seeing how JupyterLab [seems to plan](https://news.ycombinator.com/item?id=12102973) to be heavily extensible with user plugins, I'm wondering how the keyboard shortcut system will deal with shortcut collisions between plugins? For a similar situation, I like using Atom and its host of user plugins, but I am increasingly seeing conflicts between plugins' shortcuts if you use many plugins, as the authors select them themselves. I wish they would have gone a way similar to Spacemacs, where the shortcuts seem to be composed with a leader key (e.g. ` SPC h d f`  for help-describe-function), with effectively a namespace tree for each component, reducing the potential for collision very much.

**Comment by sccolbert** [comment]
@kehey Some browsers pre-empt *certain* shortcut combinations, and we'll never be able to trap those since those key events are never actually delivered to browsers. Which shortcuts in particular are not working?

@bilderbuchi Our shortcut system supports chords, so you can have multi-key sequences such as `Ctrl+P K Q W` if you like. We don't encourage plugin authors to provide their own shortcuts (in general). Rather, the plugin author provides the commands which do the action, and the user can freely supply their own shortcut binding to the command. *Currently* we are providing default shortcuts because we haven't yet built the settings plugin to allow you to configure them yourself with ease.

**Comment by bilderbuchi** [comment]
Nice, thanks for clearing that up!

**Comment by kehey** [comment]
@sccolbert At this point it's just my tmux lead key, which is `ctrl+B` that will open up the bookmarks. I'm perfectly fine switching my tmux lead key, but I'm not sure what will work. 

In other situations (e.g. in this github comment box), `ctrl+B` is actually sent to the comment box for text to be bold so it's not the that this key combo is always sent to firefox. So that's why I wonder whether the terminal in the lab is even trying to catch these kinds of key combinations.

**Comment by jasongrout** [comment]
@kehey - sounds like you fixed it. Can we close this?

**Comment by kehey** [comment]
Yes, we can. :-)
