### ISSUE TITLE
Moving between cell in edit mode.

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#4]
When text cursor is at (0,0), and pressing "up", the previous cell shoudl become selected.

Same with "down" when cursor is the last line, last caracter.

**Comment by jasongrout** [comment]
What you describe happens for me in 0.0.5. However, what is different from the current notebook is that when you are at (0,0) and press up, the current notebook puts your cursor at (last line, 0 character), whereas JupyterLab puts your cursor at (last line, last char).

**Comment by jasongrout** [comment]
Tracing things down, it looks like when we move from one cell to another, we just focus the appropriate codemirror, and the last cursor position in that codemirror is probably the one that is remembered, which in our case in going up is the last line, last char.

Perhaps we should make the behavior be: if you are on the first *line* (anywhere) and press up, you move up to the previous cell, and if you are on the last *line* (anywhere), pressing down moves down a cell.

This is also related to #12, in that both have to do with editor keybindings.

**Comment by blink1073** [comment]
In Sublime, if you hit "up" on the top line, it takes you to the first character, and this is also the behavior in the classic notebook.  I'd say let's match the behavior of the classic notebook.

cf. #528.
