### ISSUE TITLE
Next Steps

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyterlab#41]
- [x] Get API docs autobuilt
- [x] turn on Travis
- [x] Get notebook tests running again
- [x] Basic tutorial documentation about the architecture of phosphide, document manager, and our app
- [ ] Add a work-around in phosphide to, from the appshell, get the current dock panel widget and list of dock panel widgets

**Comment by sccolbert** [comment]
Can you open an issue on phosphor to track the changes/functionality you need?

**Comment by jasongrout** [comment]
Good idea. @blink1073, can you do that?

**Comment by blink1073** [comment]
Yep, on it.

**Comment by blink1073** [comment]
cf https://github.com/phosphorjs/phosphor/issues/77

**Comment by jasongrout** [comment]
This is obsolete now.
