### ISSUE TITLE
Decouple the jupyterlab npm package and the jupyterlab pypi package version numbers

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyterlab#415]
Since the pypi package depends on external packages that themselves depend on the npm package, we have this really weird dependency problem.

We can also split the repos up. Or not hardcode the widgets extension when we get true third-party extensions.

**Comment by jasongrout** [comment]
The ipywidgets lab extension exposed this issue.

**Comment by ellisonbg** [comment]
Hmm, this sounds nasty, would be a good topic for the next dev meeting. Let's try to use this "Needs Discussion" tag for items to discuss at those meetings (Friday 9am)

**Comment by jasongrout** [comment]
The third party extensions work will make this obsolete, so I'm closing this. We've already disabled widgets in the current notebook anyway.
