### ISSUE TITLE
only one shortcut per command

### ISSUE THREAD

**Issue by to266** [jupyter/jupyterlab#423]
It seems that currently the shortcuts only support one per command (hence https://github.com/jupyter/jupyterlab/issues/320 J/K in the notebook are not easily possible)

[this commit](https://github.com/to266/jupyterlab/commit/c137b4e3bad38517934b9f8a2b033583fafda4f0) would ideally add the shortcuts, but since they are higher than the original (arrow) ones, the arrow shortcuts get ignored. 

Looks like the commands are a hash table... Alternatively I'm not adding things correctly (and should have added directly to the `sequence` somehow?)..

------------
edit: 
relevant part of the `phosphide`
https://github.com/phosphorjs/phosphide/blob/master/src/services/shortcutregistry.ts#L50

**Comment by blink1073** [comment]
Hi @to266, this behavior is fixed in the new consildated phosphor repo, which we will be switching over to in the next week or so.

**Comment by jasongrout** [comment]
@blink1073 - done?

**Comment by blink1073** [comment]
Yep, fixed by #591.
