### ISSUE TITLE
Markdown rendered preview (incl. notebooks) doesn't show images

### ISSUE THREAD

**Issue by fperez** [jupyter/jupyterlab#425]
Here's a screenshot showing our own README, neither the gif using `<img>` syntax, nor a plain png I linked (temporarily, just in my local copy) with `![]()` syntax work:

![image](https://cloud.githubusercontent.com/assets/57394/16897148/ab250e86-4b5d-11e6-8f4b-283ca4d39ee1.png)

In contrast, this is what the VSCode preview for the same looks like, both of them render (the gif also animates):

![image](https://cloud.githubusercontent.com/assets/57394/16897151/c5e79946-4b5d-11e6-90c0-71f1689ce5ae.png)

Technically this is almost a bug, but we can always say that our preview MVP has documented limitations (no images), so I'll be conservative and tag it as an enhancement... Feel free to retag as bug if you want...

** Important update:** this problem is also present in notebooks, not just in the render preview of plain markdown files.  Since rendering images is extremely widely used (including in our own docs), this is now tagged for 0.90 as a parity bug.  Here's an example of [one of our notebooks](https://github.com/ipython/ipython-in-depth/blob/master/examples/IPython%20Kernel/Index.ipynb) rendered in both lab (top) and classic (bottom), showing the broken image in lab:

![image](https://cloud.githubusercontent.com/assets/57394/16898202/358eb008-4b82-11e6-9391-cb4a218aa8ad.png)

ps - The basic renderer was requested in #226.

**Comment by fperez** [comment]
ps - The basic renderer was requested in #226.

**Comment by jasongrout** [comment]
Min and I discussed how this should be implemented yesterday. I'll post
more when not on my phone...

**Comment by SylvainCorlay** [comment]
@fperez if the href is not relative this should work

**Comment by fperez** [comment]
Nope @SylvainCorlay: I tried by copying images to the root directory, still no dice:

![image](https://cloud.githubusercontent.com/assets/57394/16897216/e1f81820-4b5f-11e6-9797-a45efe4082b7.png)

Which BTW, even if it worked, wouldn't be a solution, since in general you author md files with relative links so they work when deployed, so we need that to work in the end...

**Comment by jasongrout** [comment]
Don't make absolute references... That breaks base URL.

Jason

**Comment by SylvainCorlay** [comment]
I meant external images (like an image on a different website)

**Comment by fperez** [comment]
Correct @SylvainCorlay, that works.  But there's a huge amount of usage of local images, so we do need that working to consider basic feature parity for the notebook at least.  I said that no rendered images would be OK *for markdown preview*, but for the notebook it's not optional.  

If the fix applies to both and we get images also for the rendered markdown, great. But at least for the notebook we have to have this for basic feature parity.

**Comment by SylvainCorlay** [comment]
Totally, just that it is not specific to markdown but to how content is addressed generally in jupyterlab.

**Comment by fperez** [comment]
Yup, and if we get the fix across the board, that's great!
