### ISSUE TITLE
Annoying jitter in markdown rendered preview

### ISSUE THREAD

**Issue by fperez** [jupyter/jupyterlab#426]
The render preview requested in #226 has an annoying jitter as you type in certain cases. I'm not sure what are all the conditions that trigger it, but at least in our README, with the non-rendering image reported in #425, I get this as I type text below it:

![jlab-render-jitter](https://cloud.githubusercontent.com/assets/57394/16897167/383a5e0c-4b5e-11e6-9331-bdb87fafef86.gif)

For comparison, this is the VSCode preview, which updates the preview without any jitter:

![vscode-render-no-jitter](https://cloud.githubusercontent.com/assets/57394/16897170/47886304-4b5e-11e6-8d51-d813c934d70a.gif)

ps - Tagged as bug because it's really annoying and makes the preview very hard to use when the problem appears.

**Comment by fperez** [comment]
Tagged as bug because it's really annoying and makes the preview very hard to use when the problem appears.

**Comment by jasongrout** [comment]
We don't support local images yet. Is that the problem here?

**Comment by fperez** [comment]
Well, that is specifically listed as $425.  But even if we don't render the images, the jitter of the render preview is incredibly distracting, and we should fix at least that much.  I think it's ok to say "render preview doesn't support images, that will come later", but "render preview will give you a seizure" is a bug IMO :)

**Comment by jasongrout** [comment]
So now we have a bounty on this? :)

Yes, I agree. Either take images out, reset scroll position, or both...

**Comment by fperez** [comment]
On Sat, Jul 16, 2016 at 2:44 PM, Jason Grout <notifications@github.com>
wrote:

> So now we have a bounty on this? :)
>
> Yes, I agree. Either take images out, reset scroll position, or both...
>
> On Sat, Jul 16, 2016, 16:26 Fernando Perez <notifications@github.com>
> wrote:
>
> > Well, that is specifically listed as $425. But even if we don't render
> the
>

Ouch... :)  But hey, talk about warped incentives: tie bounty amount to bug
number, and wait to see how long before someone creates a bot to rack up
the bug numbers as fast as possible and claim the expensive ones... Our
version of Pokemon Go, I guess? :)

Back to reality, glad we agree... The current images experience with that
jumpiness isn't good.
-- 
Fernando Perez (@fperez_org; http://fperez.org)
fperez.net-at-gmail: mailing lists only (I ignore this when swamped!)
fernando.perez-at-berkeley: contact me here for any direct mail

**Comment by groutr** [comment]
I noticed this earlier today too looking at some other things.  I agree, it is very annoying.  I think it would be great too if we could somehow sync the cursor position with the Rendered Markdown scroll position.  That why, if I start editing, the Rendered view would jump to where I was editing.

**Comment by fperez** [comment]
On Sat, Jul 16, 2016 at 2:53 PM, Ryan Grout <notifications@github.com>
wrote:

> I think it would be great too if we could somehow sync the cursor position
> with the Rendered Markdown scroll position. That why, if I start editing,
> the Rendered view would jump to where I was editing.


+1, that would be lovely.


-- 
Fernando Perez (@fperez_org; http://fperez.org)
fperez.net-at-gmail: mailing lists only (I ignore this when swamped!)
fernando.perez-at-berkeley: contact me here for any direct mail

**Comment by jasongrout** [comment]
Syncing cursor position could also be really annoying if you are trying to view one part of the page while typing in another part. Perhaps that could be introduced with a lock button. Another nice thing syncing cursor position would do is have it so that you could scroll through the rendered view and click to jump to that part of the source. Or perhaps locking the two viewers would just sync the scroll position, so scrolling through one automatically scrolls through the other.

**Comment by jasongrout** [comment]
> Ouch... :)  But hey, talk about warped incentives: tie bounty amount to bug
> number, and wait to see how long before someone creates a bot to rack up
> the bug numbers as fast as possible and claim the expensive ones... Our
> version of Pokemon Go, I guess? :)

Well, except we probably want to incentivize fixing long-standing bugs, so maybe the reward would be `1000-bugnumber`, up to bug number 1000...

**Comment by fperez** [comment]
On Sat, Jul 16, 2016 at 4:50 PM, Jason Grout <notifications@github.com>
wrote:

> Syncing cursor position could also be really annoying if you are trying to
> view one part of the page while typing in another part. Perhaps that could
> be introduced with a lock button. Another nice thing syncing cursor
> position would do is have it so that you could scroll through the rendered
> view and click to jump to that part of the source. Or perhaps locking the
> two viewers would just sync the scroll position, so scrolling through one
> automatically scrolls through the other.


Good point... I know some of the better live LaTeX renderers have pretty
sophisticated support for this kind of thing.

But I also think all this is candy: as long as it's not jumping around on
every edit, I think we can live even without images, and once we have
images, it's more than enough for a first cut.

-- 
Fernando Perez (@fperez_org; http://fperez.org)
fperez.net-at-gmail: mailing lists only (I ignore this when swamped!)
fernando.perez-at-berkeley: contact me here for any direct mail

**Comment by jasongrout** [comment]
> But I also think all this is candy: as long as it's not jumping around on
> every edit, I think we can live even without images, and once we have
> images, it's more than enough for a first cut.

Yep. I think the thing to do is to tap into the markdown renderer and strip out img tags with relative urls (img tags with embedded images are still fine, though).

**Comment by jasongrout** [comment]
We can override marked's rendering of images doing something like this: https://github.com/chjj/marked#overriding-renderer-methods.

**Comment by jasongrout** [comment]
As a more robust solution, we can register a per-notebook markdown renderer with the notebook's Rendermime (just like the ipywidgets labextension registers a per-notebook widget renderer). We should provide a function that would resolve any relative document URL in the application to a real URL you could fetch from. The per-notebook markdown renderer would know the path of the notebook, and translate relative URLs to real URLs you could fetch.

**Comment by fperez** [comment]
Ah, to be honest, I hadn't noticed that this problem was also present in notebooks, I saw it only on the markdown files and thought it was specific to that path.

Now that I see it's also present in the notebook, I'm bumping priority to 0.90.  Having images rendered is so fundamental to the notebook that we can't really call it basic feature parity without that...

I'll update the description above too.

**Comment by fperez** [comment]
Oops, never mind, the above applies to #425, not this one. Sorry, will make the changes there.

**Comment by ellisonbg** [comment]
Also @blink1073 has added an activity monitor that we can use to do slightly more coarse grained updates to the model so even if there are jitters, they will be much less often. #445

**Comment by blink1073** [comment]
The relative path handling is done, a prudent use of the activity monitor will help as well.

**Comment by ellisonbg** [comment]
We are now using the activity monitor, closing this.
