### ISSUE TITLE
Menu-based way to rename files (text, notebooks)

### ISSUE THREAD

**Issue by fperez** [jupyter/jupyterlab#428]
Currently, file renaming is only available via the contextual menu in the file manager.  Most users will expect some form of "save as" or rename in the top menus (it took me a while to realize that the file manager could do this).

It's particularly important b/c the FM may move around in the file system a lot, while people may keep in their workspace open files and notebooks from multiple filesystem locations.  Having to re-navigate the FM back to each file's location just to rename it is awkward usability-wise.

**Comment by sccolbert** [comment]
In addition to this, we also plan to allow inline renaming by double clicking on the tab title.

**Comment by fperez** [comment]
Excellent, that would cover the pattern we have today of clicking on the name area in the top bar (which was inspired by Google Docs, and works fairly well).  Thanks!
