### ISSUE TITLE
Tooltip (help, tab completion) misplaced

### ISSUE THREAD

**Issue by jorisvandenbossche** [jupyter/jupyterlab#430]
Tooltip and completion are shown in the left top corner. To illustrate:

![jupyterlab-misplaced-tooltip](https://cloud.githubusercontent.com/assets/1020496/16897511/f29668cc-4bb3-11e6-8d44-c41ad2c1e062.PNG)

Windows 7, JupyterLab 0.1.1 (latest from conda-forge), Firefox 47

**Comment by jorisvandenbossche** [comment]
Tested it with chrome, and there is seems to work better, however, it is above the code line, while I would expect it be below. For example:

![jupyterlab-misplaced-tooltip-chrome](https://cloud.githubusercontent.com/assets/1020496/16897542/bbec245a-4bb4-11e6-884f-a17eab98f68c.PNG)

(in this case there is not enough room to show the full tooltip above, if the tooltip is brought up lower at the page it shows more entries)

**Comment by sccolbert** [comment]
Thanks for reporting this. Those sorts of screenshots really help us understand the issue!

**Comment by jorisvandenbossche** [comment]
And another one, to illustrate how annoying this is :-)

![jupyterlab-misplaced-tooltip2](https://cloud.githubusercontent.com/assets/1020496/16901454/650c3022-4c44-11e6-976d-c5728e25be91.PNG)

What I did in the console was:

```
import pandas as pd

pd.DataFrame
```

(my cursor was at the end). So because of the placement of the tooltip, it constantly covers your input text you are typing.

But related to the tooltips (but probably another issue), when I just type `pd` or `pd.`, I get the tooltip for the module docstring automatically shown, and therefore I don't see any completions (I first have to 'Esc' out of the tooltip, so pressing tabs shows the completions). (this is in the console, in the notebook I don't get the help tooltips)

**Comment by afshin** [comment]
#### Update
This issue is *half* resolved because the tooltip is no longer free floating: https://github.com/jupyter/jupyterlab/pull/494

The position of the completion widget still needs to be addressed and corrected.
