### ISSUE TITLE
Notebook help shortcuts not present

### ISSUE THREAD

**Issue by to266** [jupyter/jupyterlab#435]
The (maybe ipythons?) shortcut of shift+tab that show the docstring of the function under cursor in a floating window (and expanding the window with with double tap of this same combination) is not present.

When someone tackles this, I think it's also important to to make the text selectable so that it can be copy-pasted into the notebook.

**Comment by ellisonbg** [comment]
Working in master, although there is a discussion here #714 about how it all should work:

Closing as resolved and duplicate.
