### ISSUE TITLE
Mistake in documentation and/or npm issue

### ISSUE THREAD

**Issue by jdetle** [jupyter/jupyterlab#438]
Running Jupyterlab tells:
```
If you're working on the Javascript of the notebook, try running
    
        npm run build:watch
    
    in another terminal window to have the system incrementally
    watch and build the notebook's JavaScript for you, as you make changes.
```
However after running `npm run build:watch`:
``` 
npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/home/jdetlefs/local/bin/node" "/home/jdetlefs/local/bin/npm" "run" "build:watch"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3

npm ERR! missing script: build:watch
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```
This happens.

Looking in the package.json, it seems like npm run watch is the command that we want?

**Comment by sccolbert** [comment]
Yep `npm run watch` is the correct command. The docs are wrong.

**Comment by jdetle** [comment]
Cool I'll make a PR if you don't mind

**Comment by sccolbert** [comment]
It would be most welcome!

**Comment by jdetle** [comment]
It turns out this is a little more complicated than I initially thought. As far I can tell there are two options.

First option, change the name of the script in the `package.json` file for the lab. `watch` would then be `build:watch`, `watch:src` becomes `build:watch:src`, `watch:test` becomes `build:watch:test`.

Option two is to make a PR in the notebook to change the [dev note](https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L111). 

I think option one is better because it fits the naming in the original notebook. But please let me know what you think.

**Comment by sccolbert** [comment]
I'm okay with either, but maybe someone else has a stronger opinion.

cc @blink1073 @jasongrout @afshin

**Comment by blink1073** [comment]
I would prefer to update the dev note and leave the script names as-is.

**Comment by jasongrout** [comment]
+1 to changing the docs, and leaving it as `npm run watch`.

**Comment by jasongrout** [comment]
We just realized that this was printed out on the python side by the Jupyter notebook, and has nothing to do with JupyterLab. Can you add appropriate instructions in https://github.com/jupyter/jupyterlab/blob/master/jupyterlab/__init__.py#L51 instead, maybe telling people to ignore the Jupyter notebook instructions if you really mean to do stuff with JupyterLab?

**Comment by jdetle** [comment]
Of course!

**Comment by jdetle** [comment]
Oh! So understanding this further, this only happened because I had a developer install of the notebook!

**Comment by jasongrout** [comment]
Maybe, or maybe it prints out for every install of the notebook. Not sure...

**Comment by jdetle** [comment]
Installed on my desktop and I get this
```
[W 15:25:45.663 LabApp] Unrecognized JSON config file version, assuming version 1
[W 15:25:45.868 LabApp] Widgets are unavailable. Please install widgetsnbextension or ipywidgets 4.0
[I 15:25:45.875 LabApp] The port 8888 is already in use, trying another port.
[I 15:25:45.875 LabApp] The port 8889 is already in use, trying another port.
[I 15:25:45.880 LabApp] Pre-alpha version of JupyterLab extension loaded from /home/jdetlefs/github/jupyterlab/jupyterlab
[I 15:25:45.884 LabApp] Serving notebooks from local directory: /home/jdetlefs/github/jupyterlab
[I 15:25:45.884 LabApp] 0 active kernels 
[I 15:25:45.884 LabApp] The Jupyter Notebook is running at: http://localhost:8890/
[I 15:25:45.884 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Created new window in existing browser session.
[W 15:25:47.227 LabApp] 404 GET /favicon.ico (127.0.0.1) 23.78ms referer=http://localhost:8890/lab
```
when notebook version = 4.2.1

```
[W 15:30:25.378 LabApp] Unrecognized JSON config file version, assuming version 1
[I 15:30:25.387 LabApp] It looks like you're running the notebook from source.
    If you're working on the Javascript of the notebook, try running
    
        npm run build:watch
    
    in another terminal window to have the system incrementally
    watch and build the notebook's JavaScript for you, as you make changes.
    
[W 15:30:25.608 LabApp] Widgets are unavailable. Please install widgetsnbextension or ipywidgets 4.0
[I 15:30:25.614 LabApp] The port 8888 is already in use, trying another port.
[I 15:30:25.614 LabApp] The port 8889 is already in use, trying another port.
[I 15:30:25.620 LabApp] Pre-alpha version of JupyterLab extension loaded from /home/jdetlefs/github/jupyterlab/jupyterlab
[I 15:30:25.623 LabApp] Serving notebooks from local directory: /home/jdetlefs/github/jupyterlab
[I 15:30:25.623 LabApp] 0 active kernels 
[I 15:30:25.624 LabApp] The Jupyter Notebook is running at: http://localhost:8890/
[I 15:30:25.624 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Created new window in existing browser session.
```
when notebook=5.0.0.dev which makes total sense given the code.

**Comment by jasongrout** [comment]
Okay. So close this?
