### ISSUE TITLE
Empty browser

### ISSUE THREAD

**Issue by Feynman27** [jupyter/jupyterlab#439]
Hi,

I just installed jupyterlab using pip on Ubuntu 16.04. Everything appears to be fine, except when I attempt to open jupyterlab using `jupyter lab` from the terminal, I just get a blank gray screen on my browser at http://localhost:8888/lab. I'm using 

Python 2.7.12 |Anaconda 4.1.1 (64-bit)| (default, Jul  2 2016, 17:42:40) 
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

![screenshot from 2016-07-17 16-48-27](https://cloud.githubusercontent.com/assets/12432112/16903006/23976f4e-4c3f-11e6-9071-2a58e3a802de.png)

**Comment by drussellmrichie** [comment]
I'm not one of the developers, but this seems to be the same as #408? The fix suggested there seemed to work for some people (I'm still trying to get it to work, personally).

**Comment by jasongrout** [comment]
It looks like @Feynman27 got it working on #408. Thanks for posting the list of what worked for you!
