### ISSUE TITLE
Installation instructions not working: ImportError: serverextension

### ISSUE THREAD

**Issue by Cyberface** [jupyter/jupyterlab#440]
Hi guys!

I tried to install jupyterlab both from pip and the current master from yesterday following the
instructions in the readme.md.

Basically it failed for me at the last step where

`jupyter serverextension enable --py jupyterlab`

would return

`ImportError: serverextension`

Any ideas?

I am running macOSX 10.10.2 and python 2.7

Do I need to be on python 3 or update to the latest macOS ?

Thanks!

**Comment by blink1073** [comment]
It looks like you have a version of `jupyter notebook` older than 4.2, can you please try `pip install -U notebook`?

**Comment by Cyberface** [comment]
Ah thanks! I had a problem that `notebook` wasn't updating due to my virtualenv getting confused with $PYTHONPATH. Thanks! jupyterlab looks great!

**Comment by blink1073** [comment]
Awesome, thanks for the feedback!
