### ISSUE TITLE
Right clicking on filebrowser item should activate the item

### ISSUE THREAD

**Issue by sccolbert** [jupyter/jupyterlab#441]
In addition to opening the context menu, right clicking on an item in the file browser should *also* activate the item, as if it were left clicked.

**Comment by blink1073** [comment]
The behavior here differs between OSX and Windows.  On Windows, if you right click on a file that is already part of a selection, the selection stays the same.  If you right click on a different file, it becomes the only selected file.  On OSX, right clicking on an existing selection adds a border around the selection.  When you right click on a different file it adds a border around the new file, and the selection reverts back to the previous one after an action is taken.  Do we have a preference?  

<img width="528" alt="screen shot 2016-07-18 at 8 44 53 am" src="https://cloud.githubusercontent.com/assets/2096628/16916879/d2f4a256-4cc4-11e6-8a26-669681697685.png">

**Comment by sccolbert** [comment]
I prefer the Windows behavior (but at least the OSX behavior has *some* visual indicator), because our Menu widgets already follow the Windows behavior.

**Comment by blink1073** [comment]
The Windows behavior is easier to implement, I'll go with that ;).

**Comment by blink1073** [comment]
I was using the same concept of "soft selection" for drag-n-drop, but again the Windows behavior is less magical, if you drag something that is not selected, that item becomes the only selected item.

**Comment by sccolbert** [comment]
+1 for less magic

**Comment by blink1073** [comment]
👍  for more:

![magic](https://cloud.githubusercontent.com/assets/2096628/16920268/9689d2ce-4cd2-11e6-8988-e397e3213415.gif)

**Comment by ellisonbg** [comment]
I am fine with less magic in code as long as I can get a unicorn T-shirt and sparkles (+1 for the Windows model).
