### ISSUE TITLE
The leaflet map does not zoom to location if text version is also open.

### ISSUE THREAD

**Issue by sccolbert** [jupyter/jupyterlab#442]
This gif shows that when the editor view of the geojson file is open, opening the map view will not zoom to location. The only time the map auto-zooms appears to be when the text view is not also open.

![leafletissue](https://cloud.githubusercontent.com/assets/137289/16914998/dd699e62-4cba-11e6-8a97-fe4d37ea9d48.gif)

**Comment by blink1073** [comment]
My guess is that the widget is not taking into account initial state, which is already loaded when the editor is loaded first.

**Comment by jasongrout** [comment]
It does check for initial state. I think it's more subtle here. I'm going to be reworking the default widget checking because I noticed some other bugs while I was looking into this.
