### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by svenefftinge** [jupyter/jupyterlab#455]
I'd like to debug jupyterlab source code in chrome developer tools. But it doesn't show me the original typescript source, but only the generated js files. Am I doing something wrong?

(Is it ok to ask questions through issues, or is there a better channel?)

**Comment by blink1073** [comment]
Hi @svenefftinge, we are compiling the source to ES5 before WebPacking it, and using a single source-map step from WebPack back to the ES5 code.  AFAIK there is a way to link it again back to the original TypeScript source, we just have not done it yet.  There is a bug in the current version of Chrome that is forcing us to temporarily inline the source maps, which further complicates the issue.

**Comment by jasongrout** [comment]
@svenefftinge - this is a perfect place to ask questions. Thanks!

**Comment by jasongrout** [comment]
I opened #506 for tracking linking code back to the typescript sources.
