### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by restrepo** [jupyter/jupyterlab#456]
I nice feature of the notebook was that the URLs were available and easily linkable from the notebook   for files, terminals, etc.  In particular was easy to navigate through the three of directories by writing the proper URL. 

To illustrate the problems please check this notebook with several link in the first cells which are now broken:

https://github.com/restrepo/BSM-Toolbox/blob/master/index_bash.ipynb

Thanks in advance

**Comment by sccolbert** [comment]
Having a nice story around persisten component URLs is definitely on our roadmap, it's just not something we've gotten to yet. As you can imagine things like this become much complicated in our multi-paneled layout system, so there's lots to talk about around this.

**Comment by jasongrout** [comment]
@minrk had some discussion about this the other day. I'll transcribe my notes in an issue.

**Comment by ellisonbg** [comment]
Duplicate of #1442
