### ISSUE TITLE
OutputAreaWidget `mirror` getter should be a method

### ISSUE THREAD

**Issue by sccolbert** [jupyter/jupyterlab#458]
This getter should be converted to a method, since it creates a new thing:
https://github.com/jupyter/jupyterlab/blob/master/src/notebook/output-area/widget.ts#L150

Getters should be reserved for non-allocating "cheap" things. Basically, one expects the condition `foo.thing === foo.thing` to hold for most use cases.

cc @danielballan @blink1073

**Comment by willingc** [comment]
Thanks @danielballan. Great addition.
