### ISSUE TITLE
Output renderers adding other mime types to the bundle

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyterlab#467]
@ellisonbg brought up some use cases of having notebook output renderers actually modify the output model content. For example, a javascript plotting renderer might want to save a png representation.

Currently, it looks like the renderer receives a *copy* of the actual output model: (https://github.com/jupyter/jupyterlab/blob/ee3d32bb94fd401512952502abafea4aeef6c453/src/notebook/output-area/widget.ts#L695 calls convertBundle, which returns a copy: https://github.com/jupyter/jupyterlab/blob/ee3d32bb94fd401512952502abafea4aeef6c453/src/notebook/output-area/widget.ts#L806).

@fperez brought up that the architecture (messages, protocols, etc.) were written with the idea that the kernel would be the one generating the output that was saved into the notebook. Having the front end modify the output model may require deeper changes to the architecture.

**Comment by fperez** [comment]
Most of my concern was about documenting and making explicit this: if we go down this road, we want to explain how our information flow model has changed.  And this may affect other clients as well: we're at the point where we need to start thinking of the impact that changes to the relationship between the protocol that clients honor and the creation of documents (the notebook files) can impact other clients that manipulate notebooks.

**Comment by ellisonbg** [comment]
Talked to @blink1073 today about this:

* The `RenderMime` API will take a callback that gets passed down to the `Renderer` on a per output basis.
* That callback will allow a Renderer to add other outputs to the current one.
* The notebook API will pass a callback that is a closure around the current output and modify it in place.
* We will have to add an API to allow outputs to be modified in place.

**Comment by jasongrout** [comment]
> That callback will allow a Renderer to add other outputs to the current one.

I thought in our discussions on Friday that we were talking about adding mimetypes to the current output mimebundle, not adding new outputs.

**Comment by blink1073** [comment]
Correct, which is what I implemented in #952.

**Comment by jasongrout** [comment]
> Correct, which is what I implemented in #952.

Great!
