### ISSUE TITLE
Scroll left-right in notebook output

### ISSUE THREAD

**Issue by drussellmrichie** [jupyter/jupyterlab#471]
Sometimes notebook output will be too wide to fit within the size of the tab. For example, right now I've got a pandas dataframe with a bunch of columns with long names, and it's printing off the right edge of the notebook tab, which I currently have maximized within Jupyter Lab.

![](http://i.imgur.com/v36pXO4.png)

In Pineapple and the browser-based Jupyter Notebook editor, you can scroll left and right to view such horizontally-oversized output. Can the same be done in Jupyter Lab?

**Comment by jasongrout** [comment]
Definitely!

**Comment by thenx** [comment]
Looks like it's back. Worked correctly before but after updating (v0.17.5) cannot scroll left-right wide dataframes.

**Comment by jasongrout** [comment]
Can you open a new issue, and reference this issue?

**Comment by blink1073** [comment]
This was fixed in https://github.com/jupyterlab/jupyterlab/pull/1885, but not yet released.  The next release is coming soon: https://github.com/jupyterlab/jupyterlab/issues/1919.

**Comment by thenx** [comment]
Great, thanks!

**Comment by thenx** [comment]
Switched to 0.18.0. Still an issue.
