### ISSUE TITLE
Add a file import preference settings or a file import wizard

### ISSUE THREAD

**Issue by fran6w** [jupyter/jupyterlab#472]
Importing CSV file with fields separated by semi-columns ";" instead of columns "," doesn't work properly.
Best,
Francis

**Comment by jasongrout** [comment]
Do you mean this happens in the csv file viewer (i.e., double-clicking on the csv file, or right clicking and opening with the table widget)?

If yes, I agree that the it would be convenient if that window displaying the file had a text box or drop down to change the delimiter.

**Comment by fran6w** [comment]
Open With... Table provides a single column table with all fields concatenated since the semi-column ";" separator is not recognized.

**Comment by jasongrout** [comment]
Okay, sounds like we are on the same page. +1 to having a smarter display widget that lets you choose semicolons or other delimiters.

**Comment by jasongrout** [comment]
Do you want to try doing this? The code is in https://github.com/jupyter/jupyterlab/blob/master/src/csvwidget/widget.ts#L35. I'm thinking it would be good to add a small dropdown above the csv file so you could choose the separator from some common choices, or maybe a text box in case those choices aren't enough. When a new separator was selected, the renderTable method (https://github.com/jupyter/jupyterlab/blob/master/src/csvwidget/widget.ts#L86) would use the separator as an argument to the d3-dsv package to parse the file.

**Comment by fran6w** [comment]
Dear Jason,
Thank you for your effort.
Unfortunately I could not find any "widget.ts" file on my computer.
Where should I put the modified file in order to try the fix?
Best,
Francis

**Comment by jasongrout** [comment]
Thanks for looking into this! You'll need to install the JupyterLab dev version, following these instructions: https://github.com/jupyter/jupyterlab#contributing-to-jupyterlab

**Comment by jasongrout** [comment]
(Have you used git before?)

**Comment by fran6w** [comment]
A little, I am on Windows and I use either GitHub.com or GitHub desktop

**Comment by fran6w** [comment]
I followed the instructions:

1) the first one provides a display with a never ending loop:
> npm install
npm WARN package.json Dependency 'file-loader' exists in both dependencies and devDependencies, using 'file-loader@^0.8.5' from dependencies
/

2) the second one never finishes:
>pip install -e .
Obtaining file:///C:/Users/Francis/Documents/GitHub/jupyterlab

3) the third one seems to be OK:
>jupyter serverextension enable --py
 jupyterlab
Enabling: jupyterlab
- Writing config: C:\Users\Francis\.jupyter
    - Validating...
      jupyterlab  ok

4) the last one provides an empty HTML page:
>jupyter lab
[W 16:40:17.430 LabApp] Unrecognized JSON config file version, assuming version
1
[W 16:40:17.430 LabApp] Unrecognized JSON config file version, assuming version
1
C:\Anaconda3\lib\site-packages\widgetsnbextension\__init__.py:30: UserWarning: T
o use the jupyter-js-widgets nbextension, you'll need to update
    the Jupyter notebook to version 4.2 or later.
  the Jupyter notebook to version 4.2 or later.""")
[I 16:40:18.023 LabApp] It looks like you're running JupyterLab from source.
    If you're working on the TypeScript sources of JupyterLab, try running

        npm run watch

    from the JupyterLab repo directory in another terminal window to have the sy
stem
    incrementally watch and build JupyterLab's TypeScript for you, as you make
    changes.

[I 16:40:18.023 LabApp] JupyterLab alpha preview extension loaded from C:\Users\
Francis\Documents\GitHub\jupyterlab\jupyterlab
[I 16:40:18.038 LabApp] Serving notebooks from local directory: C:\Users\Francis
\Documents\GitHub\jupyterlab
[I 16:40:18.038 LabApp] 0 active kernels
[I 16:40:18.038 LabApp] The Jupyter Notebook is running at: http://localhost:888
8/
[I 16:40:18.038 LabApp] Use Control-C to stop this server and shut down all kern
els (twice to skip confirmation).
[W 16:40:18.701 LabApp] 404 GET /lab/bundle.js (::1) 77.00ms referer=http://loca
lhost:8888/lab

**Comment by jasongrout** [comment]
> the first one provides a display with a never ending loop

Thanks - hopefully fixed in https://github.com/jupyter/jupyterlab/pull/498.

> the second one never finishes:

This will probably be a problem, if it's not finishing.

I'll try replicating this on Windows. It may help if you uninstall jupyterlab first (did you install using conda or pip?)

**Comment by fran6w** [comment]
I installed it through conda but I had to install some lacking modules manually: pycosat and jsonschema.

**Comment by jasongrout** [comment]
If you have the notebook 4.2 package installed, jupyterlab shouldn't require any extra dependencies. Regardless, I'd suggest uninstalling from conda before installing the dev version.

**Comment by AbdealiJK** [comment]
Hey, Can I be assigned to this ? Would like to try it out.

**Comment by jasongrout** [comment]
Sounds great! It seems like it has stalled. I think it'd be a great idea to take it up.
