### ISSUE TITLE
focusing a cell by clicking scrolls to the bottom of the cell

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyterlab#478]
If you make the output of the cell longer than a page, then this becomes frustrating, since the input scrolls away, even if you are editing the cell. This happens in chrome and firefox for me on OS X.

![focus](https://cloud.githubusercontent.com/assets/192614/16988283/e6be24f2-4e5d-11e6-9b4f-8ba3a7b8af68.gif)

**Comment by jasongrout** [comment]
See https://github.com/phosphorjs/phosphor/issues/125 - I think we should probably move to using the browser's scrollIntoView.

**Comment by sccolbert** [comment]
`scrollIntoView` will *always* scroll AFAIU. It seems you are calling `scrollIfNeeded` on the parent node, which is the full tall container. It's not looking for the thing with focus.

**Comment by sccolbert** [comment]
Working on a fix: https://github.com/phosphorjs/phosphor/pull/126

**Comment by jasongrout** [comment]
@sccolbert is right that we are scrolling inappropriately here. In fact, I don't think we should be scrolling *at all* if the active cell was changed by a mouse click. And in the case of moving from command to edit mode, I agree with Chris that we should be scrolling the input element, not the cell.

**Comment by jasongrout** [comment]
To clarify, in the case of a mouse click focusing the cell, if the mouse click was in the input area, then we shouldn't change the position of the cursor in the viewport just to get more of the input area in view. We also have problems with clicking on interactive output (like a widget slider) making the cell active and then scrolling the point of interest away from the mouse.
