### ISSUE TITLE
Add a 'Save as' option

### ISSUE THREAD

**Issue by eskirk** [jupyter/jupyterlab#482]
A lot of users have been looking for some form of 'save as' button in user testing, and it makes sense to be able to save with a name (as opposed to `UntitledX.ipynb`)

**Comment by eskirk** [comment]
Apparently we already have a function that does exactly this. I guess all that needs to be done is to open a dialog window that allows you to enter in a name. I can get on this. 

https://github.com/jupyter/jupyterlab/blob/52f04a02e6cc33f6edf36b6ac3ae118aa02b873f/src/docmanager/context.ts#L178

**Comment by profjsb** [comment]
+1 for this on the notebook ... and for a "Save As..." on the Editor.
