### ISSUE TITLE
Terminal and Console should open in the current working directory

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyterlab#483]
Should the console and terminal (as launched from the launcher, top-level menu, or commands) launch in the current working directory defined by the file browser? The console may be talking to a kernel on a remote server, with no notion of the current directory served up to the file browser

**Comment by blink1073** [comment]
Sessions are launched *in the cwd* of the given file, which is the currwnt behavior of notebooks.  We can get that in the console by using the cwd in the path and adding a fake file name.  I'm not sure if cwd is handled by the server in the case of terminals (I'm on my phone).

**Comment by jasongrout** [comment]
Thanks for the clarifications.

**Comment by jasongrout** [comment]
hmmm, so if I have two notebooks in different directories hooked up to the same kernel, the first one wins... Interesting UI question there about how to clearly convey to the user that the kernel's directory may not be the same as the notebook's directory.

**Comment by blink1073** [comment]
Terminado *does* support a `cwd` parameter, but we are not handling it at the server level.  It would require adding to the server model for a terminal, which is currently just its "name".

**Comment by blink1073** [comment]
We now have the ability to launch consoles in the existing directory per #750.  The classic notebook always launches terminals in the base directory of the server.  It would require a server level change to enable the behavior.  Closing in favor of #782.
