### ISSUE TITLE
Add method to expose inputNode

### ISSUE THREAD

**Issue by spoorthyv** [jupyter/jupyterlab#484]
I am trying to add placeholder text to the searchbar and to do so I need access to the inputNode. According to @afshin, we need to add a method to phosphide to expose it.

@blink1073 @afshin @sccolbert @jasongrout

**Comment by sccolbert** [comment]
Which input node is this concerning?

**Comment by spoorthyv** [comment]
I think, its in app.palette

**Comment by sccolbert** [comment]
The new mono-repo exposes the `inputNode`:
https://github.com/phosphorjs/phosphor/blob/master/src/ui/commandpalette.ts#L164

What placeholder text are you wanting to set? It may make sense to make it the default behavior.

In the meantime, you can get at that node using a simple document query:
`let inputNode = document.body.querySelector('.p-CommandPalette-input');`

**Comment by spoorthyv** [comment]
I want to set the placeholder text for the search bar in the command palette.

**Comment by sccolbert** [comment]
@spoorthyv I meant what is the specific string, e.g. `"this is my placeholder text" that you want to set?

Also, see the last paragraph of my second comment for a temporary workaround.

**Comment by spoorthyv** [comment]
I want the search bar to look like this.
![group 2](https://cloud.githubusercontent.com/assets/12418068/17003882/ec047992-4e86-11e6-8cb7-92459927f1ff.png)

**Comment by spoorthyv** [comment]
Whoops I guess I closed the issue on accident.

**Comment by sccolbert** [comment]
Okay. I already showed how to get a handle to the node as a temporary workaround. All you need to do now is set the placeholder text. 

"SEARCH" is a reasonable default  text. I'll can add that to the mono-repo as well.

**Comment by spoorthyv** [comment]
I used this code in main > plugin.ts:
`inputNode = document.body.querySelector('.p-CommandPalette-input') as HTMLInputElement;
inputNode.placeholder = "SEARCH";`

But then it kind of broke everything. I got a `plugin.js:16 Uncaught (in promise) TypeError: Cannot set property 'placeholder' of null` in console.

**Comment by sccolbert** [comment]
The query will return `null` until the command palette is attached to the DOM.

**Comment by spoorthyv** [comment]
How would I make sure that its not null?

**Comment by spoorthyv** [comment]
Should I just use the onAfterAttach method of a random widget?

**Comment by jasongrout** [comment]
A random widget may be added before the command palette. As a hack, for now, you could poll until you find it (i.e., look for it, and if you don't find it, schedule the function to run again in maybe 300 milliseconds using `setTimeout`...)

**Comment by blink1073** [comment]
Fixed by #627.
