### ISSUE TITLE
New JL terminals don't source `.bashrc`.

### ISSUE THREAD

**Issue by cryptarch** [jupyter/jupyterlab#489]
Hey there,

Thanks for your great work on JupyterLab, it looks like it will be a really useful environment.

I have noticed a small number of problems. The first is that when opening a new terminal in JupyterLab, it won't re-source the `.bashrc` to take into account recent modifications.

**Expected behaviour**: each time I open a new JupyterLab terminal, it should source `.bashrc`.

**Actual behaviour**: new terminals continue to use the same `.bashrc` that existed when JupyterLab was started.

**Steps to reproduce**: Start JupyterLab. Open `~/.bashrc` in a text editor. Change the `$PS1` definition so it has different colours to before. Open a new terminal in JupyterLab. Observe lack of new PS1 colours.

Let me know if any more information is required.

**Comment by jasongrout** [comment]
This sounds like it might be an issue with the underlying library the Jupyter Notebook uses to spawn terminals, Terminado. Maybe this file specifically? https://github.com/takluyver/terminado/blob/master/terminado/management.py

@takluyver - you're the expert on this. What do you think?

**Comment by takluyver** [comment]
It's sourcing bashrc for me in the regular notebook; no idea why it would be different in Jupyterlab.

**Comment by jasongrout** [comment]
Thanks. I'll see if I can replicate it in JLab.

**Comment by jasongrout** [comment]
This works as @takluyver describes for me in JupyterLab. @cryptarch - is this still happening for you? If so, can you give us more info:

- do you notice the same problem in the Jupyter notebook?
- What version of the Jupyter notebook and JupyterLab do you have?

**Comment by cryptarch** [comment]
Hi @jasongrout @takluyver,

> do you notice the same problem in the Jupyter notebook?

To be clear on definitions, do you mean the tab that opens when I click on the Notebook icon in the JLab Launcher?

I can still produce this problem in the JLab Terminal. It is not clear to me what I should test to see whether the Notebook is also affected.


> What version of the Jupyter notebook and JupyterLab do you have?

~~~{.sh}
# pip freeze | grep jup
jupyter==1.0.0
jupyter-client==4.3.0
jupyter-console==5.0.0
jupyter-core==4.1.1
jupyterlab==0.2.0
~~~

**Comment by jasongrout** [comment]
> To be clear on definitions, do you mean the tab that opens when I click on the Notebook icon in the JLab Launcher?

No, I mean launching the current Jupyter notebook with `jupyter notebook`. It sounds like the problem is not about JupyterLab, but about something dealing with the notebook server (which is the same for the current notebook).

For me, I also realized that I was actually running zsh, so modifying .bashrc didn't do anything :).

**Comment by blink1073** [comment]
My `.bashrc` is working on `master`.  I am using OSX 10.11.6.  @cryptarch, can you please check your `terminado` version?

```
$ pip freeze | grep term
backports.shutil-get-terminal-size==1.0.0
iterm2-tools==2.2
terminado==0.6
XStatic-term.js==0.0.4.2
```

**Comment by cryptarch** [comment]
Hey @blink1073,

> can you please check your terminado version?

~~~{.sh}
$ pip freeze | grep term
terminado==0.6
~~~

> My .bashrc is working on master.

I think there has been a misunderstanding. I am not saying the `.bashrc` is not getting sourced at all. Indeed, my `.bashrc` *is* getting sourced when JLab starts. The problem is that if I *change* the `.bashrc`, new JLab Terminals within the current JLab instance do not reflect the change.

This won't usually be an issue when there is just one person using JLab on just the one computer, since their personal `.bashrc` will not change often. However, our group hopes to offer JLab via docker containers to a wide variety of researchers and students around our university.

Some of them will be content with the default `.bashrc`. However, if any of them are already a bit savvy and want to, say, customise their `PS1`, at the moment the only option seems to be to restart JLab.

**Comment by cryptarch** [comment]
Hey @jasongrout,

> No, I mean launching the current Jupyter notebook with jupyter notebook.

I don't believe this is possible within our current docker container setup which (as I understand it) only offers JLab as a web service. It doesn't have its own X11; when I try running `jupyter notebook` anyway it complains about not finding a browser.

On my _local_ machine, Terminals opened from jupyter notebook seem to behave correctly. If I start the notebook, then change my `.bashrc`, new terminals do correctly source the changed `.bashrc`.

However, I am concerned this could be muddying the waters a bit, because my goal is to have things working properly in the containers; I am not particularly concerned about whether I have correct behaviour on my personal local machines.

**Comment by blink1073** [comment]
I should have been more clear.  I meant I was able to change my .bashrc, launch a new terminal from the JupyterLab launcher, and see the difference.

**Comment by cryptarch** [comment]
If it helps, the dockerfile these containers are built from is at https://github.com/dit4c/dockerfile-dit4c-container-jupyterlab/blob/master/Dockerfile

**Comment by jasongrout** [comment]
Can you check to see if this works as you expect when using the jupyter notebook (i.e., using `jupyter notebook`)? I strongly suspect the problem is not unique to jupyterlab here.

**Comment by jasongrout** [comment]
> I should have been more clear. I meant I was able to change my .bashrc, launch a new terminal from the JupyterLab launcher, and see the difference.

Same here (with .zshrc, of course). I changed it from within the JLab terminal, then launched a new terminal, and the changes were applied.

**Comment by jasongrout** [comment]
(an easy way to check it is to launch jupyterlab, and then just change the URL to `/tree` - and there is the jupyter notebook...)

**Comment by cryptarch** [comment]
> an easy way to check it is to launch jupyterlab, and then just change the URL to /tree - and there is the jupyter notebook...

No worries, I will try this out later today (Eastern Australia time).

**Comment by jasongrout** [comment]
> Eastern Australia time

Lucky!

**Comment by tjdett** [comment]
@jasongrout Perhaps I can shed some light on this, given I'm the author of the container @cryptarch is using. It starts JupyterLab with the following config:
https://github.com/dit4c/dockerfile-dit4c-container-jupyterlab/blob/master/etc/supervisord.d/jupyterlab.conf

As you can see, that means JupyterLab is being started from a login shell:
`bash -l -c "/opt/python/bin/jupyter lab --no-browser"`

This is because supervisord is the PID 1 in the container, and it launches JL as a non-privileged user. I believe this to be the most correct behaviour, but I'm happy to be corrected.

**Comment by cryptarch** [comment]
@jasongrout: Okay, I have tried opening terminals from the notebook under `/tree` as you suggested. These also exhibit the same behaviour as terminals opened from the Lab, i.e. new terminals fail to reflect changes in `.bashrc`.

**Comment by jasongrout** [comment]
> @jasongrout Perhaps I can shed some light on this, given I'm the author of the container @cryptarch is using. It starts JupyterLab with the following config:
> https://github.com/dit4c/dockerfile-dit4c-container-jupyterlab/blob/master/etc/supervisord.d/jupyterlab.conf
> 
> As you can see, that means JupyterLab is being started from a login shell:
> bash -l -c "/opt/python/bin/jupyter lab --no-browser"

CC @takluyver - from the above comment (https://github.com/jupyter/jupyterlab/issues/489#issuecomment-242258976), it appears the issue is not unique to JupyterLab, but that the current notebook also has the problem. Any suggestions? Is there a more appropriate place for this issue (the current notebook repo, or terminado, or somewhere else?)

**Comment by takluyver** [comment]
Check the $SHELL environment variable. That's what specifies the shell to run if it's set, and if it's not set, it defaults to `sh`, **not** `bash`.

**Comment by ellisonbg** [comment]
@cryptarch did that fix it?

**Comment by cryptarch** [comment]
@ellisonbg: Sorry for the delay, I had one more test to run :) The answer is yes, it appears to be fixed now by specifying `SHELL=/bin/bash` when starting JLab.

Thanks everyone for the help!

**Comment by jasongrout** [comment]
Great!
