### ISSUE TITLE
HTML embedded elements not behaving correctly

### ISSUE THREAD

**Issue by eskirk** [jupyter/jupyterlab#49]
![screen shot 2016-06-13 at 2 52 35 pm](https://cloud.githubusercontent.com/assets/7052378/16024367/54d49dfe-3176-11e6-94b3-412743107465.png)

The above image is from the current Jupyterlab build, the below image is from the current Jupyternotebook build. Each of these cells have an html element linking to an image 

![screen shot 2016-06-13 at 2 53 05 pm](https://cloud.githubusercontent.com/assets/7052378/16024366/54d3654c-3176-11e6-888f-10668fc6b9a5.png)

Only the Jupyternotebook interprets HTML correctly, Jupyterlab is still a little behind in that regard. 

This is not exclusive to *img* elements, but *a href* don't display their link either, leading me to believe there is something wrong with HTML support as a whole.

**Comment by sccolbert** [comment]
Does the dev tools inspector show that the `<img>` element is present in the lab-rendered notebook? I wonder if this has to do with the browser blocking the request for the src url for some reason.

**Comment by sccolbert** [comment]
In the same vein, do you see an messages in the browser console related to the image url?

**Comment by eskirk** [comment]
When I inspect the element I do see a "<img>" element in there, but when I hover over it doesn't highlight anything

**Comment by jasongrout** [comment]
This appears to be from the aggressive sanitation we do. We're discussing how to lighten up on some of the sanitation if you have trusted notebooks in #74.

**Comment by ellisonbg** [comment]
@eskirk could you test to see if this is resolved?

**Comment by eskirk** [comment]
![screen shot 2016-09-08 at 11 58 45 am](https://cloud.githubusercontent.com/assets/7052378/18362682/a00c065c-75bb-11e6-8aa7-686989f4ab99.png)

@ellisonbg seems all good on my end, this issue seems fixed. Closing.
