### ISSUE TITLE
Rename "Console" to "Code Console"

### ISSUE THREAD

**Issue by cryptarch** [jupyter/jupyterlab#490]
## Current summary

We are proposing to rename "Console" to "Code Console" to better differentiate it from the terminal. This should be done across both the UI and the different parts of the code.

## Original comment

Hey there,

I've been testing out JupyterLab, and amongst some other minor issues have noticed that the Launcher tab entries are a little unclear. In particular, it seems to still be set up with the assumption that people will be using iPython. This is probably not ideal given that Jupyter lab is intended to be extensible. I refer to the following screenshot:

![jl-launcher](https://cloud.githubusercontent.com/assets/1596765/17011307/eae0f454-4f4f-11e6-99ad-a20174fd1ae9.png)

In the Launcher, notice how there is a choice between terminal and console. Since the two words are more or less synonymous, I had to open up the console to realise that the entry is really for an iPython console. You might think this is obvious, but I've never really used iPython much, so it definitely wasn't obvious to me :)

To make it clearer the difference between the terminal and the console, and also to cater for scenarios where people will be using R, Julia, etc instead of Python, I propose that "Console" be changed to "iPython Console"; likewise, "Notebook" should say "iPython Notebook".

**Comment by sccolbert** [comment]
@afshin will correct me if I'm wrong, but both of those activities will start up with the default kernel on your system, which is configurable. The kernel for the notebook/console can also be switched once open, provided you have other kernels installed on the host.

**Comment by sccolbert** [comment]
But you're right, this should be made clear(er) for new users. Maybe a blurb in the tour.

**Comment by jasongrout** [comment]
Maybe we should also offer a dropdown there for the different kernels?

The "Console" and "Notebook" definitely don't rely on having IPython kernels, but are generic.

**Comment by jasongrout** [comment]
> amongst some other minor issues

Please file these too. We really appreciate feedback!

**Comment by cryptarch** [comment]
> Please file these too. We really appreciate feedback!

Thanks, working on it :)

**Comment by cryptarch** [comment]
> @afshin will correct me if I'm wrong, but both of those activities will start up with the default kernel on > your system, which is configurable. The kernel for the notebook/console can also be switched once > open, provided you have other kernels installed on the host.

> The "Console" and "Notebook" definitely don't rely on having IPython kernels, but are generic.

Ah, I see. The environment I'm using was pre-built by someone else, who asked me to test it for them. When I said the Launcher was a bit confusing for n00bz, they suggested I raise it here as an issue :)

I agree it is probably just a minor issue, but on the other hand do think it would be clearer for others in the same situation to have more explicit wording.

**Comment by jasongrout** [comment]
In the menu we explicitly substitute in the kernel name: "New Python 3 Console", "New Python 3 Notebook". Perhaps we can do that? Design-wise, if the kernel has a long name, that would mess up the spacing, but it would be clearer. Of course, the obvious next question would be how to launch other consoles/notebooks.

**Comment by ellisonbg** [comment]
Yeah, I agree that "Console" and "Terminal" mean pretty much the same thing to many people. We probably need to come up with a better name for the console. Ideas?

* "Code console"
* "Code shell"
* ...

**Comment by afshin** [comment]
Now that we are moving toward the idea of a console that connects to a session and renders the outputs of a session even if they were not executed in the console (*i.e.*, you see your notebook's outputs in a console and you can use the console itself almost as a scratch pad, or a view into what your colleague is doing ... we definitely should consider other terminology.

When you attach to another session, sometimes that kind of functionality is called "spying" or "inspecting". We're already using the term "inspector", but we may want to change that nomenclature to "debugger" or something. Just some thoughts.

**Comment by ellisonbg** [comment]
@afshin I am not following what you mean by "connects to a session...see your notebook's output" in a console). By default consoles get their own kernel, right? I know we want documents to be able to connect to other documents/console's kernels, but in general notebooks and consoles have independent lives from each other. Trying to understand how that relates to what we call consoles in general...

**Comment by jasongrout** [comment]
@ellisonbg - see https://github.com/jupyter/jupyterlab/issues/626 for relevant discussion on this role of consoles. But I also agree with you that in general, consoles and notebooks have independent and separate roles.

**Comment by ellisonbg** [comment]
Ahh, now I totally understand! Just posted over on #626  tldr - I agree with the idea over there.

In term of naming, I think that "Code Console" is probably my favorite name for the Console. Or maybe just "Code" for short.

**Comment by jasongrout** [comment]
Not code - that's too confusing with a code file, and conveys something that is pretty static for me.

**Comment by ellisonbg** [comment]
@rnetro any update on this one?

**Comment by rnetro** [comment]
@ellisonbg, currently working on this one
