### ISSUE TITLE
Unclear menu when switching between tabs

### ISSUE THREAD

**Issue by cryptarch** [jupyter/jupyterlab#493]
Hey there,

I filed some other issue reports today, but I think this is the last one :)

With this current issue, it is a bit hard for me to put my finger on what the correct behaviour _should_ be, but I find it confusing that the top JupyterLab menu remains the same no matter what type of tab is currently active.

For example, the menu at the top always offers "Save Document" regardless of the tab, but it isn't clear what this means in the context of the Launcher or Terminal tabs.

Screenshots: 
![jl-screenshots](https://cloud.githubusercontent.com/assets/1596765/17012883/1a1f7872-4f5e-11e6-9108-79b444b90a03.png)

It would probably be clearer if there were two separate menus, one for JupyterLabs overall, and another menu integrated into each tab, specifically for that tab. That way when I've got two different text documents open for editing, Save Document will obviously mean the current text file, and then Save Document will not be available for the Launcher, etc.

Thanks for your patience with me raising all these issues and keep up the good work :)

**Comment by blink1073** [comment]
Hi @cryptarch, the ability to have multiple tabs open of different types muddies the water of what the "current activity" should be.  For instance, if you are in a notebook, but then switch over to a terminal, the current thought is that you should still be able to run a command against the most recently active notebook.

**Comment by cryptarch** [comment]
Hey @blink1073, thanks for your response.

> the ability to have multiple tabs open of different types muddies the water of what the "current activity" should be.

Sorry if I misunderstand you, but if having multiple types of tabs open "muddies the water", then wouldn't it make sense to disable having more than one type of tab open at a time? At the moment, there is nothing at all to indicate that opening multiple types of tabs is frowned upon.

> For instance, if you are in a notebook, but then switch over to a terminal, the current thought is that you should still be able to run a command against the most recently active notebook.

This seems reasonable, but I'm still confused about what "Save Document" means when I'm in a terminal or console ;)

**Comment by jasongrout** [comment]
> Sorry if I misunderstand you, but if having multiple types of tabs open "muddies the water", then wouldn't it make sense to disable having more than one type of tab open at a time? At the moment, there is nothing at all to indicate that opening multiple types of tabs is frowned upon.

We definitely want people to have multiple kinds of tabs open. It's just that we need to think seriously about the UI issues to avoid confusion (as you point out above). Your suggestion of top-level and tab-level menus is one of doing that---we really appreciate the idea. Perhaps we could have top-level menus that change depending on the current activity. Perhaps we could make the top-level toolbar very generic and move to using curated command palettes instead that change depending on the activity.

I've also been confused by the top-level menu and what the action would apply to. Thanks for also voicing this and sharing a suggestion.

**Comment by blink1073** [comment]
^ What Jason said.  :smile:

**Comment by cryptarch** [comment]
Thanks @jasongrout :) If you have shared my confusion it makes me feel better that I wasn't just being thick-headed :D

**Comment by sccolbert** [comment]
@cryptarch you're not being thick headed at all. This is a very difficult UX nut to crack :) The topic as been in discussion amongst us for a long while now. What's there now is "something", which is better than "nothing". We fully expect that part of the system to change quite a bit going forward. We just haven't yet converged on what the "right" solution is. We're fielding all serious ideas at this point.

**Comment by ellisonbg** [comment]
I have opened #762 to track the larger design questions about how menus work. I am going to close this issue. Could you look over my proposal on that issue and provide feedback there? Thanks@
