### ISSUE TITLE
Handle interactive kernel responses in output area

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyterlab#495]
Executing inputs that don't immediately return a result (like invoking the help() functionality) require the output area to support handling input_request messages.

This is a general problem for both the notebook and the console. In order to see the problem manifest, at a console prompt, entering and executing the command help() will cause the kernel to pause while it waits for user input. The kernel will remain unusable from that point forward.

migrated from https://github.com/jupyter-attic/jupyter-js-notebook/issues/227

**Comment by jasongrout** [comment]
As another test, just do `input('name: ')` (on python 3) or `raw_input('name: ')` (python2).

Also, this is how `%pdb` works - requiring input.
