### ISSUE TITLE
Selecting a group heading in the command palette gives no visual indication

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyterlab#508]
In the command palette, use the up/down arrow keys to select a group heading - there is no visual indication that anything is selected. Pressing enter on a group heading does filter/unfilter the group, so it's important to give visual indication when a group heading is selected.

**Comment by sccolbert** [comment]
Sounds like a CSS oversite.

**Comment by jasongrout** [comment]
Yep

**Comment by eskirk** [comment]
#539
