### ISSUE TITLE
(soft) line wrapping in text editor not working

### ISSUE THREAD

**Issue by fperez** [jupyter/jupyterlab#510]
Title says it all... It makes it basically impossible to edit files that may have been created without hard `\n` breaks, as is often the case from folks who edit with line-wrapping editors.

**Comment by jasongrout** [comment]
Well we definitely don't want it on *always*, but have an option for it. The Editor menu has a settings entry that indicates it will turn on and off line wrapping, but doesn't seem to work (is that what you are saying about it "not working"?). 

I think the editor itself should have a small toolbar that has buttons or indicators for things like that, syntax highlighting settings, etc. I'll make an issue for that.

And then when we get a real settings system, we should be able to set defaults about these settings on a per-file-type basis.

**Comment by jasongrout** [comment]
cf. #511 and #512.

**Comment by jasongrout** [comment]
Setting to "Needs discussion" because I think it would be better UX to implement #511 (per editor settings toolbar) or #512 (global status area that changes when switching documents).

**Comment by jasongrout** [comment]
Actually, I fixed this in #513, and we can have the discussion on #511 or #512.

**Comment by jasongrout** [comment]
(By the way, #514 makes some of these settings per-editor settings, rather than global settings)

**Comment by fperez** [comment]
yes, that's what I mean by "not working". I tried the toggle and it didn't do anything, leaving me with a huge horizontal scroll bar. I had to switch to vscode to edit b/c of this...
