### ISSUE TITLE
Make the default markdown editor the editor, not the renderer

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyterlab#521]
I'm not sure how to do this, actually. I think it makes sense to make the default renderer for markdown the editor, since likely people will be writing markdown files more than viewing them. However, our defaults system automatically puts things registered for .md files above the global editor default.

Thoughts?

**Comment by jasongrout** [comment]
CC @groutr, @blink1073 at least.

**Comment by blink1073** [comment]
I think the default `*` widget should take precedence over a widget that *can* open a file of a particular type.

**Comment by groutr** [comment]
It makes sense to me.  Out of sheer curiosity, is there a mechanism for a user to select a default viewer for a file type, like an "Always open with..." action?

**Comment by blink1073** [comment]
Not yet, that will require persistent settings.

**Comment by jasongrout** [comment]
> I think the default * widget should take precedence over a widget that can open a file of a particular type.

Makes sense. See #521.
