### ISSUE TITLE
Jupyterlab build fails

### ISSUE THREAD

**Issue by fourpartswater** [jupyter/jupyterlab#524]
I get an installation failure building from git..  

> jupyterlab-extension@0.0.1 build:extension /data/work/git_repos/jupyterlab/jupyterlab
    > webpack --config webpack.conf.js
    
    ModuleNotFoundError: Module not found: Error: Cannot resolve module 'jupyterlab/lib/default-theme/index.css' in /data/work/git_repos/jupyterlab/jupyterlab
        at /data/work/git_repos/jupyterlab/jupyterlab/node_modules/webpack/lib/Compilation.js:229:38
        at onDoneResolving (/data/work/git_repos/jupyterlab/jupyterlab/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
        at /data/work/git_repos/jupyterlab/jupyterlab/node_modules/webpack/lib/NormalModuleFactory.js:85:20
        at /data/work/git_repos/jupyterlab/jupyterlab/node_modules/async/lib/async.js:726:13
        at /data/work/git_repos/jupyterlab/jupyterlab/node_modules/async/lib/async.js:52:16
        at done (/data/work/git_repos/jupyterlab/jupyterlab/node_modules/async/lib/async.js:241:17)
        at /data/work/git_repos/jupyterlab/jupyterlab/node_modules/async/lib/async.js:44:16
        at /data/work/git_repos/jupyterlab/jupyterlab/node_modules/async/lib/async.js:723:17
        at /data/work/git_repos/jupyterlab/jupyterlab/node_modules/async/lib/async.js:167:37
        at /data/work/git_repos/jupyterlab/jupyterlab/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
        at onResolved (/data/work/git_repos/jupyterlab/jupyterlab/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
        at innerCallback (/data/work/git_repos/jupyterlab/jupyterlab/node_modules/enhanced-resolve/lib/Resolver.js:94:11)
        at loggingCallbackWrapper (/data/work/git_repos/jupyterlab/jupyterlab/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
        at /data/work/git_repos/jupyterlab/jupyterlab/node_modules/tapable/lib/Tapable.js:134:6
        at /data/work/git_repos/jupyterlab/jupyterlab/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:54:23
        at /data/work/git_repos/jupyterlab/jupyterlab/node_modules/enhanced-resolve/lib/Resolver.js:191:15
        at /data/work/git_repos/jupyterlab/jupyterlab/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:45:26
        at loggingCallbackWrapper (/data/work/git_repos/jupyterlab/jupyterlab/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
        at /data/work/git_repos/jupyterlab/jupyterlab/node_modules/tapable/lib/Tapable.js:134:6
        at /data/work/git_repos/jupyterlab/jupyterlab/node_modules/enhanced-resolve/lib/Resolver.js:122:33
        at /data/work/git_repos/jupyterlab/jupyterlab/node_modules/enhanced-resolve/lib/Resolver.js:191:15
        at applyPluginsParallelBailResult.createInnerCallback.log (/data/work/git_repos/jupyterlab/jupyterlab/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
        at loggingCallbackWrapper (/data/work/git_repos/jupyterlab/jupyterlab/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
        at /data/work/git_repos/jupyterlab/jupyterlab/node_modules/tapable/lib/Tapable.js:134:6
        at Tapable.<anonymous> (/data/work/git_repos/jupyterlab/jupyterlab/node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin.js:24:12)
        at Storage.finished (/data/work/git_repos/jupyterlab/jupyterlab/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
        at ReadFileContext.callback (/data/work/git_repos/jupyterlab/jupyterlab/node_modules/graceful-fs/graceful-fs.js:78:16)
        at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
    resolve module jupyterlab/lib/default-theme/index.css in /data/work/git_repos/jupyterlab/jupyterlab
      looking for modules in /data/work/git_repos/jupyterlab/node_modules
        /data/work/git_repos/jupyterlab/node_modules/jupyterlab doesn't exist (module as directory)
      looking for modules in /data/work/git_repos/jupyterlab/jupyterlab/node_modules
        resolve 'file' or 'directory' lib/default-theme/index.css in /data/work/git_repos/jupyterlab/jupyterlab/node_modules/jupyterlab
          resolve file
            /data/work/git_repos/jupyterlab/jupyterlab/node_modules/jupyterlab/lib/default-theme/index.css doesn't exist
            /data/work/git_repos/jupyterlab/jupyterlab/node_modules/jupyterlab/lib/default-theme/index.css.webpack.js doesn't exist
            /data/work/git_repos/jupyterlab/jupyterlab/node_modules/jupyterlab/lib/default-theme/index.css.json doesn't exist
            /data/work/git_repos/jupyterlab/jupyterlab/node_modules/jupyterlab/lib/default-theme/index.css.web.js doesn't exist
            /data/work/git_repos/jupyterlab/jupyterlab/node_modules/jupyterlab/lib/default-theme/index.css.js doesn't exist
          resolve directory
            /data/work/git_repos/jupyterlab/jupyterlab/node_modules/jupyterlab/lib/default-theme/index.css doesn't exist (directory default file)
            /data/work/git_repos/jupyterlab/jupyterlab/node_modules/jupyterlab/lib/default-theme/index.css/package.json doesn't exist (directory description file)
    
    npm ERR! Linux 4.4.0-31-generic
    npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:extension"
    npm ERR! node v6.3.0
    npm ERR! npm  v3.10.3
    npm ERR! code ELIFECYCLE
    npm ERR! jupyterlab-extension@0.0.1 build:extension: `webpack --config webpack.conf.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the jupyterlab-extension@0.0.1 build:extension script 'webpack --config webpack.conf.js'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the jupyterlab-extension package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     webpack --config webpack.conf.js
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs jupyterlab-extension
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls jupyterlab-extension
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /data/work/git_repos/jupyterlab/jupyterlab/npm-debug.log
    
    npm ERR! Linux 4.4.0-31-generic
    npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
    npm ERR! node v6.3.0
    npm ERR! npm  v3.10.3
    npm ERR! code ELIFECYCLE
    npm ERR! jupyterlab-extension@0.0.1 build: `npm run update && npm run build:extension`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the jupyterlab-extension@0.0.1 build script 'npm run update && npm run build:extension'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the jupyterlab-extension package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     npm run update && npm run build:extension
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs jupyterlab-extension
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls jupyterlab-extension
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /data/work/git_repos/jupyterlab/jupyterlab/npm-debug.log
    
    npm ERR! Linux 4.4.0-31-generic
    npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:serverextension"
    npm ERR! node v6.3.0
    npm ERR! npm  v3.10.3
    npm ERR! code ELIFECYCLE
    npm ERR! jupyterlab@0.1.1 build:serverextension: `cd jupyterlab && npm run build && cd ..`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the jupyterlab@0.1.1 build:serverextension script 'cd jupyterlab && npm run build && cd ..'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the jupyterlab package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     cd jupyterlab && npm run build && cd ..
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs jupyterlab
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls jupyterlab
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /data/work/git_repos/jupyterlab/npm-debug.log
    rebuilding js and css failed
    missing files: ['/data/work/git_repos/jupyterlab/jupyterlab/build/bundle.js']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/work/git_repos/jupyterlab/setup.py", line 158, in <module>
        setup(**setup_args)
      File "/opt/conda/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/opt/conda/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/opt/conda/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/data/work/git_repos/jupyterlab/setup.py", line 54, in run
        raise e
    subprocess.CalledProcessError: Command '['npm', 'run', 'build:serverextension']' returned non-zero exit status 1
    
    ----------------------------------------

**Comment by fourpartswater** [comment]
Line above

Obtaining file:///data/work/git_repos/jupyterlab
    Complete output from command python setup.py egg_info:
    setup.py entered
    /opt/conda/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'License'
      warnings.warn(msg)
    running egg_info
    running jsdeps
    3.10.3
    
    > jupyterlab@0.1.1 build:serverextension /data/work/git_repos/jupyterlab
    > cd jupyterlab && npm run build && cd ..
    
    
    > jupyterlab-extension@0.0.1 build /data/work/git_repos/jupyterlab/jupyterlab
    > npm run update && npm run build:extension
    
    
    > jupyterlab-extension@0.0.1 update /data/work/git_repos/jupyterlab/jupyterlab
    > rimraf node_modules/jupyterlab && npm install
    
    npm WARN lifecycle jupyterlab@0.1.1~prepublish: cannot run in wd %s %s (wd=%s) jupyterlab@0.1.1 npm run build /data/work/git_repos/jupyterlab
    
    > jupyterlab@0.1.1 postinstall /data/work/git_repos/jupyterlab/jupyterlab/node_modules/jupyterlab
    > npm dedupe
    
    
    > jupyterlab-extension@0.0.1 postinstall /data/work/git_repos/jupyterlab/jupyterlab/node_modules/jupyterlab-extension
    > npm dedupe
    
    npm WARN lifecycle jupyterlab-extension@0.0.1~postinstall: cannot run in wd %s %s (wd=%s) jupyterlab-extension@0.0.1 npm dedupe /data/work/git_repos/jupyterlab/jupyterlab
    jupyterlab-extension@0.0.1 /data/work/git_repos/jupyterlab/jupyterlab
    └─┬ jupyterlab@0.1.1
      ├── jquery-ui@1.10.5
      └── jupyterlab-extension@0.0.1
    
    npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
    npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

**Comment by afshin** [comment]
Hello. I switched to node `v6.3.0` and python `2.7` to try to emulate your setup.

#### Clean slate
Once I had those as my session default versions, I made sure my repo was in a clean state reflecting the current `master` branch of `jupyter/jupyterlab`. Because I have my own fork, I did:
```shell
git checkout master
git clean -fdx
# My remote reference to jupyter/jupyterlab is: upstream
git fetch upstream
git rebase upstream/master
```
But you could just as easily start with a complete blank slate:
```shell
git clone https://github.com/jupyter/jupyterlab.git
cd jupyterlab
```

#### Fresh build
Next I built from scratch:
```shell
npm install
pip install -e .
jupyter serverextension enable --py jupyterlab
```
#### Run
All of that succeeded for me. Next, I ran:
```
jupyter lab
```

And it launched for me.

For completeness sake, could you try these steps and report back what happens?

**Comment by ellisonbg** [comment]
Hmm, I just pulled from master and am running into a build issue as well - slightly different though - trying to blast and rebuild

**Comment by ellisonbg** [comment]
Here are the issues I run into with `npm install`:

```
src/console/panel.ts(18,8): error TS2307: Cannot find module 'phosphor-splitpanel'.
src/console/panel.ts(72,10): error TS2339: Property 'addClass' does not exist on type 'ConsolePanel'.
src/console/panel.ts(112,10): error TS2339: Property 'orientation' does not exist on type 'ConsolePanel'.
src/console/panel.ts(114,10): error TS2339: Property 'addChild' does not exist on type 'ConsolePanel'.
src/console/panel.ts(115,10): error TS2339: Property 'addChild' does not exist on type 'ConsolePanel'.
src/console/panel.ts(116,10): error TS2339: Property 'setSizes' does not exist on type 'ConsolePanel'.
src/console/panel.ts(133,14): error TS2339: Property 'isDisposed' does not exist on type 'ConsolePanel'.
src/console/panel.ts(169,10): error TS2339: Property 'orientation' does not exist on type 'ConsolePanel'.
src/console/panel.ts(170,10): error TS2339: Property 'setSizes' does not exist on type 'ConsolePanel'.
src/console/panel.ts(180,12): error TS2339: Property 'setSizes' does not exist on type 'ConsolePanel'.
src/console/panel.ts(184,32): error TS2339: Property 'sizes' does not exist on type 'ConsolePanel'.
src/console/plugin.ts(65,35): error TS2344: Type 'ConsolePanel' does not satisfy the constraint 'Widget'.
  Property 'disposed' is missing in type 'ConsolePanel'.
src/console/plugin.ts(93,17): error TS2339: Property 'id' does not exist on type 'ConsolePanel'.
src/console/plugin.ts(94,17): error TS2339: Property 'title' does not exist on type 'ConsolePanel'.
src/console/plugin.ts(95,17): error TS2339: Property 'title' does not exist on type 'ConsolePanel'.
src/console/plugin.ts(96,17): error TS2339: Property 'title' does not exist on type 'ConsolePanel'.
src/console/plugin.ts(97,35): error TS2345: Argument of type 'ConsolePanel' is not assignable to parameter of type 'Widget'.
  Property 'disposed' is missing in type 'ConsolePanel'.
```

**Comment by blink1073** [comment]
@ellisonbg, fix is in https://github.com/jupyter/jupyterlab/pull/535

**Comment by afshin** [comment]
@fourpartswater Does your build work now? Does this issue need to remain open?

**Comment by peterklipfel** [comment]
Just forked from master. Similar looking error.

    npm ERR! cb() never called!
    rebuilding js and css failed
    missing files: ['/home/vagrant/sandbox/jupyterlab/jupyterlab/build/bundle.js']
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/vagrant/sandbox/jupyterlab/setup.py", line 158, in <module>
        setup(**setup_args)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/vagrant/sandbox/jupyterlab/setup.py", line 54, in run
        raise e
    subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1
    Complete output from command python setup.py egg_info:
    setup.py entered

**Comment by peterklipfel** [comment]
Updating to the latest version of npm (from 3.7.3 to 3.10.3) did the job. This also included an upgrade from node 5.9.2 to 6.3.1

**Comment by afshin** [comment]
Thanks @peterklipfel ... I'm not sure if we have specifically tested the version of npm you had an issue with. I'll try it out. I wonder if it could have been an old `node_modules` folder lying around or something ... but it's worth investigating. Thanks again!

**Comment by ellisonbg** [comment]
Closing as resolved, let us know if anyone runs into more problems related to this...
