### ISSUE TITLE
Trying to build a plugin

### ISSUE THREAD

**Issue by projetmbc** [jupyter/jupyterlab#525]
Hello.

Where can I find the source code of the MarkDown preview plugin ? 

I would like to build a plugin using a Python script to build the HTML output. Is it feasible ?﻿

**Comment by jasongrout** [comment]
The markdown preview is at https://github.com/jupyter/jupyterlab/tree/master/src/markdownwidget. Right now, we only support having the plugins in javascript/Typescript. I'm curious - why are you wanting to build a plugin using Python?

**Comment by projetmbc** [comment]
Thanks for pointing to me the source.

Why my question ? I would like to use my own ASCII language to produce HTML documents and also LaTeX ones (with other features). I would also like to use it inside notebook instead of MarkDown.

**Comment by ellisonbg** [comment]
Let us know if you have other questions.
