### ISSUE TITLE
Race condition in minHeight for output area

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyterlab#527]
I just noticed that there could be a race condition at https://github.com/jupyter/jupyterlab/blob/master/src/notebook/output-area/widget.ts#L430. If two of these are called in succession, then the first will save the old height as '', the second will save the first min height, then the first could reset to '', and then the second could reset to the first min height.

Really, we should set a flag about whether the min height is temporarily set, and only increase it if needed in that case, not save the old height and set a timeout. Or we should cancel the previous timeout.

**Comment by afshin** [comment]
I think your instinct is right, but instead of a flag, I would set a private _newMinHeight variable and just use that in the `onUpdateRequest` function, making sure to reset it to `null` after each update request finishes.

**Comment by jasongrout** [comment]
Great idea!

**Comment by jasongrout** [comment]
@afshin, because we actually want a small time delay, rather than just waiting on the next update() call, I left the timer in there and just make sure that only the last timer actually completes. See #839.
