### ISSUE TITLE
Multi-line Indenting not working

### ISSUE THREAD

**Issue by willzfarmer** [jupyter/jupyterlab#542]
In the traditional jupyter notebook when you select part of 1 or more lines in a cell and press tab, they indent, and outdent with shift+tab. This is not the current behavior. Currently it brings up the auto-complete prompt.

**Comment by blink1073** [comment]
cc @afshin, it looks like we need to check for a current selection before invoking auto-complete.

**Comment by afshin** [comment]
@willzfarmer Thanks for reporting the issue!

**Comment by willzfarmer** [comment]
Yep, no worries. I know the lab tool is "pre-alpha" but I'm switching over from the standard notebook view completely. I don't have the time to contribute code, but I'm more than happy to submit issues. Expect more in the future!

**Comment by jasongrout** [comment]
As far as I know, you're our first full-time user. Congrats and thanks!
