### ISSUE TITLE
Download of documents fails

### ISSUE THREAD

**Issue by verginer** [jupyter/jupyterlab#545]
In the document browser using the context menu "Download" seems to fail in several ways.
  - on the local machine it  downloads a file containing only the string "null"
     The only call visible from the debug output in this case is something like this
```
[D 09:34:05.327 LabApp] 200 GET /api/sessions?1469518445323 (::1) 0.82ms
[D 09:34:08.341 LabApp] 200 GET /api/contents/untitled.txt?content=0&1469518448334 (::1) 1.31ms
```
  - on the server (i.e. accessing jupyter remotely) causes the download to fail with the pop-up   "Download file - Dismiss",  and debug output
```
[W 09:38:49.143 LabApp] 404 GET /api/contents/edgelists/coll_network/Chemistry/edgelists/coll_network/Chemistry/0.csv?content=0&1469518990791 (10.180.49.106) 2.06ms referer=https://crisis3:8889/lab
```
The path `edgelists/coll_network/Chemistry/` is repeated which looks odd (maybe this helps).

btw I love this new user interface and the jupyter lab idea as a whole.

**Comment by blink1073** [comment]
Hi @verginer, thanks for the report and the kind words.  I've got a fix for the first in #546, working on the second problem now.
