### ISSUE TITLE
Bring forward the IPython highlighting theme

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyterlab#547]
The existing theme is written in LESS, so either we add LESS to this repo or it needs to be translated to CSS:

https://github.com/jupyter/notebook/blob/41d6da235cbf3bcf6d7f818e11a066e0fd12ff8b/notebook/static/notebook/less/highlight.less

Would also need to update the `marked` options in this file https://github.com/jupyter/jupyterlab/blob/master/src/renderers/index.ts to match https://github.com/jupyter/notebook/blob/d8fc95173b489745b172cb86719cea855ea72acd/notebook/static/notebook/js/notebook.js#L88

**Comment by jasongrout** [comment]
See #705 for an image

**Comment by ellisonbg** [comment]
I can work on this one...
