### ISSUE TITLE
'New Notebook' option in 'Notebook' at the top level menu

### ISSUE THREAD

**Issue by roshancvp** [jupyter/jupyterlab#551]
* Should the notebook menu have a 'New Notebook' option? 
* This could be more consistent as other plugins have the same option

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/12474166/17147027/a534468a-5315-11e6-987d-11ba5e9e5e8a.gif)

**Comment by blink1073** [comment]
Yep, go for it!

**Comment by roshancvp** [comment]
Sounds good!

**Comment by roshancvp** [comment]
#552
