### ISSUE TITLE
When switching tabs, code inspector needs to know in order to connect to changed notebooks/consoles.

### ISSUE THREAD

**Issue by afshin** [jupyter/jupyterlab#555]
We can implement this with the new focus tracker, but currently it's an outstanding issue in the code inspector.

Feel free to re-assign this issue if somebody else feels like taking it. If not, I'll handle it when we have the mono-repo.

cc: @sccolbert @blink1073

**Comment by jasongrout** [comment]
I think this isn't blocked anymore, now that we are using the monorepo.
