### ISSUE TITLE
matplotlib notebook backend does not work

### ISSUE THREAD

**Issue by hovren** [jupyter/jupyterlab#557]
I am trying jupyterlab 0.1.1 from conda-forge and plotting in a notebook using `%matplotlib notebook` does not work. No plot is visible.

Using `%matplotlib inline` works as expected though.

**Comment by SylvainCorlay** [comment]
@hovren this is a known issue which should be resolved soon. In matplotlib 2.0.0 (to be released soon), the notebook backend for matplotlib will be a proper jupyter interactive widget (based on ipywidgets). Custom third party widgets will be supported, although the current master branch does not have it quite yet.

**Comment by jasongrout** [comment]
Note to devs: Blocked on 3rd party widgets, which is blocked on the monorepo

**Comment by michaelaye** [comment]
Q: Is it worth trying MPL 2.0beta just for this? Anybody knows if it makes the nbagg backend work?

**Comment by jasongrout** [comment]
We now have third-party widgets! Woohoo!

**Comment by jasongrout** [comment]
(though there would still need to be extra code to get something like mpl working, I think.)

**Comment by jasongrout** [comment]
This will be tracked and implemented in the matplotlib side: https://github.com/matplotlib/jupyter-matplotlib
