### ISSUE TITLE
Use https version of help pages

### ISSUE THREAD

**Issue by verginer** [jupyter/jupyterlab#559]
If I use an `https` connection to the jupyter server then Chrome and probably most other browsers will refuse to load sites in jupyterlab served over `http` (i.e. help pages) login something like:
```
Mixed Content: The page at 'https://soandso:8888/lab' was loaded over HTTPS,
but requested an insecure resource 'http://docs.scipy.org/doc/numpy/reference/'.
This request has been blocked; the content must be served over HTTPS.
```
I have seen that most if not all listed help pages are also served over https so that could be fixed by switching to https.

**Comment by afshin** [comment]
Thanks for pointing this out. *Some* of the help resources we link to do not support HTTPS. The ones that do support HTTPS are now linked via [protocol-relative URLs](https://en.wikipedia.org/wiki/Wikipedia:Protocol-relative_URL).

<img width="685" alt="urls" src="https://cloud.githubusercontent.com/assets/159529/17247252/dc63f3e6-5589-11e6-8583-8c62af7b2900.png">
