### ISSUE TITLE
Incrementing version numbers

### ISSUE THREAD

**Issue by svenefftinge** [jupyter/jupyterlab#562]
I wondered if it was possible to increment the version for the next release right *after* you have published rather then immediately before. That would make it clear for clients that they are working against the latest and greatest instead of the latest release.

**Comment by jasongrout** [comment]
Fixed by https://github.com/jupyter/jupyterlab/commit/993a84c9b7344e797add8f339463e11d8aae6965.

I guess in general we should do "npm version patch" immediately followed by "npm version prerelease".

Thanks for bringing this up!
