### ISSUE TITLE
Pasted cells should be inserted below the selected one

### ISSUE THREAD

**Issue by F-A** [jupyter/jupyterlab#564]
Hi all,

I just started using the Jupyter lab and I really like it so far.
However, being used to the Jupyter Notebook I'm pretty confused with some Jupyter lab behavior.

For example when copying and pasting a cell, Jupyter lab insert them above the currently selected one. In Jupyter notebook, cells are pater below. Maybe it would be nice to change jupyter lab behavior for the sake of consistency?

**Comment by blink1073** [comment]
Hi @F-A, that's a good catch, thanks!
