### ISSUE TITLE
Selecting up and down cells using the "j" and "k" keys

### ISSUE THREAD

**Issue by F-A** [jupyter/jupyterlab#565]
In Jupyter notebook, it is possible to navigate through the cells using the keys "j" and "k" (in reference to Vi I guess) or the up and down arrows.

Jupyter lab accepts only the arrows keys for the navigation. Would it be possible to also add the "j" and "k"?
I know the plan is to enable customizing shortcuts, but will it be possible to set 2 differents shortcut for a single command?

**Comment by jasongrout** [comment]
It's definitely possible, just not done. Thanks for bringing it up!

**Comment by blink1073** [comment]
Dev note: This depends on the monorepo.
