### ISSUE TITLE
Improve instructions on pypi

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#582]
https://pypi.python.org/pypi/jupyterlab have minimal instruction

> This is a very early pre-alpha developer preview. It is not ready for general usage yet.

And there is no link to GitHub  repository, it just point to jupyter.org, that does not link to here. 

I think that improving the readme on PyPI, and/org have a a page that describe what woudl be jupyterlab would be good. 

I thing that having the  http://jupyter.org/jupyterlab/ page is great, though it might be a bit better suited for a branding page that match the jupyter.org theme, and can become just a normal tab,  while the current page is a bit developper focused and can be scarry for "normal" users. 

Thoughts on both of these points ?

**Comment by blink1073** [comment]
Agreed on both counts.

**Comment by jasongrout** [comment]
> I thing that having the http://jupyter.org/jupyterlab/ page is great, though it might be a bit better suited for a branding page that match the jupyter.org theme, and can become just a normal tab, while the current page is a bit developper focused and can be scarry for "normal" users.

Moved to https://github.com/jupyter/jupyter.github.io/issues/121
