### ISSUE TITLE
Post Phosphor Monorepo Tasks

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyterlab#586]
- [x] Remove `json.ts`
- [x] Remove the widgettracker in favor of the focus tracker
- [x] Replace manual activation with the dockpanel `activateWidget` (requires proper API on the app shell)
- [x] Use scrollIntoViewIfNeeded
- [x] Remove all CSS imports from code - use `default-theme` and import in `jupyterlab/index.js`
- [x] Remove uses of the `.p-Widget` modifier in CSS that would no longer be required
- [x] Use `activate()` method in the notebook for cell selection
- [x] Remove use of `npm dedupe` but add dev note about repercussions
- [ ] Expose sequences instead of arrays in properties
- [x] Update plugin tutorial
- [x] Update other tutorials as appropriate

**Comment by ellisonbg** [comment]
@blink1073 assuming the last few items here are still being worked on?

**Comment by blink1073** [comment]
Moving the last item to #755.
