### ISSUE TITLE
CSS issues with toolbars 

### ISSUE THREAD

**Issue by jacpan** [jupyter/jupyterlab#593]
CSS of the toolbars look off and partially hidden.  Not sure what is causing this

I tried creating a tabs panel and had a similar issue of the top toolbar looking partially hidden 

![screenshot](https://cloud.githubusercontent.com/assets/7809648/17309649/ba9f416c-57f4-11e6-9bdc-6355e9ec8262.jpg)

**Comment by afshin** [comment]
I just built from scratch on `master` and can't reproduce this.

Could you try doing these steps:
```
rm -rf node_modules
npm install
npm run clean
npm run build:all
jupyter lab
```

**Comment by afshin** [comment]
A clean build from scratch resolved this issue.
