### ISSUE TITLE
Is jupyterlab_extension still needed? Can cause confusing load issue...

### ISSUE THREAD

**Issue by fperez** [jupyter/jupyterlab#594]
@Carreau and I just spent a solid 3+ hours debugging some extraordinarily bizarre, non-deterministic behavior on my system, where different restarts of lab would give me either my dev copy (from git master) or a stale one.  Eventually we tracked it down to the fact that, at some point in the past, I'd installed with pip `jupyterlab_extension`, but now I have the `jupyterlab` extension installed.  The way extensions are defined is via a *dict*, not a list, in the notebook config:

```
Kerbin[.jupyter]> pwd
/Users/fperez/.jupyter

Kerbin[.jupyter]> cat jupyter_notebook_config.json
{
  "NotebookApp": {
    "nbserver_extensions": {
      "jupyterlab_extension": true,
      "jupyterlab": true
    }
  }
}
```

Because this is a dict, it gets read in non-deterministic order, so on any given session I would get one or the other... Obvious in retrospect, but the observed behavior was weird enough that it took us a while to track it down.

In any case, we're filing a separate issue on the notebook itself to at least load extensions in alphabetical order, so if nothing else, things are deterministic.

But for lab, the question is whether we need `jupyterlab_extension` at all... If it's fully deprecated, and until the bug fix propagates via notebook to remove this potentially very confusing behavior for anyone, it might be a good idea to check/protect against its presence. The fix could be just a one-liner that looks for both lab and lab_extension being loaded and warns loudly or even stops if both are found...

Thoughts?  I'd just like to spare anyone else the hours I just lost...

**Comment by Carreau** [comment]
See https://github.com/jupyter/notebook/pull/1650 for deterministicness. 

If `jupyterlab_extension` is deprecated I would recommend pushing a update that make all the operation no-op, that way it won't fail if users have it in their config. [but could still print a warning].

**Comment by fperez** [comment]
ps - edited description to correct that I'd installed `jupyterlab_extension` via pip, not conda (it was in my root conda environment, which confused me for a moment).

**Comment by fperez** [comment]
It's not available on pypi anymore, so this issue is unlikely to affect too many people. Given we're fixing most of the problem in https://github.com/jupyter/notebook/pull/1650, I'm now inclined to just close it without further action on jlab...

Thoughts, @Carreau?

**Comment by Carreau** [comment]
> Thoughts, @Carreau?

It's still nasty enough, that it can bite us later, let's leave it open just to let developers a chance to see that.

**Comment by fperez** [comment]
You mean open indefinitely?​ If it's for reference purposes, I'd rather
just close it, even closed it serves its documentation purpose... If we're
not *doing* anything else on it, we should close it, I think.

**Comment by Carreau** [comment]
> You mean open indefinitely?​

No with Jason, Brian, and other not available, leave them a chance to come back and **see** it.

**Comment by fperez** [comment]
Ah, that ​sounds fine, yes. We can close it in a few days then...
`self.callback("close this", after="1 week")`

**Comment by jasongrout** [comment]
I'll be able to look at this in about a week.

**Comment by fperez** [comment]
No ​worries, I think we have it figured out, now it's mostly
informational.  The fix in the main notebook will take care of most of the
weirdness. Unplug! :)

**Comment by jasongrout** [comment]
Thanks. Agreed that this can be closed, especially since jupyterlab_extension is not on pypi.
