### ISSUE TITLE
Lab takes 16sec to load because of fonts timeout. 

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#596]
See attached profiles, 
![screen shot 2016-08-03 at 08 48 09](https://cloud.githubusercontent.com/assets/335567/17372065/1804c030-5957-11e6-8b99-ab92a0e35dee.png)

Am I the only one to see that  ?

Little annoying as there is a white page for 15sec.

**Comment by sccolbert** [comment]
Is it blocking on loading those fonts? `bundle.js` only took ~0.5s to load.

**Comment by Carreau** [comment]
It just doesn't find the fonts, ever. And block the loading of the rest of css for 15 seconds. 
At which point it seem to give up on the font, and move to the next resources. 

I can record a gif if you like.

**Comment by sccolbert** [comment]
Is this something we can fix? It looks like it's jquery trying to load those fonts.

**Comment by sccolbert** [comment]
Worth looking into, regardless.

**Comment by Carreau** [comment]
> Worth looking into, regardless.

Well if you make the user see a whitepage for 15sec where he can  do nothing, it's pretty critical...

**Comment by sccolbert** [comment]
cc @afshin

**Comment by Carreau** [comment]
To give you an idea if my explanation is unclear...

![15](https://cloud.githubusercontent.com/assets/335567/17376569/0b6dfc4c-596b-11e6-9d41-5d837b358b8e.gif)

**Comment by afshin** [comment]
I don't think the font requests are blocking even though they're taking a long time. My suspicion is that the issue is caused by MathJax. We should add an `async` attribute to the `<script>` tag that loads it.

**Comment by afshin** [comment]
Sorry, I'm totally wrong. The MathJax stuff only loads from the web in the examples! The JupyterLab version is local.

**Comment by jasongrout** [comment]
Possibly related to #590

**Comment by jasongrout** [comment]
@Carreau - is this still an issue for you? I'm not reproducing it with Notebook 4.2. We did just remove jqueryui, so that might circumvent the issue too.

**Comment by Carreau** [comment]
> @Carreau - is this still an issue for you? I'm not reproducing it with Notebook 4.2. We did just remove jqueryui, so that might circumvent the issue too.

You are right this is not an issue for me anymore.  I would have been nice to figured out  exactly what was the cause. 

Thanks !

**Comment by jasongrout** [comment]
Thanks! I agree it would have been nice to figure it out.
