### ISSUE TITLE
Implement "Duplicate" context menu

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#597]
The "Duplicate" context menu seem not implemented, it pops up a dialog:

```
Duplicate file
File Duplicate file
DISMISS
```

It would be helpful to implement

**Comment by blink1073** [comment]
I don't follow, is this different from:

![duplicate-file](https://cloud.githubusercontent.com/assets/2096628/17517050/4197ec42-5e07-11e6-850e-b4ca6a84c05e.gif)

**Comment by Carreau** [comment]
Hum.. works now...  might have had an old version... thanks !

**Comment by hnykda** [comment]
@blink1073 

Hi, I am on the last version from `conda` and I am facing this issue. When I right click on `matmul.ipynb` on the following screen, then I click on `duplicate file`, then I get just the context menu and nothing is duplicated:

![image](https://cloud.githubusercontent.com/assets/2741256/22161295/fd92950a-df49-11e6-8770-8e90c16a3ad6.png)

**Comment by blink1073** [comment]
Wow, yep, that is a regression.  I opened #1529 to track it.
