### ISSUE TITLE
Dropdown menu missplaced when zooming in

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#6]
<img width="755" alt="screen shot 2016-06-04 at 11 12 10" src="https://cloud.githubusercontent.com/assets/335567/15801281/402e8c9e-2a45-11e6-8372-22a5b00e0252.png">

As notebook issued for teaching **a lot** and in these case you **have to** zoom in. This is pretty critical.

**Comment by sccolbert** [comment]
Interesting. I wonder if this is browser/os specific...

**Comment by sccolbert** [comment]
In any case, the fix will probably need to be at the phosphor level.

**Comment by jasongrout** [comment]
@Carreau - this works fine for me on OS X Chrome and Firefox. Is it still a problem for you? If so, what browser and OS are you using?

**Comment by Carreau** [comment]
Yes it is working for me fine as well, It might have been a chrome beta bug. 

Thanks !
