### ISSUE TITLE
Cell number "undefined" if an exception occurs before that cell is run

### ISSUE THREAD

**Issue by metaperture** [jupyter/jupyterlab#606]
Reproduce with:
```
import time
time.sleep(5)
assert False
```
And run that cell. Then, in a new cell, before the previous one completes: `print('asdf')`
When the exception propagates to the first cell, the text to the left of the second cell changes to `In [undefined]`. The previous behavior was to change it to `In [ ]`, iirc.

**Comment by metaperture** [comment]
I believe this might also cause an error when the notebook is saved in this state: `Notebook JSON is invalid: 'execution_count' is a required property`.

**Comment by blink1073** [comment]
Thanks for the report, @metaperture.
