### ISSUE TITLE
Editor not saving?

### ISSUE THREAD

**Issue by metaperture** [jupyter/jupyterlab#607]
Not sure if this is just me, but files in editor aren't saving at all. No errors are outputed in json console or in the server cmdline window.

On a similar note, "Editor Save" says the control is "Cmd-S", even though I'm on a linux box. I'm guessing "Cmd/Ctrl" should be changed based on keyboard layout or OS?

**Comment by blink1073** [comment]
Hi @metaperture, I apologize for the delay.  I can confirm that files in the editor are saving for me, using the top level menu and the `Cmd-S` shortcut on OSX.  I'm not sure why it is rending as `Cmd-S`, the shortcut is defined as `Accel-S`, which should use `Cmd` on OSX and `Ctrl` on Windows/Linux.

Are you able to save files using the text editor in `jupyter notebook`?

**Comment by shekkizh** [comment]
Hi all, I came across a similar issue where the save didn't work. I was editing a markdown file while simultaneously viewing it it in rendered format. In fact once I got into this state I couldn't save any of the files I create. There were no errors in the terminal window. The key mappings was correct though.
Restarting the lab solves the issue. Notebook works fine.
Platform: Ubuntu 16.04

**Comment by jasongrout** [comment]
@shekkizh - Restarting the lab *and* trying to do what you were doing (editing and previewing the file side by side) worked?

**Comment by shekkizh** [comment]
@jasongrout The issue didn't occur again after restarting and redoing what I was doing earlier.

**Comment by ellisonbg** [comment]
Closing for now. Please let us know if anyone runs into this issue again and we can re-open this.
