### ISSUE TITLE
Abstract Notebook over a concrete editor

### ISSUE THREAD

**Issue by akosyakov** [jupyter/jupyterlab#608]
In our case we would like to provide CellWidget for another editor (not CodeMirror), but it looks like that even base widgets hold as assumption that CodeMirror is used, e.g. BaseCellWidget.

**Comment by akosyakov** [comment]
In my implementation of ICellEditorWidget interface i need an access to the active kernel. I wonder how to achieve it.

Currently I have an idea to register custom NotebookWidgetFactory that creates a kernel aware renderer.

With such approach I have to copy over the notebook plugin, just to swap original NotebookWidgetFactory with a custom. As an alternative I can create a new plugin that depends on INotebookTracker and overrides the original with the custom. Both approaches does not sound so nice to me. Could be that there should be a plugin that provides INotebookWidgetFactory and notebook requires it instead of NotebookPanel.IRenderer?

As another option a cell editor can be aware of a kernel vis signals. It does not break uses hierarchy, but force an assumption that a cell editor always exists in some kernel aware context, like the notebook or the console.

**Comment by akosyakov** [comment]
Actually I like the idea of having the notebook factory plugin. In that case you can keep the notebook simple and let a factory register additional services, like completion and inspector handlers. The notebook just should expose handlers agnostic signals, like when the active kernel or cell changed. The factory reacts on them and registers or unregisters services.

For example, if one want to cover the following cases at once or by one it will be possible:
1. Python kernel with the default completion and inspections handlers and the code mirror based editor;
2. kernel X with the custom handlers and the code mirror based editor;
3. kernel Y with the custom handlers and the custom editor;
4. kernel Z with the default handlers and the custom editor.

He can create a new factory plugin that creates a notebook panel, listens to signals and reacts appropriately. Depending on a signal it can decide which renderer should be used, code mirror based or custom, and can even customize produced cell editors like register the default completion handler on tab key in a code mirror based cell editor. So you can also keep ICellEditorWidget interface stable and simple by removing service related signals, like completionRequested.

**Comment by blink1073** [comment]
Fixed by #609, thank you so much!
