### ISSUE TITLE
Console displaying input/output from kernel from other frontends

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyterlab#626]
When a console interacts with a kernel, it currently only displays input and output originating from that console. It would be useful to have a console option (or default???) that could display *all* input and output from a kernel. Then the console could be a running log of what was evaluated, or let others follow along with what is happening with a kernel if they can connect to the kernel.

@afshin brings up:
> what about if you're connected to the same kernel in an ipython session in your terminal? 
> or what if you're in the middle of an interactive thing like the interactive help?

This came up in conversations with @danielballan and one of his coworkers, in talking about how remote parties can follow along with computation from a notebook or console.

**Comment by afshin** [comment]
Thanks @jasongrout, @danielballan ... good idea to put this into an issue.

**Comment by jasongrout** [comment]
One thing I like about having a console linked to a notebook displaying all input/output is that it becomes something of a temporal log of execution, whereas the notebook is more spatially organized.

**Comment by blink1073** [comment]
I'd be in favor of this if we also styled the inputs/outputs based on whether they are from local or "remote" execution.

**Comment by danielballan** [comment]
I like that.

**Comment by afshin** [comment]
@jasongrout @blink1073 @danielballan Are you free to talk about this today? (Thursday Aug 11)

How does 12PM EST sound? https://appear.in/jupyter

**Comment by blink1073** [comment]
I am free from then until 12:30, then I have an appointment.

**Comment by afshin** [comment]
Short is good, if the others are also free 😸

**Comment by danielballan** [comment]
Works for me.

**Comment by jasongrout** [comment]
Sounds good for me.

**Comment by danielballan** [comment]
I'm up for taking a shot at this. It sounds like it might be semi-trivial for either of you, but maybe it's a decent next step for becoming familiar with the codebase. OK with you all if I attempt a PR?

**Comment by blink1073** [comment]
By all means!

**Comment by ellisonbg** [comment]
Ahh, I now get it. Yes, I think that a console should display all input and output from the current kernel is is connected to, regardless of who ran it (that console, another notebook, another user, etc.). I also agree we should have a visual indicator that distinguishes between the local and externally run code.

**Comment by SylvainCorlay** [comment]
It would also be useful for the notebook to have a toggleable output area displaying outputs that are not associated with a cell. It is related in that it could also display outputs of an associated console session.

For example, in the case of a comm message originating from a jupyter widget *model* (and not a view) that causes an output on stderr or stdout, nothing is printed at the moment.  See e.g. https://github.com/ipython/ipywidgets/issues/698

**Comment by danielballan** [comment]
I've made some progress on this, but one detail has me stumped. I have differentiate messages that originate from the local session from those that originate from some external session (and thus have to inserted into history).

With only one session attached to the kernel, I'm finding that `ConsoleWidget._session.id` does not match messages' `header.session` (or `parent_header.session`). I would expect them to match, since the ConsoleWidget generated the message. Am I misunderstanding the meaning of these attributes?

**Comment by danielballan** [comment]
I see that `ConsoleWidget._session._kernel._clientId` matches its messages' `parent_header.session`. Is that the right way to perform this comparison?

**Comment by ellisonbg** [comment]
I think that is what you want to use for the comparison, but @blink1073 can confirm that tomorrow...

**Comment by jasongrout** [comment]
(not sure if those are the right things to look at, but...) you'll want to use accessor functions, not the private `_*` attributes. `.session.kernel`...

**Comment by blink1073** [comment]
Confirming that the approach is correct as implemented in #708.

**Comment by ellisonbg** [comment]
We are +1 on this, but will need some UI/UX design work around the external runs.

**Comment by danielballan** [comment]
#708 is not quite there yet. Outputs are mirrored but inputs are not. I got waylaid off-boarding a colleague at my day job, but I'll push it over the finish line next week.

**Comment by afshin** [comment]
@danielballan There have been a few PRs that will cause merge conflicts with yours. If you find yourself wondering about anything, I'm happy to catch you up.

**Comment by Jogala** [comment]
Hi, did it get implemented in the end? How Can I use it? 

I posted the same question on stackoverflow, but did not get an answer:

https://stackoverflow.com/questions/54942220/select-consol-for-stdout-if-more-then-one-terminal-is-connected-to-an-ipython-ke

**Comment by jasongrout** [comment]
Right click on the console, choose to display all out put

**Comment by jasongrout** [comment]
Not that this is only for the JLab console

**Comment by Jogala** [comment]
Thanks for your fast reply! 

Is there a "easy" way to make this more generic, s.t. when I type jupyter console from bash I can pass a flag that tells it to display all output? Is it possible to mute the output on one specific terminal?

**Comment by jasongrout** [comment]
This is only for the JupyterLab web-based console. It has nothing to do with the command line `jupyter console`, which is a completely different project and codebase.

In Jupyter, the protocol is for every frontend to get the input and output from everyone. It is up to the frontend to display whatever it wants. For the JupyterLab web console, we give the user a choice to display only its own outputs, or all outputs.

If you're interested in the Jupyter terminal command-line console, here is the repo to open an issue about it: https://github.com/jupyter/jupyter_console
