### ISSUE TITLE
Strange focus issue with stdin in the console: can't recover focus if lost

### ISSUE THREAD

**Issue by fperez** [jupyter/jupyterlab#635]
This is best illustrated with a gif, but the explanation is: stdin in the console works if one starts typing immediately, but if you move focus outside of the text box, it's impossible to recover the focus. Clicking again in the text area doesn't "hold" the focus, it jumps back out immediately.

![console-stdin](https://cloud.githubusercontent.com/assets/57394/17573789/9668c8c6-5f11-11e6-857f-132b84a2e184.gif)

**Comment by blink1073** [comment]
FYI I'm working on updating focus handling in the application right now: https://github.com/jupyter/jupyterlab/pull/636

**Comment by sccolbert** [comment]
If this is in the console only, I bet it's related to the other issue you're seeing in #355

**Comment by fperez** [comment]
I thought as much, they felt kind of similar... But I figured it was worth tracking it explicitly, if nothing else to highlight the problem in more than one way and make sure we catch all its manifestations.

**Comment by fperez** [comment]
Thanks for the quick response, btw!

**Comment by AlexTugarev** [comment]
@fperez, the workaround for me was to paste something into the input field via context menu, which focuses the input field again. 

I was about to file the same issue no leaving the input field through tabbing.
