### ISSUE TITLE
Remove the Mock Context Manager in tests

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyterlab#638]
Remove the context manager and the mock context in favor of a concrete class.

**Comment by jasongrout** [comment]
Context manager fixed in #662. The removal of the mock context manager will have to wait until after jupyter/jupyter-js-services#190.

**Comment by blink1073** [comment]
I don't think this is a 0.9 issue, as it only affects the test suite, moving to 1.0, feel free to revert if you disagree.
