### ISSUE TITLE
IPywidgets issues between lab and notebook

### ISSUE THREAD

**Issue by willzfarmer** [jupyter/jupyterlab#642]
When using `ipywidgets` in the lab view I get a Javascript error

![screenshot from 2016-08-11 12-16-30](https://cloud.githubusercontent.com/assets/546524/17601538/812d7c70-5fbd-11e6-86d9-31379361a07e.png)

However when I open up the notebook in the traditional viewer, there's no error and everything just works.

(may be out of scope, but I figured I'd report it)

**Comment by jasongrout** [comment]
Lab requires the dev master of ipywidgets (which hasn't been released). Is that what you are using?

**Comment by willzfarmer** [comment]
Nope, that's probably my issue, I will verify.

I figured this might be user error on my end. Will report back.

**Comment by willzfarmer** [comment]
Yep, my fault, sorry about that.
