### ISSUE TITLE
Arrow keys don't move cell focus in cmd mode in the notebook

### ISSUE THREAD

**Issue by fperez** [jupyter/jupyterlab#643]
This means there's no easy way to navigate a long notebook with the keyboard.

**Comment by sccolbert** [comment]
Removing bug label, since this functionality is simply not-yet-implemented.

**Comment by fperez** [comment]
Ok, no prob..

**Comment by fperez** [comment]
Great, earlier than I'd hoped for (since it really was an enhancement).  Many thanks, confirming works as desired.
