### ISSUE TITLE
Compiling an empty cell doesn't clear the earlier outputs

### ISSUE THREAD

**Issue by bhanu-mnit** [jupyter/jupyterlab#646]
Even when I compile an empty cell, the earlier outputs doesn't get cleared.

Though a trivial thing but looks odd in the notebook.

**Comment by afshin** [comment]
@bhanu-mnit Thanks for the report. I can confirm that the current notebook behavior is different compared to the JupyterLab notebook behavior, so we should amend the JupyterLab behavior for feature parity.
