### ISSUE TITLE
RFC: Organization of JupyterLab styles & theming support

### ISSUE THREAD

**Issue by afshin** [jupyter/jupyterlab#647]
As the codebase for JupyterLab has grown, we have done a good job of keeping our TypeScript code organized and rationally laid out. When it comes to styling components and creating the bedrock for theming JupyterLab in the future, we are starting to realize that our CSS could be better organized.

## Problems
Here are a few problems that we need to solve:

* Our color palette is spread diffusely in CSS files for components all over the codebase. We don't have a central place for "the color that means x, y, or z".
* Our fonts, like our color palette, are also declared in too many places.
* We have a concept of `base` vs. `theme` CSS for individual components, but it's not always obvious where specific rules should go.
* Relatedly, most of our CSS is in the `src/default-theme` folder but some of it is inside individual component folders.

## Why we need CSS variables
For a project this size, to solve the first two problems outlined above, we could create a set of base rules, but the list would be long and repetitive, *e.g.*:

```css
.jp-danger-background { background-color: #ff0000; }
.jp-danger-text { color: #ff0000; }
.jp-danger-border { border-color: ##ff0000 }
/* Repeat ad infinitum for all colors, fonts, etc. */
```

## Pre-processor options
The established solution to most of these problem is to use some sort of CSS pre-processor. Here are the main contenders I propose we consider.

### Sass
[Sass](http://sass-lang.com/) is the biggest and most well-known, but it would create a Ruby dependency for our build, so I'm inclined to consider other options. But because it's the heavyweight in this arena, I've listed it here just in case somebody has a very strong bias toward using Sass.

### Less
[Less](http://lesscss.org/) is another option. It is simpler and less feature-rich than Sass, but I would suggest that for our needs, using a minimal set of features and sticking very closely to "real" CSS might be best in terms of community adoption and lowering the barrier to entry. Less is available as a `node` package, so it will not add any onerous dependencies.

### Stylus
[Stylus](http://stylus-lang.com/) is another CSS alternative that is available as a `node` package. I don't know as much about it, but it does seem to be well-received by the web development community. It is a language in its own right, which presents both an opportunity (substantially smaller code, if we embrace it) and a risk (too difficult for non-programmers who just want to write a JupyterLab theme).

* * *

My suggestion is Less, partly because `ipywidgets` has been using Less for some time and it has served that project well. We would get variables for our colors and fonts, mix-ins for commonly used idioms (if any), and we could use a very light touch with the "magic" aspects, so that anyone who can read CSS would be able to read our code.

## Organization of the styles
I would recommend creating a root-level `styles` folder that is a sibling of the `src` folder and having its directory structure mirror the `src` directory for any component that needs styling.

I would further recommend that we dispense with the `base` vs. `theme` distinction because our components are already fine-grained enough that having a single stylesheet per component makes sense. Additionally, it's not always obvious what is "base" and what is "theme" level styling, because depending on the thematic effects a designer may wish to achieve, both may need to be changed anyway.

**Please offer your feedback.** If we make the correct decisions on how to approach these issues, the impact on authors of JupyterLab themes will be substantial, and the benefit to the community and to the end-user experience is strong incentive to get it right.

**Comment by sccolbert** [comment]
If we stop making the distinction between base and theme, how do we ensure the themes of 3rd party authors take precedence over our rules in a *reliable* way, without requiring them to arbitrarily increase selector specificity?

**Comment by afshin** [comment]
@sccolbert We should compile all of our CSS into a sheet that we actually put into a `<link>` tag on the `lab.html` page so that any theme can also be a single CSS file that is added to the page. I think the idea that a theme file is basically just a copy of our CSS file with only the selectors you cared to modify (and nothing else) is the most straightforward way to handle it. This is how Bootstrap themes work, for example.

**Comment by sccolbert** [comment]
What about plugins and/or themes which are loaded dynamically?

**Comment by sccolbert** [comment]
i.e. a plugin which itself is a plugin/theme manager/loader

**Comment by afshin** [comment]
A plugin that wants to load additional themes will reliably know that there is a `<link>` tag in the DOM and can inject its own `<link>` tag *after* it.

Plugins that come with their own styles that are bundled up in Webpack will inject `<style>` tags that will come after the default `<link>` file as well, so they'll also be superseding what exists.

**Comment by ellisonbg** [comment]
There is a node version of sass:

https://github.com/sass/node-sass

However, I am fine sticking with less. It is simple and I think we should keep the css magic stuff to a minimum anyways.

In terms of how to structure the CSS/less files, I think there are a couple of things to consider:

* Many things that need styling in CSS are related to layout and structural aspects shouldn't be overridden by a theme. In an app of the complexity of JupyterLab, a theme developer may think they want to customize sizing of certain things, but it will most certainly break things.
* Users and developers who want to build a custom theme, should be able to take our own "theme" and start customizing anything in that without risking breaking much.
* This means that the things we call our "theme" shouldn't have any of the base, structural things.
* This points to continuing to have the split between base and theme CSS files.

There are other benefits to having separate base/theme css files:

* The theme css files can be compiled separately from the base ones and rely on their own less/css variables. It will get very difficult to try to manage less variables that work across different less compilation runs. This allows to to expose only the variables that are relevant for theming and maintain a seperate (more private) set of less variables from the structural stuff.
* It is easy to turn off a theme and still have jupyterlab function well for testing purposes. This will force is to write better CSS code.

So I am +1 on the base/theme separation. Only question is where all of that should go. Initial thought:

* Base should go in the directory where the ts code is to keep each plugin well isolated from each other. Only thing I don't know where to put is global base less variables.
* Theme should be its own plugin and have a separate file for the theme variables and one file per plugin.

**Comment by blink1073** [comment]
I am calling this fixed on master.
