### ISSUE TITLE
Console and notebook need larger UI/UX difference

### ISSUE THREAD

**Issue by stsievert** [jupyter/jupyterlab#648]
Right now, there's little distinction that you're in a notebook or in a console cell -- the only real difference is the background of the cell.

1. The title of the notebook could be more clear and bigger. This would help emphasize you're in a notebook.
    * Right now in the notebook you just click on the title to change it, and this could be worked into the proposed changes. This is the first thing I tried to do in my user testing and could make the transition easier.
2. There could be more distinction between the notebook and console. 
    * I would like to see using Enter instead of Shift-Enter to execute the code in the current console cell. That's the every other console works and that's what I find natural. This is perhaps the largest annoyance of mine.
    * I propose outlining the console cell in a different color to represent that hitting Enter will execute the current cell. This also provides another more apparent UI difference -- I find the background to be a small difference -- it doesn't pop out at you.

I have mocked up this interface I have in mind:

![](http://i.imgur.com/nRzfKLp.png)

**Comment by blink1073** [comment]
Hi @stsievert, thank you for the suggestions.

**Comment by ellisonbg** [comment]
This is somethign that we have discussed. In particular, the console supports a very different interaction in that only the last cell can be edited. In my mind that is the main different. Because of that I am thinking about something like the following:

* For the final console cell that is being edited, use the same exact visual style as the notebook cells in edit mode. That visual style is already optimized to communicate "this cell is being edited and can be typed in and then run". This would include the slightly darker grey back ground to the code mirror input area.
* Create a new visual style for the previously run cells in the console that is different in more significant ways. Some ideas: keep white background, put a more significant visual divider between the last cell and the others, scroll the already-run cells separately, etc.

**Comment by stsievert** [comment]
> That visual style is already optimized to communicate "this cell is being edited and can be typed in and then run".

When I use the console, I'd like to use the Return key to run the typed code, not Shift-Enter. I proposed a red outline to resolve this difference in key mapping.

![Imgur](http://i.imgur.com/qVs5aNB.png)

I think the above better represents edit + new key mapping better.

**Comment by ellisonbg** [comment]
Here is a mockup of a console redesign. The main points are these:

* Cell styles are the same as the notebook.
* Active input cell is always at the bottom with a white background and green border.
* Run cells get appended to a scrolling area above (but visually behind) the active input cell.
* The run cells get a light grey background to indicate their inactive state and are each separated by a thin grey line.
* Toolbar at the top with kernel related icon buttons.

![consoledesign](https://cloud.githubusercontent.com/assets/27600/17761814/6731d2ba-64bf-11e6-828c-0283e7a49f5c.png)

Assigning to @faricacarroll to finalize the visual design (see me for the sketch file). Who wants to code this one up?

**Comment by faricacarroll** [comment]
Here are mockups of the console redesign:

There are two versions: one version with a top toolbar and the other with a floating toolbar. The top toolbar takes up a lot of space for only having 4 icons. The abundance of white space on the toolbar also looks a little awkward to me.

The floating toolbar would be a new element to JupyterLab, but could be used in other widgets (like the ImageWidget) which also have too few toolbar items to fill up space on a toolbar appropriately. 

![desktop hd](https://cloud.githubusercontent.com/assets/19479586/17988477/6658893e-6adb-11e6-9fd4-acd36c443b9f.png)

 ![desktop hd2](https://cloud.githubusercontent.com/assets/19479586/17988483/6a1cdcb4-6adb-11e6-816c-c746aaeeb7f5.png)

**Comment by fperez** [comment]
I suggest having two separate issues: keeping this one for the UI design (since it's already going in that direction) and having a new one to focus on the Enter/Shift-Enter discussion.  

@stsievert, it turns out that can be done but it's tricky to get right. In the Qt console we indeed manage to do a decent job of getting single-Enter execution in most cases while allowing for multi-line input easily.  But we'll need to discuss how much of that we can bring here as part of our attempt at feature-parity (so we can replace the qtconsole completely with users being happy about the transition).

Do you want to open another one just for the keyboard execution behavior?

**Comment by stsievert** [comment]
@faricacarroll @ellisonbg the only other thing I'd like to see is have the output be right above the input. Past that, it looks good -- nice UI redesign.

![6a1cdcb4-6adb-11e6-816c-c746aaeeb7f5](https://cloud.githubusercontent.com/assets/1320475/18028275/df06d844-6c3f-11e6-8530-9015a11d4f79.png)

**Comment by ellisonbg** [comment]
Looking really great! Some ideas to explore:

* Output should be aligned with the code of the input.
* Let's use a small drop shadow on the past in/out scrolling area to indicate it is lower than the white stuff.
* For the grey of the past in/out and the dividers, play around with different MD greys in the 50-300 range.
* To keep things simple let's use the notebook style toolbar here, but with (run, stop, restart, clear all, kernel type, kernel status)

**Comment by ellisonbg** [comment]
@stsievert as far as where new outputs go when it is empty (top or bottom) I am not sure. Let's build it and play to see which makes more sense. I am open to both!

**Comment by sccolbert** [comment]
This is looking pretty cool. I think we could even drop the green border for the input cell, since it clearly already stands out, and is the only cell with which interaction is possible.

**Comment by jasongrout** [comment]
> is the only cell with which interaction is possible.

an input() call might take focus, so there might be other cell *outputs* that have interaction.

**Comment by sccolbert** [comment]
Fair enough. My intent was more "this is clearly the one-and-only cell which supports cell editing, i.e. you can't go back and modify history".

**Comment by jasongrout** [comment]
And I agree that setting off the cell padding color as white (as in the example), or having a thick line above the input cell, does a fine job of isolating the single input area that is active, so I agree that the green border is not needed.

**Comment by faricacarroll** [comment]
Some iterations:

* Used a notebook toolbar and included items for run, stop, restart, clear all, kernel type, kernel status
   * The closest fontawesome icon I could find to represent clear all was an x inside a circle
* Removed the green border
* Scrolling area grey color is MD Grey 100 with dividers of MD Grey 300. Bottom input cell grey is MD Grey 50.  
* Output cell is aligned with code of input cell (in the current console it is not aligned #bug)
* Added slight drop shadows to grey scrolling area

![desktop hd3](https://cloud.githubusercontent.com/assets/19479586/18070022/f126cd9c-6dff-11e6-805c-a69630f2e1f6.png)

**Comment by Carreau** [comment]
> Floating toolbar: 

> To keep things simple let's use the notebook style toolbar here, but with (run, stop, restart, clear all, kernel type, kernel status)


One related remarque with respect to toolbar vs floating toolbar which might be of interest for  long-time usage. 

I'm seeing more and more (completly subjective measure) users who have touch screen; especially on windows (surface) and some chrome pixels (I think), and iPad + smart cover.

In particular they both hold screen by the side in tablet mode; and I believe having the floating toolbar (on the right) is extremely useful as actions are reachable by the thumb (for right-handed user).

Even on "Laptop" mode, many of these users still reach  for the screen to touch it, and the position of the toolbar on the upper left side on the screen is the least optimal for right handed people; While floating position seem relatively natural to reach. 

Regardless of the above notions, it seem to me that the 2 area user will click on are: 
- the input field (bottom of th screen)
- the toolbar (top of the screen)

So it seem that the 2 main target in interactive workflow with the console are almost as far from each other as we could. (They could be left/right, agreed) 

So it _seem_ like the current location is less than optimal in most cases; I understand that in the perspective of time and to get things out we should not bikeshed on the location on things; but I think keeping the above point in mind for a potential redesign or improvements; or even for a "touchscreen" mode would be great.

**Comment by sccolbert** [comment]
@Carreau while I don't disagree, it would be great to have some survey data on the number of users wanting to use JLab with touch interaction, to ensure we focus on the right things.

**Comment by stsievert** [comment]
@Carreau @sccolbert :+1: to mobile use. I've also heard concerns about JLab + mobile and will likely use on mobile in the future.

Hm, how 'bout the design below? In this design, the input cell always stays right below the output and moves as the output expands. This is similar to how every other console works.

![f126cd9c-6dff-11e6-805c-a69630f2e1f6](https://cloud.githubusercontent.com/assets/1320475/18074146/456c4f6e-6e30-11e6-9608-dba5fa830943.png)

But initially all the white space is a tad distracting; maybe we could logo-stamp? As a user, I'd like to see the input console cells gradually cover the logo. I mocked that this idea up with a rough approximation to the style/colors above:

![f126cd9c-6dff-11e6-805c-a69630f2e1f6 2](https://cloud.githubusercontent.com/assets/1320475/18074272/1a49f6b4-6e31-11e6-81f8-bde65a60b948.png)

I do think the header text that print information about the console should remain.

**Comment by ellisonbg** [comment]
@faricacarroll I think your last mock up is getting close. But I do think we want to keep the green border, as it communicates the same thing that it does in a notebook = cell is ready for you to type.

@stsievert I did think about not pinning the input area to the bottom of the panel, but I ran into the problem you noticed - way too much white space.

There are other benefits to having the input pinned to the bottom:

* Always in the same place visually
* Easy to shrink the vertical size of the console and still see the input area
* Once a user has a screen full of run cells, the input area will be bottom pinned anyways.

I am in favor of building the version shown in @faricacarroll last mock up (but with the green border) and then having everyone play with it to see how it feels.

**Comment by stsievert** [comment]
@ellisonbg I can agree with the input being pinned to the bottom.

> Once a user has a screen full of run cells, the input area will be bottom pinned anyways.

But I dislike how far my eye has to travel to see the output for what was just typed, even if that only occurs for the first couple input cells. I still advocate for the output being pinned to the bottom as in https://github.com/jupyter/jupyterlab/issues/648#issuecomment-242923367

With the input + output being pinned to the bottom

* the most current output is always in the same place
* the eye doesn't have to travel too far at any time, similar to other consoles

and all the benefits you mentioned

**Comment by afshin** [comment]
@stsievert actually, keep in mind that there is a "banner" with the kernel and session information that will take up a bunch of vertical space ... so the gap might not be as large as you fear. This will be different for different kernels, but the IPython banner is quite big:

<img width="717" alt="banner" src="https://cloud.githubusercontent.com/assets/159529/18104184/c99ed376-6ef1-11e6-8f58-55e0b6d73954.png">

**Comment by faricacarroll** [comment]
I understand the concern @stsievert has about the large gap between input/output initially. However, I agree with @ellisonbg that for now, we can build up the original version and then user test to see how users feel about it.

Here's a mockup with the green border:

![desktop hd4](https://cloud.githubusercontent.com/assets/19479586/18105369/f8b566f4-6eb3-11e6-8cc3-2a7ae486c53e.png)

**Comment by jasongrout** [comment]
Some points of data: the chrome console inputs are directly below outputs until you get to the bottom of the screen, and then of course they are against the output. On the other hand, the Firefox console input is at the bottom, but they echo the inputs above the outputs like in the mockup above.

**Comment by fperez** [comment]
Actually @afshin, the IPython banner [just got quite a bit smaller](https://github.com/ipython/ipython/pull/9912) :)

This is what it looks like now (at a terminal, but the same info is printed on the Qt console):

![image](https://cloud.githubusercontent.com/assets/57394/18109871/20755d92-6ec9-11e6-846b-ad3272e273b3.png)

**Comment by ellisonbg** [comment]
Fixed in master!
