### ISSUE TITLE
Editor cannot push text to console

### ISSUE THREAD

**Issue by thenomemac** [jupyter/jupyterlab#649]
A fundamental part of a data science focused IDE (R studio, Spyder, numerous plugins for sublime/emacs) is the ability to push text from the script editor to the terminal. I'm proposing in this issue that such functionality is added to jupyter lab. There should exist a key combo to automatically send a line or selection of text from the editor to the Console and or the terminal tabs. I'm not sure I know enough javascript to contribute such a feature, but I thought I'd put it out there.

**Comment by jasongrout** [comment]
Discussion is happening on #450 for this. We'd love to have your input there too!
