### ISSUE TITLE
clear_output not supported in notebook

### ISSUE THREAD

**Issue by fperez** [jupyter/jupyterlab#650]
`clear_output` is used to do in-place updates of information, here's code for a simple example:

```python
from time import sleep
from IPython.display import clear_output

n, go = 0, True
while go:
    try:
        clear_output(wait=True)
        print("n=", n)
        n += 1
        sleep(0.3)
    except KeyboardInterrupt:
        go = False
        print("bye!")
```
The current nb provides this behavior:

![nb-clear-output](https://cloud.githubusercontent.com/assets/57394/17634340/00be92c0-6087-11e6-9fab-ccec4a56f186.gif)

whereas in JLab we aren't getting the in-place clearing of old output:

![jlab-clear-output](https://cloud.githubusercontent.com/assets/57394/17634356/0f3ee520-6087-11e6-9ac2-97c1f306b27b.gif)

**Comment by blink1073** [comment]
Dev note: we need to add a check to the cell `execute()` method using `KernelMessage.isClearOutputMsg()` in the iopub handler.

**Comment by fperez** [comment]
Confirming fix works, thanks!
