### ISSUE TITLE
Cell model source changed by each keystroke in editor

### ISSUE THREAD

**Issue by albanatita** [jupyter/jupyterlab#664]
Hi, 
JupyterLab is a very promising framework and I have started to play with it to understand how it works.
I have a question about the cell model: the source is changed by the editor each time that the editor document is changed, i.e., for each keystroke. I would have assumed that the cell model would be changed only when the user press <shift+enter> and that the cell is evaluated. Is there then a signal from the cell model that indicates when the model is not anymore being edited?
Thank you in advance and again great job!

**Comment by blink1073** [comment]
Thanks for the feedback, @albanatita!  If I understand it correctly, you want a cell model to emit a signal when code is about to be executed?  Or do you mean to you want to know when the user was typing in a cell for a bit, then stopped?

**Comment by albanatita** [comment]
It is indeed when the code is executed or the markdown text rendered. As I said, I play with the code and I amtrying to do a kind of "augmented chat": the chat server is a Jupyter extension and the client is a JupyterLab plugin; each chat room is a kind of shared notebook; when the user executes the code, the cell content is sent via websocket to the server and after that, broadcasted to the other clients.

**Comment by blink1073** [comment]
Thinking about how to move execution to the model:

- Execute on a raw cell is a no-op
- Execute on a markdown cell is synchronous - sets `rendered` to true on the widget
- Execute on a code cell is asynchronous, and we want to update the prompt during and after execution

Given this, I propose that we add `BaseCellModel.execute(kernel? IKernel): Promise<boolean>`, a `BaseCellModel.executed` signal, and a `CodeCellModel.executing` signal.

The respective widgets would listen to the signal on the model and take appropriate action.
The logic currently in `actions.ts` for cell execution (`Private.runCell`) should be moved to the cells.

**Comment by jasongrout** [comment]
I still think there is a big semantic difference between executing and saving a code cell, rendering and saving a markdown cell, and saving raw cell, enough so that I don't think we should call the markdown and raw cases "execution". Perhaps "save" or "finalized" or some other thing that means "doneEditingForNow".

(If we want to add some kernel request machinery to rendering markdown (perhaps inline kernel variables or something?), then I think the markdown rendering could be considered execution.)

**Comment by albanatita** [comment]
Just to illustrate the question, this is a screencast of the chat; as you can see, each keystroke of one user is displayed to the other user. It is visually nice but, in my opinion, it is a useless overloading of the network and of the server. I just need to broadcast the change when the cell is finished to be edited.

![screencast](https://cloud.githubusercontent.com/assets/13804675/17695555/650a7800-63a9-11e6-9932-89f0892974da.gif)

"finalized" could indeed be a good signal name for the `BaseCellModel` indicating that the user has finished editing the model. In this case, the signal `CodeCellModel.executing` is not necessary since, for a CodeCell, the "finalization" implies the execution of the code. And the end of the execution is already captured by a `modelChanged` signal when the output model is changed.

**Comment by blink1073** [comment]
We call it `run` uniformly in the UI, what if we added `CodeCellModel.kernel` (that can be `null`), and have a `run(): Promise<boolean>` method and a `BaseCellModel.runStatusChanged` signal with a payload of `running` or `finished`?

**Comment by albanatita** [comment]
It seems fine to me!

**Comment by jasongrout** [comment]
Or we could have a `cellInputChanged` signal on the notebook that has a payload of the cell that just changed.

**Comment by albanatita** [comment]
but in this case, it is not coherent with the `contentChanged` signal which is on each cell and not on the notebook, is it?

**Comment by jasongrout** [comment]
I guess that is different than what you are describing (cellInputChanged seems like it should be triggered when a cell is edited and then blurred, even if it wasn't executed).

It still seems to me that it would be most natural to you to have a *notebook*-level signal, not a cell-level signal. That way you could attach a single handler instead of keeping track of each cell, adding new handlers as new cells are added, etc.

**Comment by albanatita** [comment]
This is right indeed. It suits me if the signal is at the notebook level. No need to access each cell in this case.

**Comment by blink1073** [comment]
I don't know that we want to trigger a signal when a cell is blurred.  @albanatita, it seems in this case what you want is to use an `ActivityMonitor` on the `contentChanged` signal of the notebook.

https://github.com/jupyter/jupyterlab/blob/master/src/common/activitymonitor.ts

**Comment by albanatita** [comment]
So this is the case where the user stops writing for a moment (given by `timeout`). I was not aware of this 'ActivityMonitor`. However, my idea is that user may make mistakes when writing the contentof his cells (either code or markdown) and he doesn't want the other users to see all of this. Therefore, the content of the cell has to be sent only when he has pressed shift+enter. So, a signal on the notebook corresponding to the event "user has pressed shift-enter" and the model is now "frozen" would be the solution.

**Comment by jasongrout** [comment]
So how about a new `cellRun` signal on a notebook, that is just triggered when `runCell` is called? (are those names too similar?)

**Comment by blink1073** [comment]
Run cell run, see cell run.

**Comment by blink1073** [comment]
What about a `run(kernel?: IKernel)` method on the `Notebook` widget that emits a `cellsRun` signal with a sequence of cells?

**Comment by jasongrout** [comment]
Are we converging to the existing solution (https://github.com/jupyter/jupyterlab/blob/274f023dc354f644c2d06863950fd99f30914dce/src/notebook/notebook/actions.ts#L316)?

@albanatita - One deliberate design decision we've made in the current code is that running and kernels are external to a notebook, and running a cell is acting *on* a notebook, not asking a notebook to act for itself. Thus the shift-enter and notion of a cell being run is not part of the notebook scope - the notebook is more about the data model, and reflecting changes to the data model.

Is there a way to have this notification of user intent in this framework naturally?

**Comment by blink1073** [comment]
My concern is that signals should be emitted *by the object itself* where possible.  Perhaps `Notebook.runCell()` and `Notebook.cellRan()` would be a good compromise?

**Comment by jasongrout** [comment]
> My concern is that signals should be emitted by the object itself where possible.

Agreed. That's why I was puzzled how to do it, but still maintain a separation of execution and model...

**Comment by jasongrout** [comment]
Perhaps the signal should really be on the context, just like a saved signal, etc.

**Comment by blink1073** [comment]
Note that the context is not used anywhere in `actions.ts`, on purpose.  This is mean to be used in any "context" (pun intended).

**Comment by jasongrout** [comment]
@ellisonbg - you were in on the initial design of these things. Do you have thoughts on the matter too?

**Comment by jasongrout** [comment]
Summary - we want some way of signaling that a user "commits" to a cell contents with a strong intent. The current intent levels for a user specifying a cell contents, as I see it, are:

(a) typing characters in a cell
(b) blurring a cell input
(c) "running" a cell to execute a cell or render markdown

Right now the notebook/cell models know about (a) and (b), but the notebook model doesn't know about (c). The code cell widget knows about (c) since we call their execution method. The markdown cell can infer (c) since its rendered attribute changes. The question is: should we make the notebook widget aware of (c), and if so, should we move the "run" functionality into the notebook widget too?

**Comment by albanatita** [comment]
The cell widgets are aware of (c) but there is no signal emitted, right? The rendered attribute is public, though. But for code execution, I don't see where I could hook the beginning of the execution from the outside.
This concerns the widgets. Initially, my question was on the model. But after this discussion (thank you for your time), I am more convinced that I should hook signals at the interface level, more than at the model level.

**Comment by jasongrout** [comment]
CC @danielballan - Dan, this demo you see above is similar to what you and I talked about that would be valuable for Brookhaven users...

**Comment by jasongrout** [comment]
(For reference, the discussion with @danielballan is at https://github.com/jupyter/jupyterlab/issues/626)

**Comment by ellisonbg** [comment]
This is my understanding of the core issue here. Right now, we have a signal that fires everytime the model changes, which is too fine grained for some purposes. Thus, we need a more coarse grained way of monitoring changes to a cell. Some options:

1) Put an activity monitor on the cell changed signal. This is simple and doesn't require us to change anything.
2) Fire a signal based on something higher up. This might include the notebook view or the context.

I think it depends on which semantics are needed. If you simply want course grained cell model changes, then I would use 1) or fire on a cell leaving edit mode. If you care more about the execution aspect, then I would fire it from the object that knows about that event.

**Comment by albanatita** [comment]
This is a good summary. Following this discussion, I think that I will use solution 1) for the following reasons: a) I don't want code added or changed only for my purposes; if each user ask for a new signal, you will become crazy and the code bloated. So, I try to hook as much as possible on what exists. b) I have thought a bit more of the user case and I can imagine that, in the chat, the user doesn't want to have each cell broadcasted to other users. So, I may add a button next to each cell, or a general command in the palette,  to indicate that the cell has to be shared. In this case, I am dependent on the UI and not anymore only on the state of the model.
On my side, I have my answer and I have a better view of how to proceed. Thank you again.

**Comment by jasongrout** [comment]
@albanatita - Do you think we should close this issue, then?

**Comment by albanatita** [comment]
For me, it is OK to close it. I see now how to proceed.  Thank you!

**Comment by jasongrout** [comment]
Thanks. If the issue come up again, we'll have a good start on the conversation.
