### ISSUE TITLE
In Terminal, GNU screen dumps core

### ISSUE THREAD

**Issue by nfultz** [jupyter/jupyterlab#669]
In screen, I launched jupyter lab. I wanted to attach to that screen from jupyter lab's built in terminal. It didn't work :(

This is what I typed in the terminal: 

```
nfultz@nfultz:~$who
nfultz   pts/0        2016-08-15 16:56 (cpe-76-91-22-196.socal.res.rr.com)
nfultz   pts/2        2016-08-15 20:43 (76:S.1)
nfultz@nfultz:~$screen -dr
Aborted (core dumped)
nfultz@nfultz:~$screen -dr
Aborted (core dumped)
nfultz@nfultz:~$echo $TERM
xterm

```

**Comment by blink1073** [comment]
Hi @nfultz, I am not familiar with screen, but did this work using the existing `jupyter notebook`?

**Comment by blink1073** [comment]
FWIW, I just tried and was able to use `screen ipython` from my iTerm2 window and `screen -dr` in JupyterLab to take control of that session.  I am using OSX 10.11.6.

**Comment by blink1073** [comment]
I was also able to launch JupyterLab as `screen jupyter lab` and then connect to that at well.

**Comment by nfultz** [comment]
I am using Ubuntu 14.04 on AWS, which has Screen version 4.01.00devel (GNU) 2-May-06. My goal is to be able to check the console log from inside Jupyter Lab.

**Comment by nfultz** [comment]
It also did not work from `jupyter notebook` fwiw.

**Comment by nfultz** [comment]
Upgrading to screen 4.2 from backports seems to have solved the issue.
