### ISSUE TITLE
New/upload/refresh at bottom is confusing. 

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#67]
Too far from the rest of the UI element , especially on big screens. I literally searched the button for a minute, went to the command tab... 

Buttons should have visual-separations, even when not hovered, 
the change of style on hover exists (I can see that the applied style is different), but for me, on my screen I cannot see any differences.

**Comment by sccolbert** [comment]
Ping @ellisonbg @cameronoelsen, since the points you bring up were explicit design decisions.

**Comment by ellisonbg** [comment]
Yeah, we may need to rethink this. Will have the designers tackle this at
some point here.

On Tue, Jun 14, 2016 at 5:05 PM, S. Chris Colbert <notifications@github.com>
wrote:

> Ping @ellisonbg <https://github.com/ellisonbg> @cameronoelsen
> <https://github.com/cameronoelsen>, since the points you bring up were
> explicit design decisions.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyterlab/issues/67#issuecomment-226052776>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0CaMmND9aE9sgKIbW-wBV3xbWfg4ks5qL0G4gaJpZM4I13l7>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by bliker** [comment]
My suggestion would be to make it something like this. Usually only obvious things can be replaced with icons (see gmail for good example).
<img width="209" alt="screenshot 2016-06-18 23 05 31" src="https://cloud.githubusercontent.com/assets/2674600/16173674/65ce9ec0-35a9-11e6-8541-d645a7b27a20.png">

**Comment by bliker** [comment]
Actually, there may have been [different design intent](https://github.com/jupyter/jupyterlab/blob/master/src/filebrowser/theme.css#L39-L85) by @ellisonbg but the border is missing some code and it does not show up, also the hover colour does not match the rest of the UI.

**Comment by ellisonbg** [comment]
Fixed in master.
