### ISSUE TITLE
%load in notebook should focus the loaded cell

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyterlab#678]
From https://github.com/jupyter/jupyterlab/issues/581#issuecomment-240237040

> the focus after %load is on the next cell, not the current one where the data gets loaded.

**Comment by jasongrout** [comment]
Thoughts from JLab dev meeting: doing this would add special-case logic that may not apply, for example, running a whole notebook with a %load cell - what should happen then? What if there are multiple %load cells?

And perhaps %load is a bad idea anyway. We have better ways to copy code into a cell with JLab.

So closing for now, to keep the logic simpler.

**Comment by fperez** [comment]
Note that currently, %load comments out the call after executing it, so once it's been run once it gets "neutralized". 

I would be careful about completely deprecating %load: it works across all of our clients (even in terminal IPython), and it's hard to beat in terms of convenience as a way to pull in a bit of code from the filesystem or a URL (simply type `%load <path>`, including tab-completion if local).  Let's make sure if replaced, it's actually an improvement :)
