### ISSUE TITLE
Tab should not pick-up a completion. 

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#68]
Tab should not pick-up a completion, when the completer is (already) open,  tab is supposed to  complete to the common longest prefix[1] of all the completions. 

Well technically not prefix, but common longuest contiguous subsequence, as `mat<tab>` returns `matplotlib` and `%matplotlib` so the longuest prefix would be empty string.

**Comment by sccolbert** [comment]
I'm not sure I completely follow exactly what you are trying to describe. Would you mind giving a more detailed example?

**Comment by Carreau** [comment]
Would Gif And key sequence help  ? 
```
th<tab:show completer>
  <tab:common-subsequence>
  I<tab:common-subsequence>
  H<tab:common-subsequence>
  C<tab:common-subsequence>
  N<tab:common-subsequence>
  B<tab:common-subsequence>
```
![comp](https://cloud.githubusercontent.com/assets/335567/16064027/8ff37bda-3252-11e6-8912-52163d44f0c1.gif)

```
mat<tab><tab>l<tab>
```

![comp-mat](https://cloud.githubusercontent.com/assets/335567/16064026/8ff29bde-3252-11e6-9461-8e7a1db68e92.gif)

**Comment by sccolbert** [comment]
perfect. thanks!

**Comment by Carreau** [comment]
Sidenote : Codemirror doe already have a completer addon, it might be less work to reuse it instead of rewriting it.

**Comment by minrk** [comment]
It would be *great* to use the codemirror completion if at all possible, rather than our own widget.

**Comment by blink1073** [comment]
I don't think we should be relying *more* on CodeMirror, especially now that the Monaco Editor is available.  Also, a completion widget can be generically used anywhere in an application, not just in a code editor.

**Comment by afshin** [comment]
I agree with @blink1073. As an example, you could trivially attach completion to an `<input>` if completion exists as a standalone widget, so it would be easy to build "suggestion" functionality for a text field.

**Comment by jasongrout** [comment]
I agree it would be great to have a consistent completion used throughout the application. One of the things Atom did last year, for example, is to introduce their autocomplete framework: http://blog.atom.io/2015/05/15/new-autocomplete.html. If we want to go beyond what codemirror provides (especially across the entire application), it would be good to have a component for it.

For example, I can imagine jupyter widgets wanting to have a completion box, etc.

**Comment by minrk** [comment]
Editors generally have their own completion machinery, including both CodeMirror and Monaco. If we adopted Monaco, one of the effects of that should be getting *Monaco's own completion controls*. So I actually think the possibility of switching to an alternative to CodeMirror is a further argument *for* using the editor's own completion machinery, not against.

**Comment by afshin** [comment]
We have multiple environments and the three that are most relevant to this discussion going forward are the command line based `ipython`, the Jupyter notebook, and the web console. The only way to create a coherent experience is to write our own, *especially* if we want the same semantics to work in non-editor environments, like normal form fields, for example.

**Comment by sccolbert** [comment]
Writing a completion widget is not all that much work, and once we have it, we can reuse it anywhere. We get the added bonus of making it behave *exactly* how we want. @afshin makes a good argument. The completion should be consistent across all JLab controls which need it. Those controls won't *all* be running CodeMirror/Monaco.

**Comment by minrk** [comment]
I don't agree, but I'll defer to you guys.

**Comment by Carreau** [comment]
I tend to agree with min, writing a computer that behave correctly is not
that easy, and it is work we don't have to maintain if it already exists.
Codemirror's one have existed for years and still get bug fixes and
features. Though you are the ones writing the code and will be the one
maintaining it, so it's up to you.

**Comment by ellisonbg** [comment]
From a design perspective, we should have a single well designed completer
UI that is used for all of our components. How that is implemented is much
less important.

On Fri, Jun 24, 2016 at 5:48 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> I tend to agree with min, writing a computer that behave correctly is not
> that easy, and it is work we don't have to maintain if it already exists.
> Codemirror's one have existed for years and still get bug fixes and
> features. Though you are the ones writing the code and will be the one
> maintaining it, so it's up to you.
> On Jun 24, 2016 08:10, "Min RK" <notifications@github.com> wrote:
>
> > I don't agree, but I'll defer to you guys.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/jupyter/jupyterlab/issues/68#issuecomment-228372363
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AAUezzBUChCJKXx6_xZVOAalbyR75M_8ks5qO_NngaJpZM4I13s1
> >
>
> > .
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyterlab/issues/68#issuecomment-228382200>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0MRWiyPkYEPViOx1HxSWqbxRJ5glks5qO_w8gaJpZM4I13s1>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
> From a design perspective, we should have a single well designed completer
> UI that is used for all of our components. How that is implemented is much
> less important.

Personally I think that the UI appearance is not as important as the completer behaving correctly in all the edge cases. And as experienced over the last few weeks using prompt_toolkit completer with @fperez and @takluyver it is more complicated than we thought. 

The different components of the UI will likely require a slightly different set of completer. 
For example: It's not as if we had our share of bugs with respect to the notebook completer over the years: 
 - Race conditions with slow kernel, 
 - no scrolling with the page
 - should pop vertically above the cursor
 - completing to common subsequences of completions that don't share a prefix
 - completer not returning the same things (`numpy.tab` returning `.hitorgram` or `numpy.histogram`)
 - completer stealing keyboard focus.
 - multiple completer active across CodeMirror instances. 

Most of these behavior will be irrelevant on non-notebook completers if any. 

See [part of history which is not small](https://github.com/ipython/ipython/commits/3.x/IPython/html/static/notebook/js/completer.js), and the bug fix are still comming as we got a PR 10 days ago. So we **still** have some issues. 

I'm completly aware and trust that you are more than skilled enough to implement a completer UI. I'm just warning that you might underestimate the cost. Plus we also need to think about whomever is going to maintain that in the long run. [sorry but  I have no insight on how long the current funding will last, so I don't know who that might be]

Keep in mind as well that we currently have kernels that ship their own `kernel.js` which do rely on CodeMirror being present and do rely on some CodeMirror functionalities.  So replacing codemirror might not be that "easy" in practice, and we have a great piece of code already available and battle tested. Why not use it ? 

The codemirror completer appearance is completely customizable in appearance it it's appearance the concern. 

Then again it's not up to me to decide.
