### ISSUE TITLE
Fix CSS regressions from mono-repo adoption

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#680]
Hi all! Getting back at it. Just updated and saw the visual design of JupyterLab looks quite different. Before diving into further changes, I would love to get some background on the how/why/motivation for the changes.

For the record here is what master looks like:

<img width="1279" alt="screen shot 2016-08-16 at 8 17 43 pm" src="https://cloud.githubusercontent.com/assets/27600/17723388/932b9b02-63ee-11e6-821b-ba671274925a.png">

**Comment by sccolbert** [comment]
So. Most of the sketchiness has probably happened because not all of the requisite CSS changes were made when moving over to the Phosphor mono-repo. Unfortunately, we don't have a compiler which checks our CSS :)

Nevertheless, we need to fix it.

cc @blink1073 @afshin

**Comment by ellisonbg** [comment]
Congrats on getting the phosphor mono-repo in!!!

I had a feeling some of that was involved. But just so I don't waste my time discussing accidental design changes, could you clarify what aspects of the recent design changes were a deliberate choice?

**Comment by sccolbert** [comment]
I don't think there were any deliberate design changes, except for maybe the search icon in the command palette input field.

**Comment by blink1073** [comment]
I suspect *most* of this will fall out of the wash when we reorganize the css import structure, since the order of css imports will be explicit.

**Comment by ellisonbg** [comment]
Any ETA on when this stuff will be resolved - it sort of blocks further design work as I plug back in with students...

**Comment by blink1073** [comment]
If this is a priority item, I can stop working on third party extensions and do this first.  Otherwise, Darian is back on Monday.

**Comment by jasongrout** [comment]
Personally, I think while you're deep in the third-party extension stuff, it's better to stay going on that, at least until we hit a roadblock, given that Darian will be back on Monday.

**Comment by jasongrout** [comment]
Remember, we still have discussion to hash out on https://github.com/jupyter/jupyterlab/issues/647 about styling...

**Comment by jasongrout** [comment]
> saw the visual design of JupyterLab looks quite different

I'm still not sure exactly what we're discussing here, though. Can you give some examples of changes you are noticing?

**Comment by jasongrout** [comment]
@ellisonbg - this issue doesn't have anything specific UI issues to address. Can we close it in favor of more specific issues?

**Comment by blink1073** [comment]
Closing per in-person discussion with @ellisonbg.
