### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by waitingkuo** [jupyter/jupyterlab#685]
Could we have a Dockerfile for jupyterlab? Or it's preferred that put it in other repos such like <https://github.com/jupyter/docker-stacks>. I'm willing to help to add one.

**Comment by blink1073** [comment]
Hi @waitingkuo, I think docker-stacks would be the best location.

**Comment by jasongrout** [comment]
Agreed. @waitingkuo - do you want to open an issue over in the docker-stacks repo? Thanks for the suggestion!

**Comment by waitingkuo** [comment]
I'll open an issue there, thanks
