### ISSUE TITLE
Add context menu for each document type

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#691]
Right now, our main activities (notebooks, text editors, etc.) don't have a document/activity wide context menu. We have seen in user tests that users do go looking for these things and we have context menus elsewhere (file browser). We should make sure that each doc panel activity has a context menu with common per activity actions.

**Comment by jasongrout** [comment]
Steve did implement a context menu for all documents, but at least one or two people complained that the normal browser menu didn't show up then...

**Comment by jasongrout** [comment]
See #577.

**Comment by ellisonbg** [comment]
Thanks for the background. I do see the issue with the browser menus not showing up.

I am not (yet) willing to give up on the idea of context menus entirely. The reason is that during user tests, when users couldn't find what they were looking for, many of them tried to access context menus. This included (to my surprise) my 10 year old son. Before these tests I would have said that context menus were weak in their discoverability and should be used sparingly. However, based on this, I think that the users of today and become used to attempting to accomplish actions using them. Thus, while I don't think they should be the only way of accompilshing things, I do think we should offer them.

**Comment by ellisonbg** [comment]
What about offering them on more specific elements rather than the entire document? The types of things we should avoid are images and links. So maybe:

Globally:

* The tab for each document

Notebook

* The prompt areas

Editor

* Should be OK to pin to the entire document as there can't be images or links...

Terminal

* Should be OK on everything...

Console:

* Just the prompt areas

**Comment by ellisonbg** [comment]
Another option is for us to figure out

**Comment by sccolbert** [comment]
Was this closed on accident?
