### ISSUE TITLE
Adopt rendered HMTL CSS styles from classic notebook

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#697]
Right now the "rendered HTML" in markdown cells and the markdown plugin are not fully styled. The solution is to create a new CSS class, something like `jp-RenderedHTML` and port over the CSS styles from the class notebook, which live here:

https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/less/renderedhtml.less

Assigning to myself :)

**Comment by blink1073** [comment]
Fixed by #706.
