### ISSUE TITLE
Border at top and bottom of toolbar seem to have different width.

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#7]
<img width="306" alt="screen shot 2016-06-04 at 11 15 13" src="https://cloud.githubusercontent.com/assets/335567/15801303/ad8c7f26-2a45-11e6-9860-33ac5e3b9b72.png">

Not sure if this is on purpose, its ok if it stays like that, but just want to open this to make sure.

**Comment by blink1073** [comment]
Hopefully I get it right when we switch to Cameron's icons :wink:

**Comment by Carreau** [comment]
Might just be a browser bug.

**Comment by sccolbert** [comment]
This could be a floating point rounding error when mapping onto retina displays. I see this a lot on hi-dpi displays.

**Comment by jasongrout** [comment]
What info does this need?

**Comment by sccolbert** [comment]
Need to know whether it's present in other browser/OS/device combinations, or if it's limited to retina/hi-dpi displays. If it's a hi-dpi issue and the CSS is specified correctly, there's nothing we can do about it.

**Comment by jasongrout** [comment]
@Carreau - is your screenshot above on a hi-dpi screen?

**Comment by jasongrout** [comment]
For 26917b074ce4cb590eca968cb176295498c1422c, I have the same border width on a macbook pro retina display: 
<img width="110" alt="screen shot 2016-06-15 at 10 40 57 am" src="https://cloud.githubusercontent.com/assets/192614/16084169/c972a37a-32e5-11e6-8fb5-5254dc1fa708.png">

**Comment by Carreau** [comment]
Yes, Hi DPI, Chrome, OS X. Screenshot is Zoomed a bit to make it more visible.
If the CSS is the same, feel free to close,  it was just in case there was a mistake.

**Comment by jasongrout** [comment]
@Carreau, can you try on multiple browsers? If it's just Chrome, then let's chalk it up to the rounding problem.

**Comment by sccolbert** [comment]
Also ensure browser zoom is 100% - anything more or less will exacerbate rounding issues

**Comment by Carreau** [comment]
Seem to be gone in latest Chrome anyway, let's close.
