### ISSUE TITLE
Ctrl-M should switch to command mode

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#70]
Well i did not even remembered we had that shortcut that `ctrl-M`==`Esc`, but apparently my muscle memory does remember (and esc is too far from my pinkie). And with the new MacBook Pro apparently going to lose the Esc-Key, I guess it's nice to have a second usable shortcut to switch mode.

**Comment by sccolbert** [comment]
Mac is seriously losing the escape key?

Like all shortcuts, this should be made configurable. But the defaults probably should be the same as the old ones.

**Comment by Carreau** [comment]
> Mac is seriously losing the escape key?

At least the physical one [probably](http://9to5mac.com/2016/06/06/macbook-pro-oled-keyboard-concept/), as the part of the new model have apparently leaked.

> As you can see, the area where the fn-keys normally reside have been outright replaced by an OLED touch panel. 

I would not be surprised if this is true, as macs already lost the eject button that was also used to lock screen and eject usb keys, and replaced by power button. Which did cause havoc for a few month when as it's just above backspace and did power off without confirmation for a couple of month.

**Comment by sccolbert** [comment]
Ah. I would be surprised if the oled ESC key was not mapped to the standard keyboard interrupt with ESC code though.

**Comment by Carreau** [comment]
> Ah. I would be surprised if the OLED ESC key was not mapped to the standard keyboard interrupt with ESC code though.

That's assuming browser will not ask the oled screen to display something else instead of escape. Which I can see happening. So it's not really a question of esc not working, but a question of esc not being there.
