### ISSUE TITLE
Markdown renderer is adding lots of `<br/>` before tables

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#704]
If you have a raw HTML table in a markdown cell, the rendered HTML ends up with a ton of `<br/>` elements before the table. Super weird...

![screen shot 2016-08-18 at 2 41 17 pm](https://cloud.githubusercontent.com/assets/27600/17791775/f9792c8a-6551-11e6-9b0c-2e3b6da0e4c8.png)

**Comment by ellisonbg** [comment]
I have confirmed that the same table works fine in HTML output.

**Comment by ellisonbg** [comment]
Also confirmed the bug shots up in Markdown output. Thus, the problem is the markdown->HTML conversion.

**Comment by jasongrout** [comment]
This also might be a good opportunity to switch to CommonMark.

**Comment by ellisonbg** [comment]
Do we have a separate issue for that? Or should I change the title for this one?

**Comment by ellisonbg** [comment]
But wait, we are already using marked in the classic notebook and it doesn't have this problem on the same content. Hmmmm

**Comment by jasongrout** [comment]
The issue for moving to commonmark is #272 (with a WIP/somewhat stale PR at #499)

**Comment by blink1073** [comment]
This appears to have been fixed by #735.
