### ISSUE TITLE
Syntax highlighting for code blocks in markdown is different than classic notebook

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#705]
JupyterLab:

![screen shot 2016-08-18 at 2 54 59 pm](https://cloud.githubusercontent.com/assets/27600/17792088/d2fb7e8a-6553-11e6-9838-ba70a18dded5.png)

Classic:

![screen shot 2016-08-18 at 2 54 51 pm](https://cloud.githubusercontent.com/assets/27600/17792081/cdd6cbbc-6553-11e6-839d-ddb0f2a409ad.png)

**Comment by blink1073** [comment]
cf https://github.com/jupyter/jupyterlab/issues/547

**Comment by jasongrout** [comment]
As noted by @blink1073, this is a duplicate.
