### ISSUE TITLE
Close notebook / saving / saving kernel is annoying. 

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#72]
We don't have one on the current notebook, I'm starting to get develop the same feeling against this dialog than the UAC on windows vista. 

I understand why you want that, but I think that it will annoying people. 

Also, we have the "are you sure you want to leave" dialog on the other notebook, because we have no way of saving in the background. Imho closing a tab should automatically autosave, as **anyway** once we have the RT collab that **will** be the case. So no need for another change of behavior. 

I **guess** @fperez , @ian-r-rose, @ellisonbg want to be part of this conversation.

**Comment by sccolbert** [comment]
This kinda sorta ties into blocking/prompting on backspace navigation, and the decisions we need to make around that.

**Comment by ellisonbg** [comment]
I have been thinking a bit about this and agree that having two dialogs to
close a notebook is too much. Some thoughts:

* Reduce down to one dialog that has a checkbox for stopping the kernel or
not and the Cancel/OK buttons for saving.
* The only question is what to do if there aren't unsaved changes...
* Keep the current behavior of always leaving kernels running (less sure
about this).



On Tue, Jun 14, 2016 at 4:59 PM, S. Chris Colbert <notifications@github.com>
wrote:

> This kinda sorta ties into blocking/prompting on backspace navigation, and
> the decisions we need to make around that.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyterlab/issues/72#issuecomment-226051973>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0K3QYqpZeArvy9PpBoq2KCQCDTtEks5qL0B6gaJpZM4I14H1>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
Sidenote, chrome does not allow backspace to go to previous page, at least on mac.

Here is what happend when you try:

<img width="359" alt="screen shot 2016-06-16 at 19 25 00" src="https://cloud.githubusercontent.com/assets/335567/16138995/15fc3bf8-33f8-11e6-9a31-f4bfa201b9ea.png">

**Comment by ellisonbg** [comment]
Hmm, on my Mac, latest Chrome, backspace does go back a page...

On Thu, Jun 16, 2016 at 7:25 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> Sidenote, chrome does not allow backspace to go to previous page, at least
> on mac.
>
> Here is what happend when you try:
>
> [image: screen shot 2016-06-16 at 19 25 00]
> <https://cloud.githubusercontent.com/assets/335567/16138995/15fc3bf8-33f8-11e6-9a31-f4bfa201b9ea.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyterlab/issues/72#issuecomment-226665192>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0JaiW2vs29SV6ge7dneI7DKBtPSEks5qMgWzgaJpZM4I14H1>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by fperez** [comment]
Carreau, are you on a dev build of Chrome? I think that's [new behavior](https://www.engadget.com/2016/05/20/google-tests-killing-backspace-chrome), so probably not enabled in the default builds yet.

**Comment by Carreau** [comment]
> On Jun 16, 2016, at 20:10, Fernando Perez <notifications@github.com> wrote:
> 
> Carreau, are you on a dev build of Chrome? I think that's new behavior <https://www.engadget.com/2016/05/20/google-tests-killing-backspace-chrome>, so probably not enabled in the default builds yet.
> 
Apparently yes, I am, on a beta channel.

Could mac computer have switched to beta channel when I moved my Phone to beta channel ?

**Comment by fperez** [comment]
Don't know... But in any case, that change is coming to all of us soon as it trickles down the Chrome builds.

**Comment by ellisonbg** [comment]
Fixed in master.
