### ISSUE TITLE
CSS for Command Palette search icon is incorrect

### ISSUE THREAD

**Issue by sccolbert** [jupyter/jupyterlab#758]
The input node has had wonky CSS applied to it, causing it have a percentage width. This makes the icon look weird when the palette is expanded. See the screenshot below:
![capture](https://cloud.githubusercontent.com/assets/137289/17973860/9422e418-6aa9-11e6-979a-e5c2d68ccfd4.PNG)

**Comment by sccolbert** [comment]
Assigning to myself

**Comment by jasongrout** [comment]
This is also noted in #747, along with other issues (I think it's better to track it here as a focused issue.)

**Comment by spoorthyv** [comment]
I made a pull request with css fixes for the command palette and search bar.

**Comment by spoorthyv** [comment]
This is how it looks in my new version when stretched

<img width="1160" alt="screen shot 2016-08-25 at 3 13 48 pm" src="https://cloud.githubusercontent.com/assets/12418068/17987749/9a2c0204-6ad6-11e6-85b4-274ee8f365ba.png">

**Comment by afshin** [comment]
This was a byproduct of Less compilation. It is fixed here: https://github.com/jupyter/jupyterlab/pull/780

The width was actually supposed to be: `calc(100% - 18px);` and it was being mis-compiled before we switched to strict math mode.
