### ISSUE TITLE
Active tab indicator doesn't change for non-document tabs

### ISSUE THREAD

**Issue by sccolbert** [jupyter/jupyterlab#759]
As it says on the tin:

![capture](https://cloud.githubusercontent.com/assets/137289/17974097/550edfd8-6aaa-11e6-9890-777c60f5cab7.PNG)

**Comment by sccolbert** [comment]
cc @afshin @blink1073

**Comment by blink1073** [comment]
It is applied based on the focus tracker:

<img width="397" alt="screen shot 2016-08-25 at 10 18 51 am" src="https://cloud.githubusercontent.com/assets/2096628/17974859/5cef1350-6aad-11e6-8fdd-a700337beaab.png">

**Comment by blink1073** [comment]
So it always tracks the "current" tab in the main dock panel.

**Comment by sccolbert** [comment]
No it doesn't. See the screenshot. None of the selected tabs have the indicator. There's a bug somewhere.

**Comment by blink1073** [comment]
The screen shot does not help me.  You could be getting caught by the lack of "click on the tab to activate" behavior.

**Comment by blink1073** [comment]
If I click the tab, then click on the image, it gets focus and styled.

**Comment by blink1073** [comment]
@sccolbert, were you using the latest master?  If so, is your third tab an image?

![activate](https://cloud.githubusercontent.com/assets/2096628/18006088/8a4dd000-6b63-11e6-8466-744010c4681c.gif)

**Comment by AbdealiJK** [comment]
I seem to be seeing a similar issue with csvwidget but not with imagewidget.
The active tab (The blue highlight on the tab) does work for images, consoles, notebooks, and editors, but not for the table rendering of the CSVs (csvwidget).
The CSVwidget becomes active if I click on the contents of the tab though.

**Comment by blink1073** [comment]
Hi @AbdealiJK, that is because the csvwidget does not define an `onActivateRequest` method.  You are welcome to add it as part of #766.

e.g. https://github.com/jupyter/jupyterlab/blob/cc0bc34ec5bf18f3ce9342ba73106493a128ba6f/src/imagewidget/widget.ts#L96-L101

**Comment by sccolbert** [comment]
Why are we not applying a style to the current tab in each panel? It can be with `.p-TabBar-tab.p-mod-current`. No JS required.

**Comment by sccolbert** [comment]
@blink1073 Yes, and yes to your previous questions. (Master as of the day I posted the issue).

**Comment by blink1073** [comment]
Because we're singling out the current tab in the *entire* main area.
