### ISSUE TITLE
Web version of Qt Console

### ISSUE THREAD

**Issue by afshin** [jupyter/jupyterlab#76]
In addition to the notebook interface, we need to implement a web-based version of the console interface. Here are some of the tasks that will get us there:

- [x] Create a `ConsolePanel` as a container that holds a `ConsoleWidget`, similar to the way the notebook works.
- [x] Create a `ConsoleModel` that is similar to a `NotebookModel` but does not have a notion of arbitrary cell insertion.
- [x] The first child of the `ConsoleWidget` needs to be a `RawCellWidget` to hold a banner and the second needs to be a `CodeCellWidget` to hold the prompt.
- [x] The `ConsoleWidget` needs a set of keyboard bindings to emulate the Qt Console application.
- [x] The execution of the code cell needs to be separated from the notebook because it is common functionality.
- [x] After every `prompt` execution, a new `CodeCell` needs to be generated to become the new `prompt`.
- [x] The history functionality of the Qt Console needs to be implemented (i.e. navigating through past commands via arrow keys).
- [x] The contextual tooltip feature of the Qt Console needs to be implemented.
- [x] The `pager` functionality of leaving the prompt and residing within a different interactive context (*i.e.*, entering the interactive help) needs to be implemented.
- [x] The completion functionality (*i.e.*, tab completion) of the Qt Console needs to be implemented. This should be done in a way that allows the notebook, or other widgets potentially, to use it as well.

**Comment by afshin** [comment]
via @jan-matthis

> Not sure if this is the right place to throw this in: It would be very handy to have the web console closely integrated with the notebook, e.g. through magic commands. Something like `%qtweb` could spawn a console connected to the current kernel in a new tab or in an overlay. `%qtdebug` might spawn a web console with `%debug` executed inside, so that ipdb can be used with autocompletion and history.

**Comment by ellisonbg** [comment]
+1 on notebook integration, but it should be done through the UI or jlab keyboard shortcuts rather than a kernel magic. The only reason we did it that was in the qtconsole was because it was the only option at the time.

**Comment by jasongrout** [comment]
@afshin - what's the status of those remaining items?

**Comment by afshin** [comment]
@jasongrout This is what I'd like to demo today. Depending on what we decide, we might be able to close this issue.

**Comment by jasongrout** [comment]
Cool. Are you going to be able to make it tonight? It's kind of late for you. You could also demo it next Tuesday to a wider audience at the dev meeting.

**Comment by afshin** [comment]
I can do it today. If not, @blink1073 has offered to drive. I'd prefer a smaller audience.

**Comment by afshin** [comment]
cf. https://github.com/jupyter/jupyterlab/pull/494

**Comment by afshin** [comment]
I propose closing this issue as all the functionality of the Qt Console has been reimplemented at a minimal level. Everything from here out is improvement of those features.

**Comment by blink1073** [comment]
Closing, well done my friend.
