### ISSUE TITLE
Is R supported in Jupyter Lab?

### ISSUE THREAD

**Issue by alireza202** [jupyter/jupyterlab#763]
I use both Python and R with Jupyter Notebook, but I can't run any r command/code in Jupyter Lab. When I launch a R terminal or notebook, I see `IRkernel::main()` appearing, but no R code/notebook runs. They get stuck in `[*]` state.

**Comment by ellisonbg** [comment]
Hmm, I may be seeing this as well. Think we have a bug!

**Comment by AbdealiJK** [comment]
My R Kernel is working for me in jupyterlab as well as jupyter notebook.

I'm using:
 - Jupyter, Jupyterlab and IRKernel at the latest master commits (Installed from github)
 - Python 3.5, R 3.3.1

**Comment by fperez** [comment]
In my case it took a moment with `[*]` but it worked fine (this wasn't kernel start lag, as I opened in Lab an R notebook that I'd already started from ClassicNb, so the kernel was already up and running).  I'd switched tabs momentarily so I don't know how long it took to respond, but no more than ~10 seconds, possibly much less.

Afterwards it's behaving fine. I'm on master at 46e40f6.

**Comment by alireza202** [comment]
I updated the IRkernel to 0.6 version from github. I'm running R 3.2.1, and Python 2.7. It's still not working.

**Comment by fperez** [comment]
For reference, I was using Python 3.5, I only have a minimal 2.7 setup without JLab in it, and no time right now to set up a full 2.7 system.

Pinging @takluyver and @flying-sheep, perhaps one of you guys might have some ideas?  Do you think the py2/3 difference is relevant?

**Comment by jasongrout** [comment]
@alireza202 - does the R kernel work in the normal notebook (if you launch JupyterLab, and then change the URL to `/tree`?)

**Comment by flying-sheep** [comment]
hi!

i think python 2/3 shouldn’t be relevant here as we ship no python code (unrelatedly: you really should switch to modern python anyway)

aren’t there logs? do you have the newest IRkernel from git master and have you run `update.packages()`?

**Comment by fperez** [comment]
BTW @alireza202, to get logs, you can start the notebook/lab server with `--debug`.

**Comment by alireza202** [comment]
I have it on my work computer. I'll check it out on Monday.

**Comment by alireza202** [comment]
Ok, here's a strange thing. I tried running R again, it didn't work. I changed `/lab` to `/tree`, and it worked. And now it seems like it's working in `/lab` mode too.

**Comment by jasongrout** [comment]
It might have been a caching issue, maybe? We'll close this issue, then, but feel free to reopen it if you notice more problems.
