### ISSUE TITLE
Console tab name doesn't update when you switch kernels

### ISSUE THREAD

**Issue by faricacarroll** [jupyter/jupyterlab#769]
When you switch kernels in a Python 3 Console, the tab name does not update.
 
<img width="937" alt="screen shot 2016-08-25 at 3 13 18 pm" src="https://cloud.githubusercontent.com/assets/19479586/17987773/bf9d2fc2-6ad6-11e6-960f-b7e2c8320e25.png">

**Comment by blink1073** [comment]
The console tab doesn't have the name of the kernel in it anymore.  The plan was to add a toolbar with a subset of what is in the notebook toolbar, including the kernel indicators.

cc @afshin

**Comment by afshin** [comment]
Ah, but the caption does have the kernel name still. It should be updated.
