### ISSUE TITLE
Improve docs for RenderMime.IRenderer

### ISSUE THREAD

**Issue by akosyakov** [jupyter/jupyterlab#772]
It is not clear when isSafe and isSanitizable should return true and when false. Please explain assumptions about these methods and what sanitization and sanitized mean.

**Comment by blink1073** [comment]
Hi @akosyakov, does #772 answer your concerns?

**Comment by jasongrout** [comment]
> does #772 answer your concerns?

I think he means #779.

**Comment by blink1073** [comment]
Hahaha, not enough coffee when I wrote that methinks.

**Comment by akosyakov** [comment]
@blink1073 yep, sounds quite clear to me
