### ISSUE TITLE
Add badges in README

### ISSUE THREAD

**Issue by AbdealiJK** [jupyter/jupyterlab#775]
We can have the following badges in the README for easier finding resources:
 - Gitter - https://badges.gitter.im/jupyter/jupyterlab.svg
 - ReadTheDocs - https://img.shields.io/badge/docs-latest-brightgreen.svg?style=flat
 - Travis master - https://api.travis-ci.org/jupyter/jupyterlab.svg?branch=master
 - PyPI - https://img.shields.io/pypi/pyversions/jupyterlab.svg
 - Conda - https://anaconda.org/conda-forge/jupyterlab/badges/version.svg

The reason to use badges is because they're more prominent that text links.

**Comment by blink1073** [comment]
Hi @AbdealiJK, I think we should match the existing badges used by Jupyter Notebook, which we are tracking in #751 as part of our `README`/ `contributing` refactor.

**Comment by AbdealiJK** [comment]
Makes sense, although I notice that the google-group badge is there in [notebook](https://github.com/jupyter/notebook) but no gitter badge.
It would be useful to add gitter (If it's a recommended way of communicating)

**Comment by AbdealiJK** [comment]
@blink1073 can this be closed then ?

**Comment by blink1073** [comment]
Sure.
