### ISSUE TITLE
Reconsider rendering new input cell before IDLE message

### ISSUE THREAD

**Issue by svenefftinge** [jupyter/jupyterlab#781]
Currently when you send an execute message to the kernel, the notebook (or console) will immediately add another input cell. See https://github.com/jupyter/jupyterlab/blob/bc147583180f7ed2b1aa5f16ee8e00cce72ef333/src/console/widget.ts#L213

Generally it sounds like a good idea to let the user already type and not block him during the execution. But in case the generated process sends messages to gather user input we might end up with two input prompts and a hanging kernel.

**Comment by blink1073** [comment]
Hi @svenefftinge, this is behavior of the existing notebook.  We have no way of knowing if there would be a stdin request from the kernel, but if there is one, it necessarily stops kernel execution until it is fulfilled.  Execution requests are always made in the order they are generated by the client.

**Comment by svenefftinge** [comment]
ok, thanks.
