### ISSUE TITLE
Spurious "File changed" dialog appearing

### ISSUE THREAD

**Issue by fperez** [jupyter/jupyterlab#786]
This is a notebook that I'd just opened and had run a couple of cells into. No other browser tabs were open on JLab at all, and yet I got the "file changed" dialog:

![image](https://cloud.githubusercontent.com/assets/57394/18025367/adf06fd0-6bdc-11e6-8289-d38948a1c753.png)

I'd never seen this bug before, but it happened several times in a row today.  In this case, I'd had that notebook open for no more than 30 seconds.

There could be confusion regarding previous open files: while this notebook is brand new, in the same session I'd had another similarly titled ("Untitled.ipynb") open before.  But I had already shut it down and deleted the file, so this one should be completely clean.  It's possible that internally, Lab is still thinking the other one is open and is getting confused.

**Comment by blink1073** [comment]
This is related to #760 and fixed by #778.

**Comment by blink1073** [comment]
The previous "savehandler" was still alive, and what was causing this issue.
