### ISSUE TITLE
Moving tabs around seems to be slow on Firefox

### ISSUE THREAD

**Issue by AbdealiJK** [jupyter/jupyterlab#787]
In firefox, when I try moving around the tabs, I find that it takes about 5 seconds where firefox hangs before the move happens.
When I do the same in chromium, it takes less than half a second.

On checking the process usage in `htop` I find that firefox takes up 100% of one of my cores while doing this (and then goes back down to <10%). Chromium doesn't go above 20% throughout.

Using Firefox 48.0 on Fedora 24 and Chromium 52.0.2743.116

**Comment by blink1073** [comment]
Hi @AbdealiJK, can you describe a little more how you arrived in this condition?  I tried Firefox 47.0 on OSX 10.11, opened one of each type of activity from the launcher, and the tabs are responsive when moving.

**Comment by AbdealiJK** [comment]
Hm, I can't seem to be able to reproduce this.
Right now, firefox is still slower than chromium, but it does not take more than a second to move the tabs.
I think this may have been a one off occurrence on my laptop, maybe some indexing going on in the background using up resources (?)

Either way. Closing this.

**Comment by sccolbert** [comment]
@AbdealiJK Thanks for reporting this anyway! Firefox does seem to be quite a bit slower than other browsers when it comes to rearranging tabs. This should be mitigated in future release (I have a plan), but it's not super-high on my priority list given the level of effort the plan entails.

**Comment by AbdealiJK** [comment]
@sccolbert 
If you have a bit of free time sometime, it would be a good idea to note down a few of the points you have in mind to speed it up on firefox.
Maybe I could try it out or atleast it would be good documentation when implemented in the future

**Comment by jasongrout** [comment]
> This should be mitigated in future release (I have a plan),

Is this making the dock area a flat DOM structure?

**Comment by stefman2** [comment]
I too experience this issue (Mac 10.11.16 FF 48.0.1), except that, in my case, it is often far worse and Firefox appears to hang permanently, causing me to force-quit it. One thing I notice is that it seems a lot more likely to happen when I am using a local server (MAMP) for my tabs. Not sure how reproducible it is, but today I arrived at this condition by opening four local pages via localhost using MAMP, and then tried to move the rightmost tab left.
