### ISSUE TITLE
Console: use Enter instead of Shift-Enter to execute

### ISSUE THREAD

**Issue by stsievert** [jupyter/jupyterlab#789]
My first instinct when I go to the console is to hit enter to run the code. This is how every other console works.

I mentioned this in #648 but @fperez mentioned I should make it a separate issue. In this issue, he said

>  it turns out that can be done but it's tricky to get right. In the Qt console we indeed manage to do a decent job of getting single-Enter execution in most cases while allowing for multi-line input easily. But we'll need to discuss how much of that we can bring here as part of our attempt at feature-parity (so we can replace the qtconsole completely with users being happy about the transition).

**Comment by blink1073** [comment]
Thanks, @stsievert!  Dev note: we need to use [is_complete](http://jupyter-client.readthedocs.io/en/latest/messaging.html#code-completeness) message in the console when hitting enter to determine if it should be an execute or not.

**Comment by Carreau** [comment]
As a sidenote, the "is_complete" is optional in the protocol, and/or in some kernel it's hard/impossible to implement correctly so Shift-Enter should likely not be removed. 

The other side effect of using "Is complete" (with the python kernel) is that it will need an extra newline at the bottom of the cell to execute.
