### ISSUE TITLE
On serving `less` stylesheets and exposing variables

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyterlab#792]
Coming back to the subject of serving the less files so that extensions could build in-browser less stylesheets using these variables:

I think that we should not serve the entire content of the `less` source but only variables to be exposed in a separate shorter less file. There would be multiple benefits

 - This clearly separates the less variables that we can delete or rename without thinking of backward incompatibility from variables that extension author know they can rely on. (i.e. private vs public API). We could start with a very short list of variables (essentially colors) to expose.

 - Exposing only the definition of the variables allows extension users to not have to rebuild the entire jupyterlab css. (AFAIK less does not make a difference between including to read a couple of variables and building the entire css).

**Comment by SylvainCorlay** [comment]
@ellisonbg

**Comment by ellisonbg** [comment]
Yep, even though we are not using less for variables, we are defining all of our public CSS variables in a single file.
