### ISSUE TITLE
Toolbar icons look blurry

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#8]
I might be completely imagining things, or i's an optical effect.
The effect disappears for me as soon as I zoom in.

Could they be anything real like a sub-pixel width or height ?
Or an optical effect as I keep switching between tabs and the color in lab is less dark than classical notebook?

**Comment by blink1073** [comment]
We're going to be switching over to icons provided by Cameron.

**Comment by Carreau** [comment]
Ok, great !

**Comment by SylvainCorlay** [comment]
Closing for #30
