### ISSUE TITLE
Toggle Terminal Theme not working

### ISSUE THREAD

**Issue by charnpreetsingh185** [jupyter/jupyterlab#801]
Toggling the terminal theme doesn't seem to be working on the latest xterm version `1.1.3`. I played around with the versions and it works on `1.0.0` but not above it.
![launcher2](https://cloud.githubusercontent.com/assets/16314651/18059884/0371dea4-6dd0-11e6-8a44-1229ebb4f98e.gif)

**Comment by blink1073** [comment]
Hi @charnpreetsingh185, this should be fixed by #800, can you pull from master and verify?

**Comment by charnpreetsingh185** [comment]
Yep that seems to have fixed it! The only issue I see is the white scroll bar while the background color is black.

**Comment by blink1073** [comment]
Ha!  We must have missed one of the styles, care to take a crack at it?

**Comment by charnpreetsingh185** [comment]
Sure I'll take a look!
