### ISSUE TITLE
Drag & Drop Cells Between Notebooks

### ISSUE THREAD

**Issue by dhirschfeld** [jupyter/jupyterlab#806]
I think this could be a pretty useful feature as JupyterLab allows you to have multiple notebooks open at the same time, arranged however you like it would be nice to be able to easily share code (cells) between them, including moving (drag & drop) and copying (ctrl-drag)

One thing I find in the current notebook is that I may go down a path which turns out to be sub-optimal so I want to go back to try out a different method. I would like to be able to easily move the existing code cells elsewhere so they don't clutter my notebook whilst I'm working on the 2nd method but are still available should the 2nd method turn out to be worse than the first!

I know it's possible by copying/cutting the cells but I think being able to drag & drop them is a little more intuitive.

**Comment by dhirschfeld** [comment]
Just noticed that you can start a new notebook and switch its kernel to that of an existing notebook - that's pretty awesome! :)

**Comment by sccolbert** [comment]
You can already drag an output cell to make it it's own panel in the dock area (click-drag in the Out[] indicator). It should be trivial for us to support this (if we don't already).

**Comment by blink1073** [comment]
We are discussing cell drag n drop in #641.

**Comment by jasongrout** [comment]
#641 is for cell drag and drop within a single notebook.

**Comment by jasongrout** [comment]
Thanks! Solving #641 solves this, so we're closing this and tracking it there.
