### ISSUE TITLE
Review CSS standards like PostCSS/Myth/LESS/cssnext

### ISSUE THREAD

**Issue by minrk** [jupyter/jupyterlab#810]
While some of us may be more familiar with LESS coming from the existing notebook, we should seriously consider using more common, standard CSS tooling such as [postcss](http://postcss.org) or [myth](http://www.myth.io), which more closely follow web standards and the prevailing trends in the javascript community before committing to LESS. This is especially important as we are planning to make this tool choice a public API for theming (#802) rather than an internal implementation detail.

**Comment by minrk** [comment]
cc @ellisonbg

**Comment by blink1073** [comment]
@ellisonbg, @sccolbert, @afshin, and I talked about this yesterday and decided in favor of using CSS Variables, since they are an actual browser spec and are supported in all but IE/Edge (with Edge support in progress), and using a tool like Myth if needed to generate backwards-compatible CSS.

**Comment by minrk** [comment]
Thanks, @blink1073!

**Comment by rgbkrk** [comment]
This is really good to hear!

Relatedly, it's postcss + [cssnext](http://cssnext.io/) for the same aspiration of following web standard tracks.

**Comment by ellisonbg** [comment]
@rgbkrk thanks - hadn't seen cssnext!

**Comment by ellisonbg** [comment]
I should note that one of the big motivations for us adopting actual CSS variables is that we want to be able to change them at runtime in the browser without having to re-compile CSS in the browser/server. This is essentially required if we want to allow third party plugins to style themselves using the currently active theme.

However, single pass CSS processors such as cssnext or myth will help us cover situations where CSS variable are not supported.

**Comment by minrk** [comment]
I think we can consider the topic 'reviewed' and let the actual PRs and Issues stand for themselves. Thanks @ellisonbg!
