### ISSUE TITLE
TextEditor / Notebook consistency.

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#812]
Hi All, 

I'm opening that mostly as a meta-issue regarding the consistency of editing experience between codecells and the editor. 

- [ ] Tab key inconsitency:
  - Tab in notebook insert 4 spaces, (or complete)
   - Insert a tab character in the editor. 

I'll edit further if necessary feel free to edit my comment as well.

**Comment by blink1073** [comment]
It looks like we want to use this:  https://github.com/codemirror/CodeMirror/issues/3278#issuecomment-105600501

**Comment by blink1073** [comment]
cf https://github.com/jupyter/notebook/blob/41d6da235cbf3bcf6d7f818e11a066e0fd12ff8b/notebook/static/edit/js/editor.js#L63
