### ISSUE TITLE
download of non-text files fails

### ISSUE THREAD

**Issue by marami52** [jupyter/jupyterlab#817]
It is similar to issue #545 which is already resolved. However, when I download non-text files such as png files, downloaded file is damaged.

**Comment by blink1073** [comment]
Thank you for the report, @marami52.

**Comment by AbdealiJK** [comment]
Seems like ipynb is also an issue

For me:
 - Downloading .ipynb files downloads a file with the same name but has the content `[object Object]` 
 - Downloading text and csv files works fine
 - Downloading images and pdfs increases the file size by ~35% and is corrupt when opening it
