### ISSUE TITLE
Renaming a file doesnt work if only the case of letters has changed

### ISSUE THREAD

**Issue by AbdealiJK** [jupyter/jupyterlab#826]
Steps to reproduce:
 - Create a file `Untitled.ipynb`
 - Right click on it in filebrowser and click on "rename".
 - Rename it to `uNTITLED.ipynb` or `untitled.ipynb`, etc.
 - A pop up appears asking whether to overwrite the file `uNTITLED.ipynb` as it already exists (Although no such file really exists)
  - If you click on Cancel, nothing happens and the file is not renamed.
  - If you click on "Overwrite" a pop up with "Rename Error" appears and the file has been deleted.

It happens with all file extensions, not just .ipynb

**Comment by blink1073** [comment]
This looks like a limitation of the notebook server itself, I get the same behavior in the classic Notebook:

<img width="698" alt="screen shot 2016-09-01 at 10 40 14 am" src="https://cloud.githubusercontent.com/assets/2096628/18173781/89848f66-7030-11e6-98f8-1f5074016586.png">

**Comment by blink1073** [comment]
Actually, this mirrors what my OS is doing (OSX):

```bash
$ cp Untitled.ipynb untitled.ipynb
cp: untitled.ipynb and Untitled.ipynb are identical (not copied).
```

**Comment by blink1073** [comment]
Perhaps this could be special cased if old and new are identical modulo a lower-casing.

**Comment by AbdealiJK** [comment]
AH. That does make sense. I was running this test on a windows system where the cmd does not normally use case sensitivity.

Just tested this: It works fine on my linux system though. (In my linux system the cp and mv command work correctly unlike your Mac)

**Comment by jasongrout** [comment]
It's not the OS, it's the file system. HFS is case insensitive, but it does preserve case (I think there is an option when formatting to make it case sensitive). NTFS too, IIRC. However, ext* and many other filesystems on linux are case sensitive.

**Comment by jasongrout** [comment]
A *move* on OS X should work fine, though: `mv del.txt DEL.txt` correctly registers the different case.

**Comment by jasongrout** [comment]
The situation on NTFS is more nuanced: https://support.microsoft.com/en-us/kb/100625

**Comment by jasongrout** [comment]
Regardless, I think this issue should be moved to the jupyter/notebook repo, as it really is a server issue.

**Comment by jasongrout** [comment]
Actually, it looks like the notebook was made case insensitive: https://github.com/jupyter/notebook/pull/1142

**Comment by ellisonbg** [comment]
Is there anything for us to do in JupyterLab on this one? Seems like a limitation of the filesystem and notebook server.

**Comment by jasongrout** [comment]
Notebook 4.2.2 has this error, but notebook master does not (https://github.com/jupyter/notebook/pull/1142 seems to fix it). So closing, as it's already been fixed upstream. Thanks for the report!
