### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by nfultz** [jupyter/jupyterlab#845]
I'm seeing this in the log:
`
    404 GET /favicon.ico (172.31.12.243) 40.33ms referer=http://nfultz.dev.openmail.company:8888/lab
`

It would be nice to have a favicon.

**Comment by ellisonbg** [comment]
Don't we have a favicon? Wondering if there is a build problem? What version of juptyerlab are you running? How did you install?

**Comment by nfultz** [comment]
I installed by  pip install.  Here are my versions:

(jupyter)nfultz@nfultz:drive$jupyter lab --version
4.2.2
(jupyter)nfultz@nfultz:drive$jupyter --version
4.1.1

**Comment by blink1073** [comment]
Hi @nfultz, the favicon should be provided by the base NotebookApp.  Do you have a favicon when running `jupyter notebook`?

**Comment by blink1073** [comment]
Ah, it looks like running `jupyter lab` from the `jupyterlab/jupyterlab` directory itself gives this error for me, but not when run from another folder.

**Comment by nfultz** [comment]
Yep, I see the favicon when I run jupyter notebook.

**Comment by nfultz** [comment]
I usually start a virtualenv, then cd to my google drive, then start
jupyter lab there. Could that be a problem?

**Comment by blink1073** [comment]
@nfultz, I don't *think* that could be a problem, but I don't use google drive.
