### ISSUE TITLE
Audit of tab completion behavior

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#847]
The purpose of this issue is to document and audit the behavior of the tab completion in JupyterLab to make sure it closely matches the behavior in the classic notebook and command line IPython.

@Carreau am I missing anything here?

## Behaviors

- [x] Pressing tab initiates completion for the currently typed line and displays the possible completions.
- [x] Up/down arrows can be used to navigate the possible completions.
- [x] Return or a single mouse click can be used to select the currently selected completion.
- [x] If a user continues to type code while the completer is open, the typed text will be appended to the code cell and the list of completions will be filtered further.
- [x] The tab completion text is aligned with the code in the cell (see below)
- [x] Pressing esc while the completer is open should close it and focus the code cell.

## Questions

- [x] Should pressing tab once the completer is open also select the currently selected completion (it doesn't in the notebook or ipython)?

<img width="224" alt="screen shot 2016-09-06 at 10 56 30 am" src="https://cloud.githubusercontent.com/assets/27600/18284879/9e2398a6-7420-11e6-8658-1fdaf13ea9c2.png">

**Comment by Carreau** [comment]
Thanks for writing that up Brian. 

I think you got the high level important points, here are a few to consider:

 - what successive tab press do : complete to longest common sub prefix if available currently.
 - what successive tab press do when no prefix available? Nothing or select ?
 - what "will be filtered further means" ? And in particular how it affects the tab insert subprefix as fuzzy matching is inherently incompatible with subprefix. In particular current completion often erase things the user have typed. Do you query the kernel or not as kernel state is not static and new completion can arrive as you type. "Filtering" is not a good word to describe that. In current notebook it is _not_ filtering.
 - What happen if you backspace. 
 - What happen if kernel is busy.
 
Well above "prefix" is not really a prefix but longuest common _contiguous_ sequence.

As well as all the part where our completion on `np.<tab>` can return in the same request `np.histogram` and `.random` (no prefix) as 2 valid completions.


> Pressing esc while the completer is open should close it and focus the code cell.

That's an implementation description. "Escape should dismiss the completer and the user should still be able to keep writing at the cursor position" seem to be more accurate as that's what we want to achieve, not how we want to achieve it. Maybe the CodeCell never lost focus, who knows...


> The tab completion text is aligned with the code in the cell

That's assuming we don't complete before the cursor. The API allows it. `matpl<tab>` can complete to `%amtplotlib` how do you align it ?


> Pressing tab initiates completion for the currently typed line and displays the possible completions.

Completion send the all cell, not current line. In most of the case it's roughly the same though I agree. 

What about when cursor is in the middle of a token ?  `math.ac|os` and press tab for example
What about completion in function call ? (keyword arguments, parameters)

What does double click ?

Left/right arrow when completer is open ? (in many editors it picks things, but it's annoying if you have permanent as you type completer)

What about when we have multiple cursors ?

I'll revisit that later see if I remember other edge cases.

**Comment by afshin** [comment]
> Pressing tab initiates completion for the currently typed line and displays the possible completions.

With regard to this one, @fperez and I were talking about this a couple months ago, and one thing that seems like a good behavior is to automatically select a completion value *if there is only one match*. That's the behavior I have implemented in the completer. Should I keep it that way or should I change it to display even when there is only one match?

cc: @Carreau @ellisonbg

**Comment by Carreau** [comment]
> With regard to this one, @fperez and I were talking about this a couple months ago, and one thing that seems like a good behavior is to automatically select a completion value if there is only one match. That's the behavior I have implemented in the completer. Should I keep it that way or should I change it to display even when there is only one match?

Yes, that's a really good point. When there is a single completion I think we should directly compete to it.; 
that is unless you have permanent completion as you type I guess.

**Comment by afshin** [comment]
@Carreau said:
> That's assuming we don't complete before the cursor. The API allows it. `matpl<tab>` can complete to %matplotlib how do you align it ?

I don't know how to resolve this issue. In my outstanding PR (https://github.com/jupyter/jupyterlab/pull/870) I have aligned the completer with the beginning of the block that the API says it is completing (*i.e.*, the `cursor` as defined by the API response).

@ellisonbg, is there any consensus about *successive* tab key presses? The "filling in contiguous prefix matches" behavior is what it currently does. Should this change?

**Comment by afshin** [comment]
FYI, @Carreau's write-up of the tab options is very helpful. I'm just looking for what we want the Jupyter Lab completer behavior to be.

**Comment by Carreau** [comment]
> I don't know how to resolve this issue. In my outstanding PR (#870) I have aligned the completer with the beginning of the block that the API says it is completing (i.e., the cursor as defined by the API response).

Yes, I think that's perfectly reasonable. I was mostly pointing out case we might want to have a look at. 
The options for each of these case could be to:
 -  delay looking at it
 -  describe now what current completer does for future reference. 
 -  implement the exact same behavior
 -  implement a better behavior.

As I doubt even 1/2 of what I list above have been carefully thought about for current completion I'm not sure it's worse trying to replicate exactly.

> is there any consensus about successive tab key presses? The "filling in contiguous prefix matches" behavior is what it currently does. Should this change?

I think not breaking user expectations or muscle memory is a good way to have people to move over to JupyterLab. Even if we can make it better, I would prefer to pave the way for a better completion but stay close to current behavior. That will also stop pushing the line for 1.0 forward and give us a clear goal.

**Comment by afshin** [comment]
I'm going to close this issue as its points were primarily address in this PR: https://github.com/jupyter/jupyterlab/issues/870

If we need to re-visit the completer, I'd suggest a new issue.
