### ISSUE TITLE
Integration with JupyterHub

### ISSUE THREAD

**Issue by zer0n** [jupyter/jupyterlab#850]
Is it possible to configure JupyterHub and/or JupyterLab so that I can Lab within Hub?

**Comment by willingc** [comment]
Closing this issue as a duplicate

https://github.com/jupyterhub/jupyterhub/issues/725#issuecomment-245584865

**Comment by jasongrout** [comment]
(and for completeness, the answer in the comment is "Yes, it's possible." and the comment tells what to do.)
