### ISSUE TITLE
Save in split view save the wrong side

### ISSUE THREAD

**Issue by mulyoved** [jupyter/jupyterlab#864]
![9-10-2016 1-53-27 pm](https://cloud.githubusercontent.com/assets/2309907/18409962/3674daa8-775e-11e6-8802-e072780cda23.png)

split view, save from the right panel save the left panel
Chrome, Windows7

**Comment by blink1073** [comment]
Thanks for the report @mulyoved.  Based on the screen shot, the left tab is the "active tab" because it has the blue styling above the tab.  It looks like the editor widget needs to blur itself when it is no longer the active tab to avoid this confusion.

**Comment by jasongrout** [comment]
Can you give a sequence of steps to reproduce this? In your screenshot, you say "Focus in right code editor" and then do Ctrl+S. Focusing *should* make the right tab be the active one.

**Comment by mulyoved** [comment]
1. open new notebook
2. drag 2nd notebook from files section to the right side
3. modify right side panel, by typing

Results - blue line focus indication stay on the left panel while typing the in right panel

**Comment by blink1073** [comment]
@mulyoved, thank you for the great minimally reproducible example,.
