### ISSUE TITLE
Windows Install needs package bunch

### ISSUE THREAD

**Issue by hal98x** [jupyter/jupyterlab#869]
While installing jupyter lab, I ran the second command in the install instructions and got the following output 

(jptest) C:\Users\mwallace>jupyter serverextension enable --py jupyterlab --sys-
prefix

Traceback (most recent call last):
  File "C:\Users\mwallace\AppData\Local\Continuum\Anaconda2\envs\jptest\Scripts\
jupyter-serverextension-script.py", line 3, in <module>
    import notebook.serverextensions
  File "C:\Users\mwallace\AppData\Local\Continuum\Anaconda2\envs\jptest\lib\site
-packages\notebook\__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "C:\Users\mwallace\AppData\Local\Continuum\Anaconda2\envs\jptest\lib\site
-packages\notebook\nbextensions.py", line 32, in <module>
    from traitlets.config.manager import BaseJSONConfigManager
  File "C:\Users\mwallace\AppData\Local\Continuum\Anaconda2\envs\jptest\lib\site
-packages\traitlets\__init__.py", line 1, in <module>
    from .traitlets import *
  File "C:\Users\mwallace\AppData\Local\Continuum\Anaconda2\envs\jptest\lib\site
-packages\traitlets\traitlets.py", line 62, in <module>
    from .utils.bunch import Bunch
ImportError: No module named bunch

I did pip install bunch but it doesn't seem to clean up the problem. 

Windows 7 pro, Anaconda and Python 2.7

**Comment by jasongrout** [comment]
What version of traitlets do you have installed? Can you check to see if the file: C:\Users\mwallace\AppData\Local\Continuum\Anaconda2\envs\jptest\lib\site
-packages\traitlets\utils\bunch.py exists?

**Comment by hal98x** [comment]
I think my environment corrupted itself so I removed it and started over. I think it had something to do with first using pip to install and then trying to use conda via conda forge channel to fix install. I temporarily lost the link to the conda forge page. It works now. I like the interface it is very slick. I need to go back and see how you automagically ran a python program that was open in the text editor.
