### ISSUE TITLE
Reusable toolbar components

### ISSUE THREAD

**Issue by akosyakov** [jupyter/jupyterlab#891]
I would like to reuse the kernel name item and the kernel status item in the context of another module, not the notebook.

Could I propose a PR that makes them the notebook independent?

**Comment by blink1073** [comment]
Absolutely, we'll most likely want those in the code console toolbar once we add one.

**Comment by akosyakov** [comment]
@blink1073 Will it be ok to put them under `toolbar/kernel.ts`

**Comment by blink1073** [comment]
Sounds good
