### ISSUE TITLE
Left justify HTML tables in output

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#913]
Right now HTML tables in the `jp-RenderedHTMLCommon` CSS class are centered as they should be. However, in output, we should left justify these tables. This is to match the behavior in the classic notebook where we center tables/images in markdown and left justify in output.

**Comment by ellisonbg** [comment]
Fixed in master

**Comment by jorisvandenbossche** [comment]
Just installed latest from conda forge, and I seem to have this problem again:

![screenshot from 2017-06-24 10-50-10](https://user-images.githubusercontent.com/1020496/27507234-0eab4c4c-58cb-11e7-9cd6-a2b0bb57d2af.png)
