### ISSUE TITLE
Improved notebook creation commands/UI

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#917]
Right now JupyterLab has a separate command for creating a notebook for each kernel type. We want to move away from this as it won't scale well to many kernels. Our plan is to:

* Have a single "Create New Notebook" command...
* That opens a dialog that will have a select box for picking the kernel and optionally allow the notebook to be named something other than "Untitled*.ipynb"
* The default state of the dialog will be such that hitting return will give the user an Untitled notebook with the default kernel.
* Remove other notebook creation commands.
* There will be a second "Create New Default Notebook" that quickly creates an Untitled notebook with the default kernel without using a dialog.

This issue is to track this work.

**Comment by jasongrout** [comment]
I'm willing to try this, but it may also be good to make it easy for the user to add some specialized "new <kernelspec> notebook" for some common languages they use.
