### ISSUE TITLE
Send all payload messages to output

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#956]
I propose that we send all payload messages to output. The ipython kernel already has a flag for this (I always run in this mode) and nteract doing this by default. I sent a message to the main Jupyter group about this.

**Comment by jasongrout** [comment]
For reference, the message to the mailing list is at https://groups.google.com/forum/?fromgroups#!topic/jupyter/jmL0JcWxENU

**Comment by ellisonbg** [comment]
We discussed this at the weekly dev meeting and have decided to go this direction...

@minrk and @Carreau were both in favor of this

**Comment by Carreau** [comment]
I'm happy to enable that on IPython 6 by default. Or ipykernel. 
I don't think this is a jupyterLab issue (I might be wrong). 

I would **strongly** recommend, if it's a jupyterlab decision to ask other kernel authors.
