### ISSUE TITLE
Change information shown in running left panel

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#972]
* Display full paths of each console/notebook
* Don't display the kernel name below a certain width.

**Comment by blink1073** [comment]
We are not currently displaying any of the consoles (cf #161, #260), do you mean the terminals?

**Comment by blink1073** [comment]
I think the right answer here is to show just the name and the shutdown button, but have a details view that has more information: full path, kernel, etc.

**Comment by blink1073** [comment]
This should also be done as a VDOM widget.  Overall, I do not think this is a good candidate for Strata.

**Comment by ellisonbg** [comment]
The Running panel is still a huge mess. Thinking out loud here:

* In this context, the name of the kernel is much less relevant than the full notebook path. The reason is that there is no other way in our ui to easily see which notebooks are running in different directories on your system. Because of that I would move the kernel name to the hover detail.
* I would show the full path in the UI, but right align it and put overflow hidden. This will then show the notebook name and as much of the path that fits.
* Keep full path in hover tooltip.
* We will also need to properly style the buttons but that is a separate issue
