### ISSUE TITLE
Only parse and display a limited number of rows

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#976]
Right now the CSV widget blindly parses the entire file and tries to display it. The d3 parsing library we have can parse only certain lines of a file. We should only parse and display the first N lines of a CSV file, where N is a number we play with to see where performance problems hit. Guessing that 500-1000 is a good start...

**Comment by ellisonbg** [comment]
Pinging @sccolbert as this will be solved in a better way by the grid widget he is building...

**Comment by ellisonbg** [comment]
While we are doing this, let's also put the table header and body in `thead` and `tbody` elements to pick up the full default table styling we are offering. Note: I am adding the needed CSS class to pick up that style in a separate PR...

**Comment by sccolbert** [comment]
I can tackle this, or the `thead/tbody` portion of it at least. 

For the partial parsing, is this really needed for the demo? If we do it, are we actually needing to implement a virtual renderer here? I assume you'd still want to be able to scroll through the entire data set?

**Comment by blink1073** [comment]
I checked the docs for d3, and it parses the entire file.  We can dynamically choose which of those rows to render based on scroll position, but IMO that should wait until we have a grid widget.  I think the best we can do now is set a hard limit on the number of rows and console warn if it is above a certain number.

**Comment by ellisonbg** [comment]
Fixed for now in master...
