### ISSUE TITLE
Split off the geojson file viewer as a separate 3rd party extension

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyterlab#980]
We removed it as part of the TS 2.0 update. This will be a good first test of the [Typescript cookie cutter recipe](https://github.com/jupyter/jupyterlab-extensionts-cookiecutter).

Also, from Brian
> Great, I think that labextension should define a MIME renderer for geo JSON as well so it works in notebook/console output as well using the application/vnd.geo+json MIME type. Then the file viewer can just use that renderer

**Comment by jasongrout** [comment]
See https://github.com/jupyter/jupyterlab_geojson for work in progress.

**Comment by blink1073** [comment]
I confirmed that the dev install instructions for the referenced, thanks @jasongrout!
