### ISSUE TITLE
Buggy cursor/selection logic when using up arrow to go to rendered markdown cell

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterlab#981]
See attached screen capture.

![markdownbug](https://cloud.githubusercontent.com/assets/27600/18884357/1ab8d026-84b5-11e6-9833-479ca41edc8c.gif)

**Comment by sccolbert** [comment]
What's the desired behavior?

**Comment by ellisonbg** [comment]
The markdown cell should be selected, but the codemirror editor from the previously selected cell should be blurred to the cursor goes away.

**Comment by blink1073** [comment]
The classic notebook converts the cell to `edit` mode in this case, I will copy that behavior.

**Comment by jasongrout** [comment]
See also #906 where a similar issue was noted.
